https://github.com/tycrek/degoogle/blob/master/README.md
http://subjectguides.lib.neu.edu/awd
https://ai.googleblog.com/2018/07/improving-connectomics-by-order-of.html?m=1
https://systems-research.slack.com/join/shared_invite/enQtNjAyNTU2MTYwMTEyLWVjYTdiMjJlZTEwMzY0ZGQ0YzM4M2I0ODA3NWVjYjE2OGZiZTM1YTQwNTM3ZTdiZThkNTY4ZDY5NDY2N2QyMTQ
https://github.com/kylesferrazza/slack-racketbot?files=1
https://github.com/danambrogio/cardfetch
https://redex.racket-lang.org/
https://www.theatlantic.com/magazine/archive/2017/04/why-is-silicon-valley-so-awful-to-women/517788/?fbclid=IwAR29wNYuXh_R64gXgw7CTN6mVZlFNjrwMdd4YQkYv3lEWZUFZQMvqFq66x0
https://en.m.wikipedia.org/wiki/Control_flow_analysis
https://blog.plover.com/book/free-hop.html
https://philip.greenspun.com/blog/
[[https://www.quantamagazine.org/einstein-symmetry-and-the-future-of-physics-20190626/][complex ideas, simple solutions]]
[[https://nora.codes/][cool person, col ideas]]
[[https://nora.codes/post/names-legal-names-and-fractally-deferred-responsibility/][i like their article abt names !]]
[[http://tilde.town/][community for art !]]
[[https://mikestone.me/watching-in-linux][watch cmd in linux]]
[[https://write.as/][focused writing]]
[[https://slim.computer/][v cool person !! ! ! !]]
[[https://4042302.org/][error page as 302 :: links never died!]]
[[http://willcrichton.net/][incredible site]]
[[https://flak.tedunangst.com/post/good-idea-bad-implementation-crosstalk][good idea bad impl]]
[[https://github.com/makccr/dot/tree/3f8d8b40a81e5aa82fbcc7f98f9eeb86247b86e1][good config?]]
[[https://www.youtube.com/watch?v=FYTZkE5BZ-0&app=desktop][powerful]]
[[https://thedorkweb.substack.com/p/tales-from-the-dork-web-10][diy smartwatch]]
[[https://derivationmap.net/][map of physics derivations]]
[[http://bootstrappable.org/][phil for builds]]
[[https://matrix.org/blog/2020/06/02/introducing-p-2-p-matrix][p2p matrix]]
[[http://opentaxsolver.sourceforge.net/index.html][do taxes open soruce]]
[[https://github.com/browserdotsys/vecchio][ray tracing fast]]
[[https://github.com/TimPut/timput.com][very cool website org]]
[[https://news.ycombinator.com/item?id=23408144][two minute chats]]
[[https://zserge.com/posts/jvm/][writing a toy jvm]]
[[https://kk.org/thetechnium/68-bits-of-unsolicited-advice/][68 bits of advice]]
[[https://electro.pizza][cool person]]
[[https://www.tessera.li/][mathviz]]
[[https://starthouse.xyz/?ref=hn][startup pitches]]
[[https://blog.akinori.org/][self indulgence]]
[[https://www.fossil-scm.org/home/doc/trunk/www/fossil-v-git.wiki][fossil!]]
[[https://blog.nil.im/?78][what is objfw>]]
[[https://usesthis.com/interviews/rachel.demy/][great interviews and website]]
https://aperiodical.com/2020/06/review-immersive-linear-algebra/ review for
linalg
[[https://en.m.wikipedia.org/wiki/Ricci_calculus][rules and indices for tensor and tensor fields!]]
[[https://bartoszmilewski.com/2020/05/27/guitar-decomposed-5-mutating-the-third/][guitar in haskell]]
[[https://git.sr.ht/~ft/9pro][tools for sourcehut!]]
[[https://wiki.xxiivv.com/site/discourse.html][on discourse.]]

#+TITLE: things to learn
* signal processing/compression
https://github.com/PyWavelets/pywt

* people
https://en.m.wikipedia.org/wiki/L%C3%A1szl%C3%B3_Polg%C3%A1r
http://www1.ece.neu.edu/~eyeh/
http://www.ccs.neu.edu/home/hlnguyen/
http://www.ccs.neu.edu/home/rancohen/
https://christine.website/contact
https://jswrenn.comhttp://www.ccs.neu.edu/home/hlnguyen/
http://www.ccs.neu.edu/home/rancohen/
https://christine.website/contact
https://jswrenn.com//
http://people.cs.uchicago.edu/~jhr/
https://www.ccs.neu.edu/home/ryanc/
http://users.umiacs.umd.edu/~hal/cv.html
https://users.cs.northwestern.edu/~jesse/
http://worrydream.com/#!/Bio -- this guy has done a lot and has a lot of
interests
http://cs.brown.edu/research/plt/ -- self explanatory
https://lexi-lambda.github.io/resume.html -- alexis king -- brilliant racket and
haskell programmer
https://www.reddit.com/r/haskell/comments/fyyia7/which_major_code_bases_should_i_study_to_better/
http://blog.ezyang.com/about/ -- edward yang, a stanford phd student who works
with ml and functional languages
https://ryanjung.dev/ -- in fundies, has great personal website -- work on mine!
http://justinpombrio.net/ -- pl guy, phd student from brown
https://www.antonok.com/ -- good work in rust, have talked to him, cool guy
https://shreyaskapur.com/ -- mit undergrad, really on top of it
https://nicholas-miklaucic.github.io/ -- northeastern guy, great blog
https://guillaumelegoy.github.io/ -- Boring Data Science blog with lots of cool
trinkets
http://seinfeld.co/library/
http://herpolhode.com/rob/ -- archer, unix guy who writes about things!
https://web.stanford.edu/~ouster/cgi-bin/home.php -- behind raft; cool dude http://aviral.io/ -- prl phd student who does a lot of cool work
https://en.wikipedia.org/wiki/Greg_Marinovich -- photographer who has worked at
a lot of different places, very well known, he works in BU
http://willghatch.net/blog/ -- good writing on a bunch of people doing things
with operating systems
https://jborichevskiy.com/ideas/ -- this person has a lot of cool ideas r work
https://www-cs-faculty.stanford.edu/~knuth/retd.html -- of course, knuth
http://lav.io/ lots of gool 3d and visual art work
http://madebyevan.com/ -- 3d stuff !
https://en.wikipedia.org/wiki/Daniel_S._Weld
http://mumble.net/~jar/ -- this guy works on cool open source things
https://miles.land/#portfolio -- very cool and entreprenurial !
https://winston.me/ -- winston seems cool
https://www.karenx.com/ -- high profile filmmaker and designer
https://www.theguardian.com/culture/2020/apr/29/nats-what-i-reckon-the-sweary-ranty-youtuber-whos-become-an-isolation-cooking-sensation
-- good cook!!
http://homes.sice.indiana.edu/samth/ -- sam tobin something, student of matthias
[[http://number-none.com/blow/][jon blow, game dev and compiler guy]]
** matthias
https://felleisen.org/matthias/Thoughts/Referential_Transparency.html
https://felleisen.org/matthias/Thoughts/Why_How_do_I_get_a_PhD.html -- on grad
school
https://link.springer.com/article/10.1007/BF00277387
https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-20.html#%_idx_2990
sicp, somehow
https://www.cis.upenn.edu/~halleyy/ phd student working on generative models
https://mitpress.mit.edu/sites/default/files/sicp/index.html
http://ccs.neu.edu/home/types/extras/extras.html -- been greenman, cool guy!
https://felleisen.org/matthias/4620-s18/index.html
https://felleisen.org/matthias/7480-s17/lectures.html -- talks from a lot of PL
people
** mike shah
http://www.mshah.io/pizza/artofpizza.html pizza
http://www.mshah.io/conf/18/cppcon/index.html debugging with the gui
cpp, llvm and all that.
https://docs.google.com/presentation/d/1jps3KpD2zbsBwwApDnsU9LsgpXX-8ttmwtwEKoNKHt8/mobilepresent#slide=id.g358c9a0181_0_7
https://docs.google.com/presentation/d/1gkVFtXpXcySlu7qiPaaACIMAXBT0Cfn_p_yBn1NFrOs/mobilepresent#slide=id.g17dd02dfa8_4_16

** olin shivers
http://www.ccs.neu.edu/home/shivers/autoweapons.html
his thesis is incredible
https://news.ycombinator.com/item?id=2382531
stuff about olin
comedy:
http://www.ccs.neu.edu/home/shivers/autoweapons.html
https://www.wanderings.net/notebook/Main/BitterAcknowledgmentsOfOlinShivers
http://www.ccs.neu.edu/home/shivers/newstyle.html
http://www.ccs.neu.edu/home/shivers/scribblings.html
** knuth
https://www-cs-faculty.stanford.edu/~knuth/boss.html
https://www-cs-faculty.stanford.edu/~knuth/news08.html
https://www-cs-faculty.stanford.edu/~knuth/taocp.html
https://www-cs-faculty.stanford.edu/~knuth/retd.html
https://www-cs-faculty.stanford.edu/~knuth/vita.html
https://www-cs-faculty.stanford.edu/~knuth/cp.html

** sam stites : prob programming, ml
https://stites.io/ -- great writing on neural networks
** jake kinsella
peer of mine, several cool personal projects
https://github.com/TheLocust3/hierarchy -- trello clone with trees and graphs
https://github.com/TheLocust3/full-stack-vm -- virtual machine!
https://jakekinsella.com/projects/intel8080/ -- emulator for intel 8080
processor - emulation could be cool
* sus links
https://web.archive.org/web/20130507230947/http://www.heise.de/tp/artikel/2/2898/1.html
https://web.archive.org/web/20130507230947/http://www.heise.de/tp/artikel/2/2898/1.html
https://meet.jit.si/ -- free meetings and stuff
http://www.catb.org/hacker-emblem/?utm_source=Hackaday.com&utm_campaign=ec4864ced1-EMAIL_CAMPAIGN_2020_02
http://www.jsfuck.com/

** category theory
https://en.wikibooks.org/wiki/Haskell/Category_theory -- haskell and categories!
https://en.wikipedia.org/wiki/Monad_(category_theory)#Algebras_for_a_monad
https://en.wikipedia.org/wiki/Kleisli_category -- category for monads
Does every monad arise from an adjunction?
http://www.haskellforall.com/2013/02/you-could-have-invented-comonads.html
https://en.wikipedia.org/wiki/Monad_(category_theory)#Algebras_for_a_monad
https://stackoverflow.com/questions/3870088/a-monad-is-just-a-monoid-in-the-category-of-endofunctors-whats-the-problem
http://comonad.com/reader/
https://ncatlab.org/nlab/show/comonad#definition
 http://comonad.com/reader/ -- curry howard lambek currespondence guides researchers into computation. rea    ding a logic like type theory is a definitional trick as it is just reinterpretation of syntax. syntactic     categories are difficult to connect to categorical semantics

* systems
http://people.cs.pitt.edu/~jacklange/teaching/cs2510-f17/

https://github.com/NatTuck/pancake -- this looks kinda wild, figure out what
it's doing!
* physical
https://github.com/xingyif/raft
https://www.youtube.com/watch?v=hUzri2ybm_Y
** bio
neurobiology
in vivo / ex vivo
in vitro
beta tau optimization
radio tracers : technological or approval barrier? a combination of the both,
really, technology not developed for this. none o these are good enough to
definitively say they can be implemented
learn about brains and chemistry stuff!! work in lab!
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2633703/
https://www.nature.com/articles/nchem.2889
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4289634/
http://worrydream.com/#!/LearnableProgramming designing a programming system for
understanding programs
https://www.maa.org/news/interview-tony-derose  -- from computer graphics pioneer

https://catalog.princeton.edu/catalog/SCSB-8534958 -- b
https://kk.org/thetechnium/68-bits-of-unsolicited-advice/?utm_campaign=Recomendo&utm_medium=email&utm_source=Revue%20newsletter
* math
https://www.quantamagazine.org/amazing-math-bridge-extended-beyond-fermats-last-theorem-20200406/

* talks
https://www.reddit.com/r/ProgrammingLanguages/comments/fxc504/do_you_know_any_interesting_talks_about_pl/
https://www.youtube.com/watch?v=yy8jQgmhbAU&app=desktop
https://www.realtimerendering.com/raytracinggems/
https://www.benawad.com/scraping-recipe-websites/
https://www.youtube.com/watch?v=P1ww1IXRfTA&t=&app=desktop
[[https://www.hillelwayne.com/talks/software-history/?utm_source=hillelwayne&utm_medium=email][what we can learn from software history]]
[[https://www.hillelwayne.com/10x/][good programmers can be bad for industry]]
[[https://www.hillelwayne.com/hate-your-tools/][hate your tools]]
[[http://bangbangcon.com/livestream][fun, 10 min fast talks!]]
* funny
https://aphyr.com/posts/342-typing-the-technical-interview excellent article
on navigating the technical interview

https://github.com/lampepfl/dotty/issues/7598 -- on the equality operator
http://matt.might.net/articles/electric-meat/ -- his whole blog is incredible
* designing code
http://gamesfromwithin.com/data-oriented-design
https://overreacted.io/goodbye-clean-code/
https://www.ybrikman.com/writing/2013/09/29/the-10x-developer-is-not-myth/
https://brianmckenna.org/blog/softwerewolves

* being a developer
https://www.youtube.com/watch?v=M1t0egTZY44&app=desktop
https://muldoon.cloud/programming/2020/04/17/programming-rules-thumb.html
https://kk.org/thetechnium/68-bits-of-unsolicited-advice/
https://billwadge.wordpress.com/2020/04/25/the-secret-of-software-success/
https://www.deprocrastination.co/blog/3-tricks-to-start-working-despite-not-feeling-like-it
https://www.reddit.com/r/MachineLearning/comments/6l2esd/d_why_cant_you_guys_comment_your_fucking_code/

* etc
https://outline.com/gdqBaR
https://h313.info/ i like this site
https://andres.systems/
https://github.com/h313
http://dontfragment.com/using-python-yaml-and-jinja2-to-generate-config-files/
http://nathancorbyn.com/
https://www.perell.com/blog/peter-thiel
https://an-vu.com/What-I-m-Reading
https://www.goodreads.com/book/show/2333956.The_Annotated_Turing?ac=1&from_search=true&qid=6DmPQiMHk9&rank=1
https://pluralistic.net/
https://craphound.com/
https://erik.itland.no/
https://vsupalov.com/docker-arg-env-variable-guide/
https://varkor.github.io/blog/2018/11/10/monadic-do-notation-in-rust-part-i.html
https://www.pythonforbeginners.com/files/reading-and-writing-files-in-python
https://www.philosophicalhacker.com/post/data-point-for-job-seeking-devs/
https://benwiser.com/blog/My-blog-is-now-generated-by-Google-Docs.html
https://www.philosophicalhacker.com/post/data-point-for-job-seeking-devs/
https://macwright.org/2020/05/10/spa-fatigue.html
https://www.quantamagazine.org/how-to-design-a-perpetual-energy-machine-20200401/
http://www.catb.org/esr/structure-packing/
https://www.karenx.com/blog/how-to-become-a-designer-without-going-to-design-school
https://andrewkelley.me/post/not-a-js-developer.html
https://andrewkelley.me/post/intro-to-zig.html
https://en.m.wikipedia.org/wiki/Bonini%27s_paradox
https://linkurio.us/
https://m.youtube.com/watch?v=HyzD8pNlpwI
https://m.youtube.com/watch?v=b2AjRklfWQo
https://m.youtube.com/watch?v=dS6rCaDSwW8
https://m.youtube.com/watch?v=DpXy041BIlA&feature=youtu.be
https://m.youtube.com/watch?v=X3l0fPHZja8
https://joshtriplett.org/
https://m.youtube.com/watch?v=oYk8CKH7OhE
https://m.youtube.com/watch?v=XpDsk374LDE
https://mobile.twitter.com/sylefeb/status/1258808333265514497
https://m.youtube.com/watch?v=rq1DRuB9p7w
https://m.youtube.com/watch?v=TH9VCN6UkyQ
https://m.youtube.com/watch?v=4t1K66dMhWk
https://varkor.github.io/blog/2018/11/10/monadic-do-notation-in-rust-part-i.html
https://gcc.gnu.org/onlinedocs/gcc/Static-Analyzer-Options.html
https://marctenbosch.com/news/2020/05/siggraph-2020-technical-paper-n-dimensional-rigid-body-dynamics/
https://nikic.github.io/2020/05/10/Make-LLVM-fast-again.html
https://m.youtube.com/watch?feature=youtu.be&v=oTMuzM_-_0M
https://arxiv.org/abs/1805.09501
https://ban.ai/multics/
https://www.multicians.org/simulator.html
https://cs-syd.eu/posts/2020-04-28-genvalidity-improvements
https://metacademy.org/
https://news.ycombinator.com/item?id=23032243
https://medium.com/@thezedwards/the-2020-url-querystring-data-leaks-millions-of-user-emails-leaking-from-popular-websites-to-39a09d2303d2
https://sourcehut.org/blog/2020-04-30-the-sourcehut-hub-is-live/
http://www.sizecoding.org/wiki/Game_of_Life_32b
https://kasvith.me/posts/how-we-created-a-realtime-patient-monitoring-system-with-go-and-vue/
https://thedesignsquiggle.com/
https://machinelearningmastery.com/learn-add-numbers-seq2seq-recurrent-neural-networks/
http://www.julianzucker.com/
https://hasura.io/
https://www.planetminecraft.com/project/harry-potter-adventure-map-3347878
https://caseymuratori.com/blog_0038
https://rachelbythebay.com/w/2020/04/30/dev/
https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/
https://www.gnu.org/fun/jokes/eternal-flame.html
https://nesslabs.com/science-of-curiosity

https://blog.twitter.com/engineering/en_us/topics/open-source/2020/hunting-a-linux-kernel-bug.html

https://johnkerl.org/doc/ortho/ortho.html writing math well
https://medium.com/@anilkoonath/my-son-was-locked-in-his-body-for-27-years-then-he-found-his-voice-f9a4bedb1d0e
powerful
https://mobile.twitter.com/naval/status/1002103360646823936 how to get rich
or smth
https://www.newyorker.com/magazine/2017/06/05/the-work-you-do-the-person-you-are
https://blog.plover.com/misc/half-baked.html tired answers to half baked
questions !! both article on category theory but commentary on stack exchange
https://www.the-tls.co.uk/articles/feynman-making-the-extraordinary-look-easy/
incredible work on feynman
https://nesslabs.com/too-busy-to-enjoy-life
https://en.m.wikipedia.org/wiki/Onfim
https://ciechanow.ski/gears/ incredibly well done article on gears -- learn
the topic, but more importantly learn how to develop such good articles
https://qnkxsovc.gitlab.io/prob-vis/ another incredible writeup
https://macwright.org/
https://www.quantamagazine.org/amazing-math-bridge-extended-beyond-fermats-last-theorem-20200406/
http://norvig.com/21-days.html
https://github.com/mist64
https://www.instupendo.com/about
https://github.com/puffnfresh
https://blog.theboringtech.io/2020/04/16/time_is_the_real_currency.html
https://en.m.wikipedia.org/wiki/Wikipedia_Seigenthaler_biography_incident
https://en.m.wikipedia.org/wiki/Parable_of_the_broken_window
https://acoup.blog/2020/04/24/fireside-friday-april-24-2020/
* employment/work/practical
https://erikbern.com/2019/02/21/headcount-targets-feature-factories-and-when-to-hire-those-mythical-10x-people.html
https://erikbern.com/2020/01/13/how-to-hire-smarter-than-the-market-a-toy-model.html
https://erikbern.com/2020/03/10/never-attribute-to-stupidity-that-which-is-adequately-explained-by-opportunity-cost.html
https://www.tbray.org/ongoing/When/202x/2020/04/29/Leaving-Amazon -- hating
amazon
https://erikbern.com/2018/08/16/business-secrets-from-terrible-people.html
https://www.newgrad.tech/
https://www.cs.princeton.edu/~bwk/advice.html being productive by yourself in
cs
https://binarysearch.io/
https://mtlynch.io/solo-developer-year-2/ working solo
https://news.ycombinator.com/item?id=22050802 getting job through hn!
https://www.reddit.com/r/cscareerquestions/comments/9ujawa/programming_language_theory_jobs/
jobs in pl!
https://news.ycombinator.com/item?id=22990872 -- inspirational thread about
joirneys
https://www.reddit.com/r/ProgrammingLanguages/comments/9ffiky/how_to_get_a_job_in_programming_languages/
https://www.reddit.com/r/ProgrammingLanguages/comments/9bft4d/do_you_know_of_compilerish_job_opportunities_for/
https://en.m.wikipedia.org/wiki/Horn_clause
https://iism.org/article/driving-engineers-to-an-arbitrary-date-is-a-value-destroying-mistake-49
https://github.com/aftertheflood/sparks
https://nullprogram.com/blog/2020/04/30/
https://en.m.wikipedia.org/wiki/OODA_loop
https://esphome.io/
https://afnan.io/posts/lambda-calculus/

* living
https://www.gwern.net/In-Defense-Of-Inclusionism
https://hiepph.github.io/post/2017-11-24-emacs-org-syncthing/
https://iism.org/article/driving-engineers-to-an-arbitrary-date-is-a-value-destroying-mistake-49
https://rachelbythebay.com/w/2020/05/07/serv/
machiavelli what we got wrong
https://aeon.co/ideas/hypocognition-is-a-censorship-tool-that-mutes-what-we-can-feel
http://www.aaronsw.com/weblog/hatethenews
https://fs.blog/2012/04/feynman-technique/
https://surfingcomplexity.blog/2020/05/05/the-hard-parts-about-making-it-look-easy/
https://news.ycombinator.com/item?id=23092657
https://www.lifehack.org/articles/productivity/how-stop-procrastinating-and-stick-good-habits-using-the-2-minute-rule.html
https://psyarxiv.com/29ryz
https://www.robinsloan.com/notes/home-cooked-app/
https://mobile.twitter.com/david_perell/status/1257484391204352002
https://en.m.wikipedia.org/wiki/StartUp_(podcast)
https://en.m.wikipedia.org/wiki/How_To_Fail_at_Almost_Everything_and_Still_Win_Big
http://matt.might.net/articles/what-cs-majors-should-know/
http://www.cs.uni.edu/~wallingf/blog/archives/monthly/2019-11.html coveting
an online prescence
https://www.svese.de/impact-vs-backlog-frame-in-software-development
https://news.ycombinator.com/item?id=23091136
https://news.ycombinator.com/item?id=23088219
https://www.newyorker.com/magazine/2007/02/12/two-heads
https://www.indexventures.com/perspectives/rebirth-robotics-how-covariant-unlocks-power-deep-learning-robots/
https://thomask.sdf.org/blog/2019/11/09/take-care-editing-bash-scripts.html
http://www.call-with-current-continuation.org/
https://news.ycombinator.com/item?id=23057411
https://www.palabra.io/index.html
https://emacs.stackexchange.com/questions/5359/how-can-i-troubleshoot-a-very-slow-emacs
https://www.gwern.net/In-Defense-Of-Inclusionism
https://sarahguo.com/
https://blogs.scientificamerican.com/guest-blog/john-conway-reminiscences-about-dr-matrix-and-bourbaki/
https://en.m.wikipedia.org/wiki/Real_projective_plane
https://alexanderlim.io/
https://restyled.io/
http://wiki.c2.com/?GreenspunsTenthRuleOfProgramming
https://www.youtube.com/watch?v=OyfBQmvr2Hc&feature=youtu.be&app=desktop
https://www.youtube.com/watch?v=I5UjfaDRFq0&app=desktop
https://www.youtube.com/watch?v=WBWRkUuyuE0&app=desktop
http://shell.cs.pomona.edu/shtepper
http://www.ccs.neu.edu/home/hlnguyen/cs7805/spring20/index.html
https://arxiv.org/abs/1605.06640
https://www.youtube.com/watch?v=jG7dSXcfVqE&app=desktop
https://www.freecodecamp.org/news/free-courses-top-cs-universities/
https://www.goodreads.com/review/list/22328243-alex?shelf=currently-reading
https://mondaynote.com/old-square-discovers-psychedelic-valley-e38d1ef5bc0f
https://blog.metaobject.com/2020/04/maybe-visual-programming-is-answer.html?m=1
https://towardsdatascience.com/the-unreasonable-ineffectiveness-of-deep-learning-on-tabular-data-fd784ea29c33
https://nitros12.github.io/writing-a-discord-library-using-polysemy/
https://nesslabs.com/science-of-curiosity
http://beza1e1.tuxen.de/lore/tubes.html
http://bling.github.io/blog/2016/01/18/why-are-you-changing-gc-cons-threshold/
https://people.kernel.org/metan/how-to-trigger-races-reliably
https://news.ycombinator.com/item?id=23098090
https://heartbeat.fritz.ai/how-lidar-detection-works-8db24556a8d9
https://news.ycombinator.com/item?id=23095190
https://pywavelets.readthedocs.io/en/latest/
https://en.m.wikipedia.org/wiki/OODA_loop
https://www.youtube.com/watch?v=yy8jQgmhbAU&app=desktop
https://www.principles.com/the-changing-world-order/#introduction
https://www.tomshardware.com/news/amd-radeon-gpu-steal-data-radio-transmission-cybersecurity
http://c9x.me/articles/gthreads/intro.html
https://markan.me/the-delight-of-development/
https://rmsol.de/2020/04/25/v4l2/
https://divinations.substack.com/p/inside-the-clubhouse
https://www.youtube.com/watch?v=Sb0-I8FkUWU&app=desktop
https://www.youtube.com/watch?v=Sb0-I8FkUWU&app=desktop
http://blog.ezyang.com/2012/03/you-could-have-invented-fractional-cascading/
https://airtable.com/shrzJxrXCaJwwJO2T/tblMZ48gq36WojgtE
https://airtable.com/shrzJxrXCaJwwJO2T/tblMZ48gq36WojgtE
https://en.m.wikipedia.org/wiki/Monster_group
http://www.delorie.com/djgpp/doc/rbinter/it/06/0.html -- windows scan codes
https://remarkable.com/store/remarkable-2?utm_source=facebook-ads-network&utm_medium=paid-social&utm_campaign=2001+-+RT+-+Introducing+reMarkable+2+-+0-7+days&utm_content=Image+-+USD&utm_term=0-7+days+US
https://cutebouncingbunnies.wordpress.com/
https://www.netmeister.org
https://www.netmeister.org/blog/industry-vs-academia.html/
https://www.netmeister.org/blog/cs-falsehoods.html
https://www.partow.net/programming/hashfunctions/idx.html
https://en.m.wikipedia.org/wiki/Conway%27s_law
http://rmculpepper.github.io/gamble/
https://www.metalevel.at/sgp/
https://weiweihuanghuang.github.io/
https://www.3blue1brown.com/about
http://janvitek.org/whoowns.html
https://www.reddit.com/r/compsci/comments/69h3vb/rank_polymorphism_for_array_languages/
https://gitlab.com/antonok/enum_dispatch#technical-details
http://karolis.koncevicius.lt/posts/ascetic_bullet_journal/
http://mikhailkhoury.com/
https://zapier.com/blog/how-to-build-chat-bot/#how
https://byorgey.wordpress.com/2020/02/23/what-would-dijkstra-do-proving-the-associativity-of-min/
https://rhelmer.org/blog/
https://www.youtube.com/watch?v=M1t0egTZY44&app=desktop
https://mitpress.mit.edu/sites/default/files/titles/content/sicm_edition_2/book.html
https://ocw.mit.edu/resources/res-18-010-a-2020-vision-of-linear-algebra-spring-2020/index.htm

* tutorials
https://alex-hhh.github.io/2020/03/a-game-of-tetris.html
https://www.youtube.com/playlist?list=PLRGI9KQ3_HP_OFRG6R-p4iFgMSK1t5BHs&app=desktop
https://grahamc.com/blog/erase-your-darlings
http://www.marktarver.com/bipolar.html
https://www.reddit.com/r/artificial/comments/gxrnhq/d_paper_explained_synthetic_petri_dish_a_novel/
https://wespiser.com/writings/wyas/home.html write you a scheme
http://www.brattlebookshop.com/ the bookstore!
https://en.m.wikipedia.org/wiki/Frank_Frazetta incredible artist, some mdg
https://sivers.org/ cool entreprenuer
https://secondbreakfast.co/patio11-s-law
http://pkotrcka.inlisp.org/
https://github.com/dbp/website/blob/master/reading.markdown notes about
things reading
https://github.com/restic/restic good backup system
https://github.com/schollz/cowyo neat, encrypted wiki!
https://tinysubversions.com/
https://jae.moe/
https://www.paritybit.ca/
https://hackaday.com/2016/05/03/volkswagen-beetle-the-most-hackable-car/ the
hackable car!


https://imgur.com/a/fQJqc
https://gerrit.googlesource.com/git-repo/+/refs/heads/master/README.md
https://mitadmissions.org/blogs/entry/the-last-all-nighter/#disqus_thread
https://mitadmissions.org/blogs/entry/techfair/
https://mitadmissions.org/blogs/entry/for-the-love-of-6470-montresor/
http://varenhor.st/2009/07/idoor-iphone-controlled-hydraulic-door/
https://people.csail.mit.edu/karger/
https://en.wikipedia.org/wiki/David_Karger
https://www.stephanboyer.com/post/17/my-electric-unicycle
https://www.stephanboyer.com/

* check out live coding with oculus and racket
[[https://www.youtube.com/watch?v=ydyztGZnbNs&app=desktop][carmack live]]
[[https://merveilles.town/@rek][figure out what this is]]

[[https://news.ycombinator.com/item?id=23211184][learning strategy]]
[[https://www.youtube.com/watch?v=kEB11PQ9Eo8&app=desktop][non euc engine]]
[[https://www.kernel.org/doc/html/latest/driver-api/fpga/index.html][linux fpga subsystem]]
[[https://www.devontechnologies.com/apps/devonagent][research assistant search]]
[[https://www.listennotes.com/blog/why-podcasts-are-my-new-wikipedia-the-perfect-41/][learning from podcasts!!]]
[[https://news.ycombinator.com/item?id=23180572][p2p filesystem]]
[[https://news.ycombinator.com/item?id=23191493][modern web]]
[[https://observablehq.com/@jakechvatal][observable:what is this?]]
[[https://digitalmars.com/articles/b90.html][on writing a pl]]
[[https://www.realworldtech.com/][real world tech]]
[[https://thume.ca/resume/][i like layout of resume and pers proj]]
[[https://github.com/eggcaker/jekyll-org/blob/master/README.org][jekyll org]]
[[http://www.brendangregg.com/][coolguy]]
[[https://marian42.itch.io/wfc][proced gen for linux]]
[[https://github.com/kylesferrazza/ansible][what is ansible]]

[[https://wiki.archlinux.org/index.php/Realtime_kernel_patchset][realtime kernel patch for 0 latency]]
[[https://cr.openjdk.java.net/~rpressler/loom/loom/sol1_part1.html][loom]]:loom
is all about doing threads right!
[[https://github.com/rmccullagh/letsbuildacompiler][lets build a compiler book]]
[[https://github.com/itsrainingmani/gitexplore][check this out!]]
[[https://utcc.utoronto.ca/~cks/space/blog/web/HTTPSNoOldServers][good blog]]
[[https://news.ycombinator.com/item?id=23174421][crypto msging]]
[[https://en.wikipedia.org/wiki/List_of_cognitive_biases][for ui design]]
[[https://sites.google.com/site/steveyegge2/blog-rants][steve on amazon]]
[[https://synthese.wordpress.com/2010/08/21/prologs-death/][death of prolog]]
[[http://www.brendangregg.com/blog/2019-12-02/bpf-a-new-type-of-software.html][bpf:packet filter and kernel execution engine. what]]
[[https://blog.mainframe.dev/?m=1][this man rly do be making a mainframe tho]]
[[https://urbit.org/understanding-urbit/urbit-os/][urbitOS!!]]
[[https://ipj.dreamhosters.com/][internet protocol journal]]
[[https://dlang.org/blog/2020/05/14/lomutos-comeback/][dlang adn algo]]
[[https://www.hillelwayne.com/post/alloydocs/][alloy: the neat formal method]]
[[http://alloytools.org/][alloy - os lang and analyzer for software modeling]]
[[https://www.hillelwayne.com/post/influential-dead-languages/][on influential dead languages]]

configure mpd !
mpv video player or somethign
tox client for secure messaging?
qutebrowser will have to wait
[[https://rclone.org/drive/#making-your-own-client-id][rclone or smth]]

* cool topics to study
[[http://matt.might.net/articles/what-cs-majors-should-know/][what every cs major should know]]
[[https://thebreadbook.org/][the bread book :: a free society for everyone!]]
[[http://www.ccs.neu.edu/home/pete/courses/Computer-Aided-Reasoning/2018-Fall/][computer aided reasoning: cool topic]]
[[https://www.cs.cornell.edu/people/egs/beehive/codons.php][cocodns: new name service to replace dns for the internet!]]

[[https://verifcomp.dbp.io/][verifcomp]]
[[https://en.wikipedia.org/wiki/The_Dragon_Prince][made by the avatar ppl]]
[[https://en.wikipedia.org/wiki/Public_Opinion_(book)][public opinion]]
[[https://github.com/rickellis/ArchMatic][arch setup scripts]]
[[https://quasarbright.github.io/MachineLearning/README][gan work]]
[[https://www.everything2.com/index.pl?node_id=892542][the polyphasic sleep cycle]]

* Working Effectively
[[https://www.stevestreeting.com/2010/09/04/work-2-0/][article]]
- Problem: staying 'in the zone' is just not healthy or effective for a
  programmer! However, long periods of concentration are vital for a
  programmer to better understand their code and succeed. This crazy
  dedication helps develop unhealthy habits and can prevent you from
  properly focusing.

- Concentration periods are the most important part of programming. Losing
  concentration means losing all context, and losing all context means that
  you'll spend lots of time reorienting yourself and entering a stronger
  period of focus.

- It's difficult to adjust, and this leads to substantially decreased
  productivity.

To improve:
1. Embrace interruptions. Learn to accept interruptions and avoid giving up
through them.
2. Maintain context outside of your head at all times. Always explicitly
comment and track what you're doing, teh decisions you're making. etc.
Externalizing thoughts can help you clarify them! Every so often, make sure
to record these (the author does this at 30 minute intervals).
3. Ignore tangental issues. Focus on the singular current task and don't
worry about things that could get you sidetracked! Write those down with a
ticket system that's fast, lightweight and agnostic to the amount of detail
put into these thoughts. The most important thing to do is to put this idea
away until it can be summoned in a future context.
4. Always know of the one thing you will do next.
5. Prioritize negatively :: assume baseline that you will not do any of the
tasks, then assess the negative outcomes of not doing each one. Perform the
task that will have the most negative outcome first.
6. Recognize the benefits of breaks. Breaks have great benefits, encourage
better health, and can offer a new context from which the problem can be
tackled!

* around the internet
[[https://wiki.xxiivv.com/site/devine_lu_linvega.html][the generalist.]]
[[https://wiki.xxiivv.com/site/about.html][digital playground]]
[[https://www.jjude.com/sdl/][learning to learn]]
[[https://medium.com/endless-filament/make-your-filament-at-home-for-cheap-6c908bb09922][make 3d printing filament]]
[[https://www.flipmine.com/][flipping!]]
[[https://www.35mmc.com/25/06/2017/hasselblad-xpan-ii-review/][3d print xpan]]
[[https://supercollider.github.io/][algorithmic composition through code]]
[[https://lemire.me/blog/2020/05/22/programming-inside-a-container/][programming inside a container]]
[[generalproblem.net][noah zentzis - i talked to him!]]
[[https://parachute.live/blog/forensic-investigation-the-shocking-state-of-privacy-in-safety-apps][shocking state of privacy in safety apps]]
[[https://en.m.wikipedia.org/wiki/Masters_of_Doom][on ID software]]
[[https://feltrac.co/control/2020/01/12/simple-control-systems.html][machine control systems]]
[[https://www.35mmc.com/24/12/2018/panomicron-oxygen-review/#Discovering_and_buying_my_Panomicron_Oxygen][3d
printing a camera]]
[[https://billdemirkapi.me/How-to-use-Trend-Micro-Rootkit-Remover-to-Install-a-Rootkit/][rootkit with rootkit remover!!]]
[[https://www.nytimes.com/2019/12/05/opinion/digital-technology-brain.html][powerful article about avoiding distraction]]
[[http://pinboard.in/][pinboard:: bookmarking!]]
[[https://fabiensanglard.net/gebbwolf3d/][game engine black book]]
[[https://news.ycombinator.com/item?id=23222424][impostor syndrome in programming]]
[[https://dragonquest64.blogspot.com/2020/05/python-generated-sequence-diagrams.html?m=1][python sequence diagrams]]
[[https://news.ycombinator.com/item?id=23281542][tem commandments of c programmers]]
[[https://news.ycombinator.com/item?id=23282278][brand yourself as a freelancer]]
[[https://news.ycombinator.com/item?id=23281568][writing a programming book]]
[[https://vimeo.com/36579366][inventing on principle]]
[[https://google.github.io/eng-practices/review/reviewer/][code review standards]]
[[https://github.com/deezer/spleeter][pioneering source separation ]]
[[https://arxiv.org/abs/2005.09535][open source attacks]]
[[https://arxiv.org/abs/2005.09535][dark depths of youtube]]
[[https://pinshape.com/items/7919-3d-printed-35mm-film-on-120-spool][film on spool]]
[[https://www.35mmc.com/24/12/2018/panomicron-oxygen-review/#Discovering_and_buying_my_Panomicron_Oxygen][3d printed camera]]
[[https://news.ycombinator.com/item?id=20124018][truths of jr dev]]
[[https://news.ycombinator.com/item?id=20323246][choose boring tech.]]
[[https://wiki.js.org/][open source wiki]]
[[http://www.simonweckert.com/googlemapshacks.html][google map hack performance art]]
[[https://news.ycombinator.com/item?id=23170881][side proj!]]
[[https://news.ycombinator.com/item?id=23172959][new proj!]]
[[https://sites.google.com/site/steveyegge2/blog-rants][amazrant]]
[[https://gist.github.com/bricker/cb811b3b86d767124801][amazrant2]]
[[https://synthese.wordpress.com/2010/08/21/prologs-death/][rip prolog]]
[[https://jozefg.github.io/][chaddd]]
[[https://machinelearning.apple.com/][ml at apple]]
[[https://rauchg.com/][blog]]
[[http://seenaburns.com/][blog]]
[[https://100r.co/site/home.html][the best]]
[[https://joearms.github.io/oldindex.html][functional web]]
[[https://jxnblk.com/blog/][chad]]
[[http://mrmrs.cc/writing/][great site]]
[[https://github.com/frankmcsherry/blog][the blog.]]
[[https://github.com/learn-anything/blogs#readme][wowowewow]]
[[https://lobste.rs/s/hrxdoq/what_s_url_your_technical_blog][techblog]]
[[https://bradfrost.com/blog/post/write-on-your-own-website/][write on your own website]]
[[https://blog.andrewbran.ch/overengineering-a-blog/][overengineering]]
[[https://github.com/mathieudutour/medium-to-own-blog][dont use medium]]
[[https://git.sr.ht/~sircmpwn/openring][webbing neat]]
[[http://matt.might.net/articles/how-to-blog-as-an-academic/][matt adv]]
[[https://joelhooks.com/digital-garden][whoat didigtal garden]]
[[https://news.ycombinator.com/item?id=21928170][niceh blogs]]
[[https://www.fast.ai/2020/01/16/fast_template/][make blog.]]
[[https://github.com/jkup/awesome-personal-blogs#readme][tech blogs]]
[[https://news.ycombinator.com/item?id=22273224][dev bugs]]
[[https://github.com/kilimchoi/engineering-blogs#readme][ng blog]]
[[https://danluu.com/corp-eng-blogs/][writing good engineering blog]]
[[https://news.ycombinator.com/item?id=22800136][findinh your blog]]
[[https://github.com/hankchizljaw/hylia][blog starter kit]]
[[https://lobste.rs/s/5ysabq/share_your_blog][share ur blog]]
[[https://jonkuperman.com/best-blog-designs-2020/][blog]]
[[https://sanderknape.com/2020/04/why-great-write-blog-posts/][why you should blog]]
[[https://www.35mmc.com/24/12/2018/panomicron-oxygen-review/#Discovering_and_buying_my_Panomicron_Oxygen][secret spots]]
[[https://twitter.com/monicalent/status/1258750975021588483][learning from blogging]]
[[https://ferrucc.io/posts/starting-a-blog/][why do i blog?]]
[[https://news.ycombinator.com/item?id=23095273][comments on static site]]
[[https://news.ycombinator.com/item?id=23206259][hard tech]]
[[https://news.ycombinator.com/item?id=23205588][blog hack to bring back]]
[[https://vanschneider.com/a-love-letter-to-personal-websites][love letter to the internet]]
[[https://gist.github.com/nikitavoloboev/63b5d2418122fcd6949d854dc5080689][good reader]]
[[https://news.ycombinator.com/item?id=21332072][successful online businesses]]
[[https://news.ycombinator.com/item?id=21332072][abandoned paper mill near me]]
[[https://news.ycombinator.com/item?id=23250379][openai langauge model used for code generation]]
[[https://news.ycombinator.com/item?id=23246908][why i hate rust]]
[[https://news.ycombinator.com/item?id=23243330][why giving money good]]
[[https://apps.ankiweb.net/][ANKIII]]
** music
[[https://news.ycombinator.com/item?id=23232268][how distortion works in music]]
[[http://labs.phaser.io/][phaser games]]
[[https://arcade.makecode.com/][games in the browser!]]
[[https://teenage.engineering/][v cool]]
** thinking
[[https://github.com/deezer/spleeter][the most valuable thing you can learn in an hour.]]
[[https://capitalandgrowth.org/answers/Article/3217401/Become-Abnormal][become abnormal.]]
[[https://fabiensanglard.net/gebbwolf3d/][mental models for intelligent decisions]]
[[https://sloanreview.mit.edu/article/learning-for-a-living/][learn for a living.]]
[[https://news.ycombinator.com/item?id=22105229][to survive]]
[[https://news.ycombinator.com/item?id=23262763][a programmer's perspective.]]
** hustling people
[[https://www.linkedin.com/in/gefenskolnick/][chad]]
[[https://en.m.wikipedia.org/wiki/Alexis_Ohanian][reddit guy and vc]]
[[https://www.cs.princeton.edu/~ckorkut/][cs guy working on certicoq]]
[[https://joon.be/][wild independent game designer]]
[[https://dbp.io/essays/2012-10-24-programming-literature.html][programming as literature.]]
** snowden
[[https://www.theatlantic.com/magazine/archive/2020/06/edward-snowden-operation-firstfruits/610573/][paranoia]]
[[https://news.ycombinator.com/item?id=23221517][the surveillance story]]
* nix
[[https://cachix.org/][cache nix packages]]
[[https://engineering.shopify.com/blogs/engineering/what-is-nix][what is nix?]]
[[https://news.ycombinator.com/item?id=23251754][what is nix article]]
* pl
[[http://www.zifyoip.com/wysiscript/sigbovik.html][programming with syntax highlighting]]
* webdev
[[https://news.ycombinator.com/item?id=17910069][which functional language for web development??]]
[[https://news.ycombinator.com/item?id=23231361][usefulness of declarative programming]]
[[https://github.com/Rolstenhouse/unofficial-apis][unofficial apis]]
[[https://tinyprojects.dev/posts/tiny_websites_are_great][build tiny websites.]]
[[https://news.ycombinator.com/item?id=23283675][elixir]]
[[https://hashrocket.com/blog/posts/elm-by-example-soup-to-nuts-part-1][elm by example]]
[[https://work.margo.com/posts/why-elixir/][why elixir]]
[[https://newcss.net/][use only html.]]
[[https://codepen.io/lynnandtonic/pen/NWGLMMO][3d cube]]
[[https://lemire.me/blog/2020/05/22/programming-inside-a-container/][one word domains]]
[[https://blog.noredink.com/post/126978281075/walkthrough-introducing-elm-to-a-js-web-app][elm with js web app]]
[[https://mmhaskell.com/blog/2018/10/29/purescript-iii-web-pages-with-react][making wbepage with purescript and react]]
[[https://mmhaskell.com/blog/2018/11/19/elm-series-purescript-coming-up][on elm and purescript]]
[[https://latex.now.sh/][latex in css!]]
[[https://every-layout.dev/][relearn css layout]]
[[https://medium.com/serverless-transformation/what-a-typical-100-serverless-architecture-looks-like-in-aws-40f252cd0ecb][serverless architecture]]
[[https://tachyons.io/][responsive css framework]]
[[https://www.netlify.com/blog/2020/05/08/improve-your-seo-and-social-sharing-cards-with-next.js/?utm_source=twitter&utm_medium=next-seo-cs&utm_campaign=devex][improving seo]]
[[https://defn.io/2019/04/07/web-continuations/][continuations for web dev]]
[[https://blog.timescale.com/blog/multi-node-petabyte-scale-time-series-database-postgresql-free-tsdb/][free time series db on postgres - relevant for work?]]
** hugo blog inspo
[[https://themes.gohugo.io/origin-hugo-theme/][hugo]]
[[https://themes.gohugo.io/amperage/][seo opt]]
[[https://themes.gohugo.io/hugo-theme-terminal/][terminal theme]]
[[https://themes.gohugo.io/][all themes]]
[[https://themes.gohugo.io/][origin theme]]
[[https://themes.gohugo.io/ezhil/][personal portfolio theme]]
[[https://themes.gohugo.io/archie/][minimal ui]]
[[https://themes.gohugo.io/hugo-book/][plain doc book]]
[[https://themes.gohugo.io/erblog/][simple blog]]
[[https://themes.gohugo.io/archie/][md ui]]
[[https://themes.gohugo.io/hugo.386/][bootstra??]]
[[https://themes.gohugo.io/erblog/][erblog theme]]
[[https://themes.gohugo.io/hugo-changelog-theme/][changelog]]
[[https://themes.gohugo.io/academic/][academic]]
[[https://themes.gohugo.io/hugo-theme-hello-friend-ng/][simple theme]]
[[https://portal.mozz.us/gemini/gemini.circumlunar.space/software/][gemini software!!]]
** fun css
[[https://codepen.io/chrisgannon/pen/oNjqpLy][slider]]
[[https://codepen.io/chrisgannon/pen/oNjqpLy][inherit!]]
[[https://codepen.io/chrisgannon/pen/oNjqpLy][wow animation!]]
[[https://github.com/scallywag/org-board/blob/master/README][emacs archive system]]
[[https://github.com/lionheart/pinboard.py][pinboard]]
* small, sharp tools.
[[https://brandur.org/small-sharp-tools][article]]
Rule of modularity: write simple parts connected by clean interfaces.
Rule of composition: design programs to be connected to other programs.
Rule of Parsimony: write a big program only when it is clear by
demonstration that nothing else will do.
Build as simple as possible, but no simple. Do not allow the composition of
these parts to assemble a tightly integrated system.

* abandoned places
[[https://portal.mozz.us/gemini/gemini.circumlunar.space/software/][northwest]]
[[https://portal.mozz.us/gemini/gemini.circumlunar.space/software/][secret locs]]
[[https://arxiv.org/abs/1808.02923][math]]
[[https://github.com/michaelbjames][probprog]]
[[https://news.ycombinator.com/item?id=23211184][learning!]]
[[https://www.numworks.com/simulator/][coo lcalculator]]
[[http://whydontyoulove.me/][designer and dev in teh valley]]
[[https://blogs.nvidia.com/blog/2020/05/22/gamegan-research-pacman-anniversary/][gaemgan]]
[[https://www.iep.utm.edu/epis-per/][percentpion]]
[[https://people.cs.umass.edu/~arjun/main/home/][guha]]
[[https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/README.md][chad]]
[[https://medium.com/@victormours/better-linting-in-vim-with-ale-1e4b1d5789af][linting in ale]]
[[https://taskwarrior.org/][taskwarrior]]
[[http://jelv.is/][neat blog]]
[[https://www.aquicarattino.com/blog/how-write-programming-book/][why to write abt programming]]
[[https://gist.github.com/cellularmitosis/1f55f9679f064bcff02905acb44ca510#tutorials][gui programming]]
[[https://news.ycombinator.com/item?id=23245724][bug bad]]
[[https://news.ycombinator.com/item?id=23252448][visual programming]]
[[https://guzey.com/science/sleep/14-day-sleep-deprivation-self-experiment/][sleep on cognition]]
[[https://www.ramblingcode.dev/posts/lovely_week_with_elixir/}[elixir]]
[[https://en.m.wikipedia.org/wiki/The_Electric_Kool-Aid_Acid_Test][cool book]]
[[https://news.ycombinator.com/item?id=23246170][port scanning]]
[[https://news.ycombinator.com/item?id=20883169][blind dev]]
[[https://www.cambridge.org/core/journals/journal-of-child-language/article/early-vocabulary-development-in-danish-and-other-languages-a-cdibased-comparison/D12A283664A8BA4A695D0DDF3378555A][early vocab]]
[[https://www.tbray.org/ongoing/When/202x/2020/04/29/Leaving-Amazon][amazon bad]]
[[https://overreacted.io/goodbye-clean-code/][goodbye clean code]]
[[https://boingboing.net/2019/07/03/nobus-r-us.html]['ban hack]]
[[https://jeffhuang.com/productivity_text_file/][prouctivitty]]
[[https://jeffhuang.com/designed_to_last/][make it last]]
[[https://monicalent.com/blog/2019/06/03/absolute-truths-unlearned-as-junior-developer/][jr dev]]
[[https://pomb.us/build-your-own-react/][build react from scratch]]
[[https://blog.samaltman.com/][aahh]]
[[https://news.ycombinator.com/item?id=23271624][pacman gan]]
[[https://news.ycombinator.com/item?id=23276456][cool tech]]
[[https://copetti.org/projects/consoles/nintendo-64/][nintendo arch]]
[[https://deezer.io/releasing-spleeter-deezer-r-d-source-separation-engine-2b88985e797e][deezer]]
[[https://marc.info/?l=openbsd-tech&m=158965652915344&w=2][what is this lol]]
[[https://en.m.wikipedia.org/wiki/John_Carmack][chad]]
[[https://deezer.io/][tech blog]]
[[https://news.ycombinator.com/item?id=20916749][ask company during interview]]
[[https://news.ycombinator.com/item?id=22124489][managing emotions]]
[[https://en.wikipedia.org/wiki/Webring][webring]]

[[https://audiomass.co/][sonic smth]]
[[https://news.ycombinator.com/item?id=23340031][reading online content]]
[[https://ertdfgcvb.xyz/][wow]]
[[https://webring.xxiivv.com/#rss][rss!]]
[[https://github.com/LeD3F/dots][good dotfiles for a lot of wms]]
[[https://roamresearch.com/#/app/selentelechia/page/cdp0rUo9S][hell yea]]
[[http://akkartik.name/about][on building mechanisms for good code]]
[[https://controls.ee/links/][beats and sound]]

[[https://www.mattblaze.org/blog/p25][johnny can't encrypt!]]
[[https://zulipchat.com/][chat for distributed teams]]
[[https://cancel.fm/ripcord/][desktop chat clinet]]

* good dotfiles
[[https://github.com/adi1090x/CustomArch/tree/version-2.0][custom arch iso]]
[[https://github.com/akshat46/FlyingFox][great firefox config]]
[[https://github.com/akshat46/FlyingFox][using wmutils]]
[[https://github.com/LeD3F/dots][great dotfiles; exp polybar and dunst confiugrations]]
** wm to check out !!
- 2bwm
- dwm
- frankenwm
- herbstluftwm

* emacs
[[https://github.com/sulami/dotfiles/blob/master/emacs/.emacs/README.org][great,
literate custom emacs config]] -- come back to this if/when you decide to use
emacs again!

* other links
[[https://whitequark.org/][whitequark]]
[[https://lab.whitequark.org/][whitequark blog]]
[[https://lyngvaer.no/][log:: good blog]]
[[https://www.criterion.com/][the criterion collection: classic movies]]
[[http://lea.verou.me/2020/05/todays-javascript-from-an-outsiders-perspective/][today's js]]
make sure to check out qutebrowser. it does not seem quite there yet, but
navigating via only keyboard seems very good.
[[https://ideatrash.net/2013/03/scripts-and-utilities-to-make.html][scripting for newsbeuter to make it better than google reader]]
[[https://ideatrash.net/2013/03/scripts-and-utilities-to-make.html][tui everything]]

[[https://taskwarrior.org/docs/taskserver/setup.html][setting up taskwarrior server]]

idea! vim plugin to reduce plugin usage. removes random lines from vimrc on
load, and continues to remove them every time vim starts up until you
manually override

* becoming an influencer
put the camera down
pick something you want to learn about
spend the next 10 years mastering your craft
pick the camera back up
tell people what you have learned
kill it

https://www.karenx.com/blog/how-to-become-a-designer-without-going-to-design-school/

* 'general inspiration'

#+TITLE: General Inspiration

Assorted inspiration for various topics.
This should all be better sorted when it is reviewed.

* ETC

[[https://ertdfgcvb.xyz/][inspirational site]]
[[https://constraint.systems/][creative image constraints]]

* web hostility

[[https://neustadt.fr/essays/against-a-user-hostile-web/][article]]
"Facebook is at odds with the open web that I love and defend..."
Netscape Navigator (small internet) -> big internet!
The modern web is being destroyed -- personalized content, growth hacking,
social media activation, CMS and user experience. These websites are not
built to appreciate the visitor -- they are constructed to make the user a
customer. Cookies bad! Small blogging good!

[[https://builtwithnix.org/][nix!]]
[[https://shouldiblockads.com/#ha][what is wrong with ads?]]
[[https://revealjs.com/#/][create stunning presentations on the web]]

[[https://svelte.dev/][autocreate websites. what.]]

[[https://amorphous.itch.io/][strange narrative games, good mono font]]
[[https://scuttlebutt.nz][scuttlebutt : the decentralized, social web.
localized but distribued.]]

* setting up weechat as frontend for everything

[[https://github.com/thefinn93/signal-weechat/blob/master/README.md][signal weechat]]
[[https://github.com/wee-slack/wee-slack][slack weechat]]

[[https://cineshader.com/][cellular noise]]

[[https://www.olivevideoeditor.org/][free video edition]]
also look into editing with blender

code as a creative medium :: MIT book

tildegit :: git for the tildeverse!

[[https://dev.upvote.blog/][seems like an organic place to spend time on the internet]]

* blogging for free

[[https://bearblog.dev/][bear blog]]
[[https://pluma.cloud/][pluma free blog]]
[[https://write.as/][focused writing place]]
[[http://txti.es/][convenient, fast web pages]]

[[https://telegra.ph/why-am-i-here-05-29][express yourself quickly]]
[[https://txt.fyi/+/22b9f246/][raw expression]]
[[https://txt.fyi/+/6ce898cf/][the cask ]]

[[https://txt.fyi/about/][quick publishing on the web.]]
[[https://txt.fyi/+/57688c94]][real shit]]
[[/#/][another one of these]]
[[http://ix.io/][kinda fire. more minimal and more obscure]]
[[https://commentpara.de/][anon we comments on any site]]
[[https://rwtxt.com/public][reading and text editor]]
[[https://write.as/][focused writing.]]
[[https://discourse.nixos.org/t/is-there-much-difference-between-using-nix-shell-and-docker-for-local-development/807][nix vs docker]]
[[https://blog.container-solutions.com/step-towards-future-configuration-infrastructure-management-nix][configuring infra in nix]]

[[https://gopher.tildeverse.org/tildeverse.org][tilde. in gopher.]]
[[https://pleroma.tilde.zone/main/all][federated social media is the future.]]
[[https://en.m.wikipedia.org/wiki/Duff%27s_device][compiler neat thing]]
[[https://dotdotdash.io/][collective.]]
[[https://moonscript.org/][moonscript: better lua programming!]]

* camera

buy fuji x t 2 !!
[[https://www.bestsevenreviews.com/fujifilm-xt2-review/][fuji best camers]]
[[https://online-go.com/][an excellent client for playing go]]

* Do I need to go to university?

[[http://colah.github.io/posts/2020-05-University/][article]]
it's hard to know who should take nontraditional paths, and many people are
looking for validation not to do so. realistically, this is the best option
for most people, both socially and academically.
Some questions:
- Do I have things that I deeply want to spend a year of my life exploring
  and working on?
- Do I have a way to support myself that leaves me time and energy to grow?
- Can I really work self-directed for months at a time? Do I have examples of
  me working hard on a personal project or learning without external
  structure?
- Do I have or can I learn the skills I need to work on this project
  independently?
- Do I have or can I learn the skills I need to work on this project
independently?
- Do I have sources of community, peer support or mentorship for what I want
  to do?

Those who leave university may be disparaging their efforts to make friends.
However, the ability to focus independently for an extended period of time
before heading to college is ideal for many people to flourish.

* Tools for Better Thinking

[[https://news.ycombinator.com/item?id=23339830][thread]]
The most underrated problem solving tool is to type out and explain your
thought process.
Start writing down questions to ask others; as you explain what you have
tried, you will begin to realize that there are more things left to try --
some of which being potential solutions.

Type your question into StackOverflow to submit; you'll be fearful of asking
the question.

Rank factors; always express factors as positive attributes. After generating
the table, the longest continuous line of check marks for each factor
determines the choice (though this can be gamed...)

State charts: easy to reason about state changes without the explosion of
state machines. These are hierarchical state machines, in a sense.

The Inversion Methods: The solution to many hard problems can be clarified by
re-expressing them in inverse form.

Crossline: structure your thoughts as you type and make cross-references.

[[https://fs.blog/mental-models/][mental models for making intelligent decisions]]

[[https://medium.com/disruptive-design/search?q=tools%20for%20systems%20thinkers][tools for systems thinkers]]
[[https://news.ycombinator.com/item?id=22747409][state machines for complex systmes]]
[[https://www.wiley.com/en-us/TRIZ+for+Engineers%3A+Enabling+Inventive+Problem+Solving-p-9780470741887][enabling inventive problem solving]]
[[https://en.m.wikipedia.org/wiki/TRIZ][analyzing and forecasting tool]]

[[https://untools.co/][tools for better thinking .]]

[[https://www.youtube.com/watch?v=de8Ak0nY1hA&app=desktop][improving compiler correctness using formal methods]]

* today's js

https://lea.verou.me/2020/05/todays-javascript-from-an-outsiders-perspective/
article
THe modern web is painful. Interfacing with js and node results in conflitts
between es and js versions, node incompatibilities, differnet import syntax
in different circumstances, etc. it's painful. How do you import with node?
without node? <script> tag or not to script? Where did the node modules go?
This is a good rant of questions and things to feature on the wbesite

* record of a living being

https://cinemasojourns.com/2020/03/29/akira-kurosawas-record-of-a-living-being/
source
watch the film :: one of the first to directly address the fear of nuclear
holocaust and the implications of the atom bomb.  an introspective, cerebral
work regarding japan after the bomb and moving forward, away from fallout.
inspired by conversations with otuers regarding what may -- or may not be --
in store for us tomorrow, if tomorrow is in store at all.

* anxiety in product development

https://andreschweighofer.com/agile/anxiety-in-product-development/
anxiety can emerge easily from stress, resulting in anger, frustration and
other unhealthy forms of exerting such stress. this impacts other people,
organizations and processes as well.
we have fear driven development : a concrete idea encouraging us to avoid
certain practices depending upon the specific approach

play to win, don't play not to lose; developing a unique selling proposition
means that you are no longer fighting with others, but rather striving to
come out ahead

awareness of such anxiety is the first step to take. with this awareness
comes conscious decision making, and with such decisions come wiser product
crafting and, in the end, better, more creative work

* bootstrappable builds

http://bootstrappable.org/
http://bootstrappable.org/projects.html good projects to work on
this is a general build philosophy addressing the chicken and egg problem --
to trust platforms, we must see how each part is produced from source, but we
do not have access to the source of compiled code when we run it against the
language they are compiling!
http://bootstrappable.org/ on trusting trust. ken thompson talk linked at the
bottom is great, as are the other articles. great compilers literature

* general ideas
** 50 ideas that changed my life

https://www.perell.com/blog/50-ideas-that-changed-my-life
inversion :: avoiding stupidity is easier and better than being brilliant
doublespeak :: saying the opposite of what one means
theory of constraints :: focus on the bottleneck, the weakest point of the
system, always.
preference falsification :: lying to conform to the most socially acceptable
opinion at the time
mimetic teory of desire: rather than having our own desires, we imitate the
desires of others and pursue their ideas
mimetic theory of conflict :: similar = fight

left off on 10!

* cool cs

https://github.com/browserdotsys/vecchio ray tracing in one weekend :: looks
fun to do
https://blog.benwiener.com/programming/2019/04/29/reinventing-the-wheel.html
discovering optimal rolling shape in pytorch!
https://zserge.com/posts/jvm/ how to write a toy jvm -- try this and put it
on github! fun small thing to mess around with. add more to it, add new
things, mess aroundand have fun!
https://www.cs.cmu.edu/~janh/courses/411/16/ compiler design course at cmu.
supposedly good material
https://gist.github.com/cellularmitosis/1f55f9679f064bcff02905acb44ca510#simple-compiler-codebases-to-study
crazy compilers good stuff

 http://gokcehan.github.io/ has some idea what he is doing; wrote lf, which
 seems to be a better ranger
https://bellard.org/otcc/
https://bellard.org/tcc/ fun

http://web.eecs.utk.edu/~azh/blog/teenytinycompiler1.html cool project for a
tiny compiler in python!

* idea

https://thetechonomics.com/2020/06/03/how-we-automated-99-of-our-newsletter-business/
automated aggregation and newsletter generation for headlines, article links,
etc

[[https://derivationmap.net/}[deriation graph of all of math physics!]]

* books

https://en.m.wikipedia.org/wiki/Words_of_Radiance
https://www.amazon.com/Dark-Matter-Novel-Blake-Crouch/dp/1101904240
https://en.m.wikipedia.org/wiki/Range:_Why_Generalists_Triumph_in_a_Specialized_World
https://m.imdb.com/title/tt1737747/
https://www.powells.com/book/little-typer-9780262536431
https://blog.rogs.me/2020/05/de-google-my-blog-how-to-blog-in-2020-without-google/
de google the blog

https://en.m.wikipedia.org/wiki/Literate_programming -- practice literate
programming in daily life.

https://moviebarcode.tumblr.com/ cool looks

[[http://lisperator.net/blog/queen-chess-fast-lisp/][queens]]
[[http://lisperator.net/blog/a-little-javascript-problem/][js problem]]
[[http://lisperator.net/blog/pull-request-based-development-sucks/][pr based dev]]
[[http://lisperator.net/blog/gazing-at-the-numbers-the-collatz-sequence/][collatz seq]]
[[http://lisperator.net/blog/the-left-pad-case/][leftpad]]
[[http://lisperator.net/blog/minesweeper-and-interviewing/][minesweeper and interviewing]]
https://www.datprotocol.com/ hypermedia protocol!
