#+TITLE: things to learn
* signal processing/compression
https://github.com/PyWavelets/pywt

* people
https://en.m.wikipedia.org/wiki/L%C3%A1szl%C3%B3_Polg%C3%A1r
http://www1.ece.neu.edu/~eyeh/
http://www.ccs.neu.edu/home/hlnguyen/
http://www.ccs.neu.edu/home/rancohen/
https://christine.website/contact
https://jswrenn.comhttp://www.ccs.neu.edu/home/hlnguyen/
http://www.ccs.neu.edu/home/rancohen/
https://christine.website/contact
https://jswrenn.com//
http://people.cs.uchicago.edu/~jhr/
https://www.ccs.neu.edu/home/ryanc/
http://users.umiacs.umd.edu/~hal/cv.html
https://users.cs.northwestern.edu/~jesse/
http://worrydream.com/#!/Bio -- this guy has done a lot and has a lot of
interests
http://cs.brown.edu/research/plt/ -- self explanatory
https://lexi-lambda.github.io/resume.html -- alexis king -- brilliant racket and
haskell programmer
https://www.reddit.com/r/haskell/comments/fyyia7/which_major_code_bases_should_i_study_to_better/
http://blog.ezyang.com/about/ -- edward yang, a stanford phd student who works
with ml and functional languages
https://ryanjung.dev/ -- in fundies, has great personal website -- work on mine!
http://justinpombrio.net/ -- pl guy, phd student from brown
https://www.antonok.com/ -- good work in rust, have talked to him, cool guy
https://shreyaskapur.com/ -- mit undergrad, really on top of it
https://nicholas-miklaucic.github.io/ -- northeastern guy, great blog
https://guillaumelegoy.github.io/ -- Boring Data Science blog with lots of cool
trinkets
http://seinfeld.co/library/
http://herpolhode.com/rob/ -- archer, unix guy who writes about things!
https://web.stanford.edu/~ouster/cgi-bin/home.php -- behind raft; cool dude http://aviral.io/ -- prl phd student who does a lot of cool work
https://en.wikipedia.org/wiki/Greg_Marinovich -- photographer who has worked at
a lot of different places, very well known, he works in BU
http://willghatch.net/blog/ -- good writing on a bunch of people doing things
with operating systems
https://jborichevskiy.com/ideas/ -- this person has a lot of cool ideas r work
https://www-cs-faculty.stanford.edu/~knuth/retd.html -- of course, knuth
http://lav.io/ lots of gool 3d and visual art work
http://madebyevan.com/ -- 3d stuff !
https://en.wikipedia.org/wiki/Daniel_S._Weld
http://mumble.net/~jar/ -- this guy works on cool open source things
https://miles.land/#portfolio -- very cool and entreprenurial !
https://winston.me/ -- winston seems cool
https://www.karenx.com/ -- high profile filmmaker and designer
https://www.theguardian.com/culture/2020/apr/29/nats-what-i-reckon-the-sweary-ranty-youtuber-whos-become-an-isolation-cooking-sensation
-- good cook!!
http://homes.sice.indiana.edu/samth/ -- sam tobin something, student of matthias
[[http://number-none.com/blow/][jon blow, game dev and compiler guy]]
** matthias
https://felleisen.org/matthias/Thoughts/Referential_Transparency.html
https://felleisen.org/matthias/Thoughts/Why_How_do_I_get_a_PhD.html -- on grad
school
https://link.springer.com/article/10.1007/BF00277387
https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-20.html#%_idx_2990
sicp, somehow
https://www.cis.upenn.edu/~halleyy/ phd student working on generative models
https://mitpress.mit.edu/sites/default/files/sicp/index.html
http://ccs.neu.edu/home/types/extras/extras.html -- been greenman, cool guy!
https://felleisen.org/matthias/4620-s18/index.html
https://felleisen.org/matthias/7480-s17/lectures.html -- talks from a lot of PL
people
** mike shah
http://www.mshah.io/pizza/artofpizza.html pizza
http://www.mshah.io/conf/18/cppcon/index.html debugging with the gui
cpp, llvm and all that.
https://docs.google.com/presentation/d/1jps3KpD2zbsBwwApDnsU9LsgpXX-8ttmwtwEKoNKHt8/mobilepresent#slide=id.g358c9a0181_0_7
https://docs.google.com/presentation/d/1gkVFtXpXcySlu7qiPaaACIMAXBT0Cfn_p_yBn1NFrOs/mobilepresent#slide=id.g17dd02dfa8_4_16

** olin shivers
http://www.ccs.neu.edu/home/shivers/autoweapons.html
his thesis is incredible
https://news.ycombinator.com/item?id=2382531
stuff about olin
comedy:
http://www.ccs.neu.edu/home/shivers/autoweapons.html
https://www.wanderings.net/notebook/Main/BitterAcknowledgmentsOfOlinShivers
http://www.ccs.neu.edu/home/shivers/newstyle.html
http://www.ccs.neu.edu/home/shivers/scribblings.html
** knuth
https://www-cs-faculty.stanford.edu/~knuth/boss.html
https://www-cs-faculty.stanford.edu/~knuth/news08.html
https://www-cs-faculty.stanford.edu/~knuth/taocp.html
https://www-cs-faculty.stanford.edu/~knuth/retd.html
https://www-cs-faculty.stanford.edu/~knuth/vita.html
https://www-cs-faculty.stanford.edu/~knuth/cp.html

** sam stites : prob programming, ml
https://stites.io/ -- great writing on neural networks
** jake kinsella
peer of mine, several cool personal projects
https://github.com/TheLocust3/hierarchy -- trello clone with trees and graphs
https://github.com/TheLocust3/full-stack-vm -- virtual machine!
https://jakekinsella.com/projects/intel8080/ -- emulator for intel 8080
processor - emulation could be cool
* sus links
https://web.archive.org/web/20130507230947/http://www.heise.de/tp/artikel/2/2898/1.html
https://web.archive.org/web/20130507230947/http://www.heise.de/tp/artikel/2/2898/1.html
https://meet.jit.si/ -- free meetings and stuff
http://www.catb.org/hacker-emblem/?utm_source=Hackaday.com&utm_campaign=ec4864ced1-EMAIL_CAMPAIGN_2020_02
http://www.jsfuck.com/

** category theory
https://en.wikibooks.org/wiki/Haskell/Category_theory -- haskell and categories!
https://en.wikipedia.org/wiki/Monad_(category_theory)#Algebras_for_a_monad
https://en.wikipedia.org/wiki/Kleisli_category -- category for monads
Does every monad arise from an adjunction?
http://www.haskellforall.com/2013/02/you-could-have-invented-comonads.html
https://en.wikipedia.org/wiki/Monad_(category_theory)#Algebras_for_a_monad
https://stackoverflow.com/questions/3870088/a-monad-is-just-a-monoid-in-the-category-of-endofunctors-whats-the-problem
http://comonad.com/reader/
https://ncatlab.org/nlab/show/comonad#definition
 http://comonad.com/reader/ -- curry howard lambek currespondence guides researchers into computation. rea    ding a logic like type theory is a definitional trick as it is just reinterpretation of syntax. syntactic     categories are difficult to connect to categorical semantics

* systems
http://people.cs.pitt.edu/~jacklange/teaching/cs2510-f17/

https://github.com/NatTuck/pancake -- this looks kinda wild, figure out what
it's doing!
* physical
https://github.com/xingyif/raft
https://www.youtube.com/watch?v=hUzri2ybm_Y
** bio
neurobiology
in vivo / ex vivo
in vitro
beta tau optimization
radio tracers : technological or approval barrier? a combination of the both,
really, technology not developed for this. none o these are good enough to
definitively say they can be implemented
learn about brains and chemistry stuff!! work in lab!
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2633703/
https://www.nature.com/articles/nchem.2889
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4289634/
http://worrydream.com/#!/LearnableProgramming designing a programming system for
understanding programs
https://www.maa.org/news/interview-tony-derose  -- from computer graphics pioneer

https://catalog.princeton.edu/catalog/SCSB-8534958 -- b
https://kk.org/thetechnium/68-bits-of-unsolicited-advice/?utm_campaign=Recomendo&utm_medium=email&utm_source=Revue%20newsletter
* math
https://www.quantamagazine.org/amazing-math-bridge-extended-beyond-fermats-last-theorem-20200406/

* talks
https://www.reddit.com/r/ProgrammingLanguages/comments/fxc504/do_you_know_any_interesting_talks_about_pl/
https://www.youtube.com/watch?v=yy8jQgmhbAU&app=desktop
https://www.realtimerendering.com/raytracinggems/
https://www.benawad.com/scraping-recipe-websites/
https://www.youtube.com/watch?v=P1ww1IXRfTA&t=&app=desktop
[[https://www.hillelwayne.com/talks/software-history/?utm_source=hillelwayne&utm_medium=email][what we can learn from software history]]
[[https://www.hillelwayne.com/10x/][good programmers can be bad for industry]]
[[https://www.hillelwayne.com/hate-your-tools/][hate your tools]]
[[http://bangbangcon.com/livestream][fun, 10 min fast talks!]]
* funny
https://aphyr.com/posts/342-typing-the-technical-interview excellent article
on navigating the technical interview

https://github.com/lampepfl/dotty/issues/7598 -- on the equality operator
http://matt.might.net/articles/electric-meat/ -- his whole blog is incredible
* designing code
http://gamesfromwithin.com/data-oriented-design
https://overreacted.io/goodbye-clean-code/
https://www.ybrikman.com/writing/2013/09/29/the-10x-developer-is-not-myth/
https://brianmckenna.org/blog/softwerewolves

* being a developer
https://www.youtube.com/watch?v=M1t0egTZY44&app=desktop
https://muldoon.cloud/programming/2020/04/17/programming-rules-thumb.html
https://kk.org/thetechnium/68-bits-of-unsolicited-advice/
https://billwadge.wordpress.com/2020/04/25/the-secret-of-software-success/
https://www.deprocrastination.co/blog/3-tricks-to-start-working-despite-not-feeling-like-it
https://www.reddit.com/r/MachineLearning/comments/6l2esd/d_why_cant_you_guys_comment_your_fucking_code/

* etc
https://outline.com/gdqBaR
https://h313.info/ i like this site
https://andres.systems/
https://github.com/h313
http://dontfragment.com/using-python-yaml-and-jinja2-to-generate-config-files/
http://nathancorbyn.com/
https://www.perell.com/blog/peter-thiel
https://an-vu.com/What-I-m-Reading
https://www.goodreads.com/book/show/2333956.The_Annotated_Turing?ac=1&from_search=true&qid=6DmPQiMHk9&rank=1
https://pluralistic.net/
https://craphound.com/
https://erik.itland.no/
https://vsupalov.com/docker-arg-env-variable-guide/
https://varkor.github.io/blog/2018/11/10/monadic-do-notation-in-rust-part-i.html
https://www.pythonforbeginners.com/files/reading-and-writing-files-in-python
https://www.philosophicalhacker.com/post/data-point-for-job-seeking-devs/
https://benwiser.com/blog/My-blog-is-now-generated-by-Google-Docs.html
https://www.philosophicalhacker.com/post/data-point-for-job-seeking-devs/
https://macwright.org/2020/05/10/spa-fatigue.html
https://www.quantamagazine.org/how-to-design-a-perpetual-energy-machine-20200401/
http://www.catb.org/esr/structure-packing/
https://www.karenx.com/blog/how-to-become-a-designer-without-going-to-design-school
https://andrewkelley.me/post/not-a-js-developer.html
https://andrewkelley.me/post/intro-to-zig.html
https://en.m.wikipedia.org/wiki/Bonini%27s_paradox
https://linkurio.us/
https://m.youtube.com/watch?v=HyzD8pNlpwI
https://m.youtube.com/watch?v=b2AjRklfWQo
https://m.youtube.com/watch?v=dS6rCaDSwW8
https://m.youtube.com/watch?v=DpXy041BIlA&feature=youtu.be
https://m.youtube.com/watch?v=X3l0fPHZja8
https://joshtriplett.org/
https://m.youtube.com/watch?v=oYk8CKH7OhE
https://m.youtube.com/watch?v=XpDsk374LDE
https://mobile.twitter.com/sylefeb/status/1258808333265514497
https://m.youtube.com/watch?v=rq1DRuB9p7w
https://m.youtube.com/watch?v=TH9VCN6UkyQ
https://m.youtube.com/watch?v=4t1K66dMhWk
https://varkor.github.io/blog/2018/11/10/monadic-do-notation-in-rust-part-i.html
https://gcc.gnu.org/onlinedocs/gcc/Static-Analyzer-Options.html
https://marctenbosch.com/news/2020/05/siggraph-2020-technical-paper-n-dimensional-rigid-body-dynamics/
https://nikic.github.io/2020/05/10/Make-LLVM-fast-again.html
https://m.youtube.com/watch?feature=youtu.be&v=oTMuzM_-_0M
https://arxiv.org/abs/1805.09501
https://ban.ai/multics/
https://www.multicians.org/simulator.html
https://cs-syd.eu/posts/2020-04-28-genvalidity-improvements
https://metacademy.org/
https://news.ycombinator.com/item?id=23032243
https://medium.com/@thezedwards/the-2020-url-querystring-data-leaks-millions-of-user-emails-leaking-from-popular-websites-to-39a09d2303d2
https://sourcehut.org/blog/2020-04-30-the-sourcehut-hub-is-live/
http://www.sizecoding.org/wiki/Game_of_Life_32b
https://kasvith.me/posts/how-we-created-a-realtime-patient-monitoring-system-with-go-and-vue/
https://thedesignsquiggle.com/
https://machinelearningmastery.com/learn-add-numbers-seq2seq-recurrent-neural-networks/
http://www.julianzucker.com/
https://hasura.io/
https://www.planetminecraft.com/project/harry-potter-adventure-map-3347878
https://caseymuratori.com/blog_0038
https://rachelbythebay.com/w/2020/04/30/dev/
https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/
https://www.gnu.org/fun/jokes/eternal-flame.html
https://nesslabs.com/science-of-curiosity

https://blog.twitter.com/engineering/en_us/topics/open-source/2020/hunting-a-linux-kernel-bug.html

https://johnkerl.org/doc/ortho/ortho.html writing math well
https://medium.com/@anilkoonath/my-son-was-locked-in-his-body-for-27-years-then-he-found-his-voice-f9a4bedb1d0e
powerful
https://mobile.twitter.com/naval/status/1002103360646823936 how to get rich
or smth
https://www.newyorker.com/magazine/2017/06/05/the-work-you-do-the-person-you-are
https://blog.plover.com/misc/half-baked.html tired answers to half baked
questions !! both article on category theory but commentary on stack exchange
https://www.the-tls.co.uk/articles/feynman-making-the-extraordinary-look-easy/
incredible work on feynman
https://nesslabs.com/too-busy-to-enjoy-life
https://en.m.wikipedia.org/wiki/Onfim
https://ciechanow.ski/gears/ incredibly well done article on gears -- learn
the topic, but more importantly learn how to develop such good articles
https://qnkxsovc.gitlab.io/prob-vis/ another incredible writeup
https://macwright.org/
https://www.quantamagazine.org/amazing-math-bridge-extended-beyond-fermats-last-theorem-20200406/
http://norvig.com/21-days.html
https://github.com/mist64
https://www.instupendo.com/about
https://github.com/puffnfresh
https://blog.theboringtech.io/2020/04/16/time_is_the_real_currency.html
https://en.m.wikipedia.org/wiki/Wikipedia_Seigenthaler_biography_incident
https://en.m.wikipedia.org/wiki/Parable_of_the_broken_window
https://acoup.blog/2020/04/24/fireside-friday-april-24-2020/
* employment/work/practical
https://erikbern.com/2019/02/21/headcount-targets-feature-factories-and-when-to-hire-those-mythical-10x-people.html
https://erikbern.com/2020/01/13/how-to-hire-smarter-than-the-market-a-toy-model.html
https://erikbern.com/2020/03/10/never-attribute-to-stupidity-that-which-is-adequately-explained-by-opportunity-cost.html
https://www.tbray.org/ongoing/When/202x/2020/04/29/Leaving-Amazon -- hating
amazon
https://erikbern.com/2018/08/16/business-secrets-from-terrible-people.html
https://www.newgrad.tech/
https://www.cs.princeton.edu/~bwk/advice.html being productive by yourself in
cs
https://binarysearch.io/
https://mtlynch.io/solo-developer-year-2/ working solo
https://news.ycombinator.com/item?id=22050802 getting job through hn!
https://www.reddit.com/r/cscareerquestions/comments/9ujawa/programming_language_theory_jobs/
jobs in pl!
https://news.ycombinator.com/item?id=22990872 -- inspirational thread about
joirneys
https://www.reddit.com/r/ProgrammingLanguages/comments/9ffiky/how_to_get_a_job_in_programming_languages/
https://www.reddit.com/r/ProgrammingLanguages/comments/9bft4d/do_you_know_of_compilerish_job_opportunities_for/
https://en.m.wikipedia.org/wiki/Horn_clause
https://iism.org/article/driving-engineers-to-an-arbitrary-date-is-a-value-destroying-mistake-49
https://github.com/aftertheflood/sparks
https://nullprogram.com/blog/2020/04/30/
https://en.m.wikipedia.org/wiki/OODA_loop
https://esphome.io/
https://afnan.io/posts/lambda-calculus/

* living
https://www.gwern.net/In-Defense-Of-Inclusionism
https://hiepph.github.io/post/2017-11-24-emacs-org-syncthing/
https://iism.org/article/driving-engineers-to-an-arbitrary-date-is-a-value-destroying-mistake-49
https://rachelbythebay.com/w/2020/05/07/serv/
machiavelli what we got wrong
https://aeon.co/ideas/hypocognition-is-a-censorship-tool-that-mutes-what-we-can-feel
http://www.aaronsw.com/weblog/hatethenews
https://fs.blog/2012/04/feynman-technique/
https://surfingcomplexity.blog/2020/05/05/the-hard-parts-about-making-it-look-easy/
https://news.ycombinator.com/item?id=23092657
https://www.lifehack.org/articles/productivity/how-stop-procrastinating-and-stick-good-habits-using-the-2-minute-rule.html
https://psyarxiv.com/29ryz
https://www.robinsloan.com/notes/home-cooked-app/
https://mobile.twitter.com/david_perell/status/1257484391204352002
https://en.m.wikipedia.org/wiki/StartUp_(podcast)
https://en.m.wikipedia.org/wiki/How_To_Fail_at_Almost_Everything_and_Still_Win_Big
http://matt.might.net/articles/what-cs-majors-should-know/
http://www.cs.uni.edu/~wallingf/blog/archives/monthly/2019-11.html coveting
an online prescence
https://www.svese.de/impact-vs-backlog-frame-in-software-development
https://news.ycombinator.com/item?id=23091136
https://news.ycombinator.com/item?id=23088219
https://www.newyorker.com/magazine/2007/02/12/two-heads
https://www.indexventures.com/perspectives/rebirth-robotics-how-covariant-unlocks-power-deep-learning-robots/
https://thomask.sdf.org/blog/2019/11/09/take-care-editing-bash-scripts.html
http://www.call-with-current-continuation.org/
https://news.ycombinator.com/item?id=23057411
https://www.palabra.io/index.html
https://emacs.stackexchange.com/questions/5359/how-can-i-troubleshoot-a-very-slow-emacs
https://www.gwern.net/In-Defense-Of-Inclusionism
https://sarahguo.com/
https://blogs.scientificamerican.com/guest-blog/john-conway-reminiscences-about-dr-matrix-and-bourbaki/
https://en.m.wikipedia.org/wiki/Real_projective_plane
https://alexanderlim.io/
https://restyled.io/
http://wiki.c2.com/?GreenspunsTenthRuleOfProgramming
https://www.youtube.com/watch?v=OyfBQmvr2Hc&feature=youtu.be&app=desktop
https://www.youtube.com/watch?v=I5UjfaDRFq0&app=desktop
https://www.youtube.com/watch?v=WBWRkUuyuE0&app=desktop
http://shell.cs.pomona.edu/shtepper
http://www.ccs.neu.edu/home/hlnguyen/cs7805/spring20/index.html
https://arxiv.org/abs/1605.06640
https://www.youtube.com/watch?v=jG7dSXcfVqE&app=desktop
https://www.freecodecamp.org/news/free-courses-top-cs-universities/
https://www.goodreads.com/review/list/22328243-alex?shelf=currently-reading
https://mondaynote.com/old-square-discovers-psychedelic-valley-e38d1ef5bc0f
https://blog.metaobject.com/2020/04/maybe-visual-programming-is-answer.html?m=1
https://towardsdatascience.com/the-unreasonable-ineffectiveness-of-deep-learning-on-tabular-data-fd784ea29c33
https://nitros12.github.io/writing-a-discord-library-using-polysemy/
https://nesslabs.com/science-of-curiosity
http://beza1e1.tuxen.de/lore/tubes.html
http://bling.github.io/blog/2016/01/18/why-are-you-changing-gc-cons-threshold/
https://people.kernel.org/metan/how-to-trigger-races-reliably
https://news.ycombinator.com/item?id=23098090
https://heartbeat.fritz.ai/how-lidar-detection-works-8db24556a8d9
https://news.ycombinator.com/item?id=23095190
https://pywavelets.readthedocs.io/en/latest/
https://en.m.wikipedia.org/wiki/OODA_loop
https://www.youtube.com/watch?v=yy8jQgmhbAU&app=desktop
https://www.principles.com/the-changing-world-order/#introduction
https://www.tomshardware.com/news/amd-radeon-gpu-steal-data-radio-transmission-cybersecurity
http://c9x.me/articles/gthreads/intro.html
https://markan.me/the-delight-of-development/
https://rmsol.de/2020/04/25/v4l2/
https://divinations.substack.com/p/inside-the-clubhouse
https://www.youtube.com/watch?v=Sb0-I8FkUWU&app=desktop
https://www.youtube.com/watch?v=Sb0-I8FkUWU&app=desktop
http://blog.ezyang.com/2012/03/you-could-have-invented-fractional-cascading/
https://airtable.com/shrzJxrXCaJwwJO2T/tblMZ48gq36WojgtE
https://airtable.com/shrzJxrXCaJwwJO2T/tblMZ48gq36WojgtE
https://en.m.wikipedia.org/wiki/Monster_group
http://www.delorie.com/djgpp/doc/rbinter/it/06/0.html -- windows scan codes
https://remarkable.com/store/remarkable-2?utm_source=facebook-ads-network&utm_medium=paid-social&utm_campaign=2001+-+RT+-+Introducing+reMarkable+2+-+0-7+days&utm_content=Image+-+USD&utm_term=0-7+days+US
https://cutebouncingbunnies.wordpress.com/
https://www.netmeister.org
https://www.netmeister.org/blog/industry-vs-academia.html/
https://www.netmeister.org/blog/cs-falsehoods.html
https://www.partow.net/programming/hashfunctions/idx.html
https://en.m.wikipedia.org/wiki/Conway%27s_law
http://rmculpepper.github.io/gamble/
https://www.metalevel.at/sgp/
https://weiweihuanghuang.github.io/
https://www.3blue1brown.com/about
http://janvitek.org/whoowns.html
https://www.reddit.com/r/compsci/comments/69h3vb/rank_polymorphism_for_array_languages/
https://gitlab.com/antonok/enum_dispatch#technical-details
http://karolis.koncevicius.lt/posts/ascetic_bullet_journal/
http://mikhailkhoury.com/
https://zapier.com/blog/how-to-build-chat-bot/#how
https://byorgey.wordpress.com/2020/02/23/what-would-dijkstra-do-proving-the-associativity-of-min/
https://rhelmer.org/blog/
https://www.youtube.com/watch?v=M1t0egTZY44&app=desktop
https://mitpress.mit.edu/sites/default/files/titles/content/sicm_edition_2/book.html
https://ocw.mit.edu/resources/res-18-010-a-2020-vision-of-linear-algebra-spring-2020/index.htm

* tutorials
https://alex-hhh.github.io/2020/03/a-game-of-tetris.html
https://www.youtube.com/playlist?list=PLRGI9KQ3_HP_OFRG6R-p4iFgMSK1t5BHs&app=desktop
https://grahamc.com/blog/erase-your-darlings
http://www.marktarver.com/bipolar.html
https://www.reddit.com/r/artificial/comments/gxrnhq/d_paper_explained_synthetic_petri_dish_a_novel/
https://wespiser.com/writings/wyas/home.html write you a scheme
http://www.brattlebookshop.com/ the bookstore!
https://en.m.wikipedia.org/wiki/Frank_Frazetta incredible artist, some mdg
https://sivers.org/ cool entreprenuer
https://secondbreakfast.co/patio11-s-law
http://pkotrcka.inlisp.org/
https://github.com/dbp/website/blob/master/reading.markdown notes about
things reading
https://github.com/restic/restic good backup system
https://github.com/schollz/cowyo neat, encrypted wiki!
https://tinysubversions.com/
https://jae.moe/
https://www.paritybit.ca/
https://hackaday.com/2016/05/03/volkswagen-beetle-the-most-hackable-car/ the
hackable car!
