#+TITLE: Monday, 09/14/2020
** 20:36  things i stole from people smarter than me
[[https://forge.medium.com/33-things-i-stole-from-people-smarter-than-me-on-the-way-to-33-c38e368e5cb8][article]]
- see reading as a moral imperative! people died to give us the ability to read.
- if you have not read *widely*, you are as good as someone who is not read at all. read diversely.
- do not criticise without advantage
- assume others know when something is wrong
- quality time vs garbage time!
  - ordinary moments can be gifts if we appraoch them from the perspective
  - alive time vs dead time -- sit around and wait or make every second count
- some people lean in and some lean away
- Years ago, in a high school English class, I shared something with my discussion group. Later, people used what I had said in their essays and presentations and got credit for it. I brought this up to the teacher, telling her that people were using my ideas. She looked at me and said, “Ryan, that’s their job.” I’m very glad she said that and that I heard it at a young age.
  - amateurs focus on outcomes more than processes; we should always focus on the work and know we can rely on the systems to deliver us results
  - there are professional habits and amateur habits; make sure you are practicing the right one
  - 'competition is for losers'; when you compete, someone loses! run a race with yourself
  - Years ago, in a high school English class, I shared something with my discussion group. Later, people used what I had said in their essays and presentations and got credit for it. I brought this up to the teacher, telling her that people were using my ideas. She looked at me and said, “Ryan, that’s their job.” I’m very glad she said that and that I heard it at a young age.
    [[https://www.huffpost.com/entry/i-dont-know-how-to-explain-to-you-that-you-should_b_59519811e4b0f078efd98440?guccounter=1][i don't know how to explain that you should care about other people]]
  - ask the best questions. questions are what separate us from others, not answers
    + what do you do with your money?
  - production and peace are very different and cannot be compared
  - choose what will teach you the most, not what will pay you a most. make sure you choose opportunities that you will learn the most from and take the most out of
  - put your precepts up for display! make your commitments public so that they will be honored
  - no man steps in the same river twice - heraclitus
  - your last book won't write your next one
  - run rates always start at zero
  - former Coca-Cola CEO Brian Dyson: “Imagine life as a game in which you are juggling some five balls in the air. You name them — work, family, health, friends, and spirit… and you’re keeping all of these in the air. You will soon understand that work is a rubber ball. If you drop it, it will bounce back. But the other four balls — family, health, friends, and spirit — are made of glass. If you drop one of these, they will be irrevocably scuffed, marked, nicked, damaged, or even shattered. They will never be the same.”
  - there is no party line for what you should and should not do
  - do not feel obligated to do anything with your money
  - feel free to just not reply to things
    selectively ignoring is the key to productivity
    do not feel obligated to entertain everyone
  - sometimes you can just take a break
** 20:50 learning more
i learn more every day man
make sure your work helps you learn
every action takes some mentral weight
