#+TITLE: Sunday, 10/18/2020
** 19:11 notes on web
*** ur/web
god i wish this language had good exceptions.
if it had good exceptions and/or a good development cycle,
it would be /the best/ ecosystem for full stack web development
the guarantees it offers are so so so important
*** ihp
incredible work. it's the most seamless web dev experience i've seen and is completely succinct
*** elm
i love how good the compiler is and the development process is
i hate all of the boiler plate, the verbosity, and the higher kinded data types
*** other haskell libraries
most require some form of recompilation;
this is killer when it's not done automatically

*** etc
- Hot reloading is so important! Having to recompile just to view a new site kills the development process for me. With that project, you can't even reload; you have to completely recompile then view the app again. That isn't a sustainable development architecture!
- The installation process is a major blocker.
  Having an app framework to get started is incredibly good, as is having a tutorial
- Syntax /really matters/ - it mattered for react, it matters now. It's necessary
  to be able to syntactically distinguish frontend from backend
** 21:13 your past and being one of the lucky ones
it's good to know and acknowledge just how fortunate you are
to meet and know incredible people and
keep in touch with them for the rest of our lives

it cna be difficult when parents set expectations for children
based on their own lives and shortcomings; if this works against you,
deal with it yourself. you are not your past; you may act like it
and may be affected by it but are by no means bound to it

parents can mean well and screw it up
you will never be happy and satisfied living up to the standards of someone else

where would you be, then, if not hampered by your upbringing?
what do you want for yourself - think about how to get there
i want to be
- open source contributor
- work for consulting company
- build knowledge of ecosystem
- innovate with developer tools
** 21:16 reducing context
is incredibly important
your environment impacts how you work and think, consciously and subconciously
it determines what you are distracted or inspired by
it determines what you are able to accomplish
it determines your skills and abilities
it determines you

curate your environment to represent you and it will urate you and your work
** 21:18 track consumption
https://rustwasm.github.io/docs/book/game-of-life/introduction.html is this a good idea?
it's good to inform others and build an online prescence
but may be bad for the individual

curate a personality without public information?
it may be better to appear deliberately cryptic to be cool

he also has good signaling as a service article i have notes in my concrete journal on it
** something acronym notes
[[https://m.youtube.com/watch?v=mbdmuC22bXc][video]]
notes on interview with errolson
my personal initial thoughts:
- scalper, costs lots of money etc
current uniform: P30A, LA6B, sleeveless tee
** slackbot on perosnal server
prompt with questions at times
import into data collector
integrate with cal for feedback?
** ava
*** desire and optimism
[[https://ava.substack.com/p/desire-optimism][article]]

/peak experience/; changed life, somehow.
buddhism suggests best solution to pain is to give up wanting
the object of desire is never object enough; not even actual objects.
we are always feeling urgent desire; the physical attempt to reach the other
with the acknowledgement that they will be forever out of reach

we try to be formed and held onto and kept by him,
but instead he offers us freedom

Schopenhauer: man can do what he wills, but not will what he wills.
it is not up to us to stop wanting, and it is a gift to want things,
to get what you want and to lose it.
the lord gives everything and charges by taking it back. what a bargain - jack gilbert
we will always lose time, and chapters of life, and it is inevitable for us to lose
our characteristics, possessions, relationships and knowledge

/our optimism can only ever be a cruel optimism/.
/no feeling is final/.
the bad news is that you are tumbling thoruhg empty air; the good news is that
there is no ground to hit

it is important to live with all of our wanting and appreciate it for what it is;
to be comfortable and confident in the moment .

*** ash is purest white
[[https://ava.substack.com/p/ash-is-purest-white][article]]
a movie
dovetails well with kafka's /letters to milena/
the sentiment that passion can burn you but leave you clean
*** wearing clothes
[[https://ava.substack.com/p/wearing-clothes][article]]
/zazen is the art of doing self/
we have a naked self :: an awareness that is just you .pure and unprocessed
but we wear all sorts of clothes as we progress through life. the entire
problem of most of our lives is deciding which clothes we should wear

Uchiyama's point is that the clothes don't matter; the delusions of self should not impact
your real relationship with the world. to believe that nothing that matters more than
internal experience and still have the flesh to dress and ahve a job and feel desires;
how do you reconcile this concept of putting on masks and concrete specific desires?

what if you enjoy living in such a complex world and falling in love with the wrong people?

self improvement and self esteem are just materialism - the self does not exist
in the way we think it really does

we should /enjoy/ living in the world and having these experiences; we should enjoy living
life and gathering these collections of concrete memories without any sort of ephemeralism
it is /okay/ to express our desires and loves of all of these points and it is okay
to keep lists of everyone you are ever going to love and will

to be *in* the world; it is important to try to be in the world
*** passion economy and future of work
[[https://li-jin.co/2019/10/22/the-passion-economy-and-the-future-of-work/amp/?__twitter_impression=true][article]]
the creator stack, or enterprization of consumer, allows individuals to pilot their own individual companies and accept lots of income
online market places permit 'turnkey' ways for people to make money, trading their time for hourly or per opportunity pages on a website and allowing the consumer and provided to move with more liquidity

though this is being your own boss, you are the boss of a one dimensional world
for these people, we crave living a livelihood in a way that highlights our individuality
*** unbundling work from employment
[[https://li.substack.com/p/unbundling-work-from-employment][article]]
often monolithic entities distintigrate into many single purpose entities; craigslist attempting to fill every niche spawned so many services to serve many of its vertical goals, and unbundling the idea to execute verticaly generated tons of revenue

the 'organization man' - the subsuming of agency for large corporation - is collapsing to micro entreprenuers who are leveraging skills and knowledge outside of the context of an employee relationship

we have removed gatekeepers through technology and spawned independent work efforts; 20-30$ of the wrking age population of the US is engaged in independent work

some are shifting quickly to digitally mediated self employment, not just for hobbies but for traditional careers as well!
catalyzed by innate human desire; the primary motivation for self employment is often financial
Daniel Pink's theoryu of motivation -- humans are driven by autonomy, mastery and purpose, all of which independent work may be able to better facilitate than alternatives

tech platforms remove gatekeepers and democratize access to customers worldwide
horizontal or vertical unbundling? i.e. patreon: horizontal; substack: vertical. what is the best approach?

/focus/ on a particular industry provides greater value, allowing non producers to turn into producers and actually expand the market of people who can function in a particular industry

they provide deeper value to help the worker manage and glow the business, taking much of the load off of the individual and benefitting the the group and collective. provide depth of value challenging for horizontal to communicate

reintroduce services and benefits workers lose when they choose to unbundle from their companies, forming a better support system for independent workers

horizontal approaches act as discovery services and destinations; often social media is seen as marketing for this action of unbundling the work environment.
** 22:22 you and your research
[[https://www.cs.virginia.edu/~robins/YouAndYourResearch.html][article]]
characteristics
- having courage
- having confidence
only a man of 'infinite courage' could dare to have thoughts
like shannon has had!

age is a big factor; some are disgustingly young with their
best work, and others accomplish brilliance when they are young in STEM,
but those in the arts (music, politics) accomplish their work very late

it is hard to work on small problems when you are famous or view
yourself in such an imprtant fashion

genius is clearly primarily determination, with the inspiration
as a necessary, but often kind of trivial,  benefit . it is only when
these things combine that people really become successful

one trait is ambiguity and the tolerance of ambiguity; avoiding the
belief of whether something is or is not true, instead
believe the theory enough to go ahead but double it enough to notice the
flaws and faults. great contributions are not made with another decimal place;.
being very aware of what is very true and what doesn't quite fit is important;
write down every ambiguity, everything that is unclear and may not align with our perception
of the worl /must/ be written down, recorded and expanded upon.

all flaws must be tracked and we must explain them and how the theory can be changed to fit them;
expanding to handle these edge cases can very well be the great contributions of the framework.

this extreme emotional committment is practically necessary;
we know little of our subconscious other than that our dreams come out of it,
and if our subconcious is able to work on the problem, we can awaken to the answer.
it's so so so important to /focus/ and /commit/ to a current problem, truly thinking about the solution

*Keep your subconscious starved so it has to work on your problem, so you can sleep peacefully and get the answer in the morning, free.*

it is so important to ask what the most important problems are!
if you aren't aware of important problems it is unlikely that you'll ever do important work
great scientists have thought through a number of important problems and how to attack them
important problem has a very caerful phrasing; important problems have an /attack/. not time travel but tangible approaches with problems

planting acorns so that oaks will grow - you can't always know exactly whre to be,
but you can keep active in places where something might happen. it is okay
to stand on top of the mountain where lightning strikes, to take risks for such inspiration;
to do great work you must work on important problems and you must have an idea

'great thoughts time' -- what will be the role of computers? what will be the goal?

when an opportunity opens, great scientists drop everything and pursue it. they already had the idea
and had to find the opportunity; as they understand the problem, they find the /in/

work with the door open or the door closed:
if you work with the door closed, you get more work done and are more productive,
but later you don't know what problems are worth working on!
the people who work with the door open are constantly interrupted, but always get clues
as to what the world is and what might be important

you must also /sell/ your solution, and sell it to other scientists;
these people are all busy with their own work, and as such they do not have the time
to entertain others' ideas, work and ambitions.

on math:  the effort to generalize often means that the solution is simple
it is a poor workman who blames his tools; the good man gets the job done with what he's got
and gets the best answer he can. by altering the problem you can make a big difference to allow
other people to either build on what you've done or duplicate what you have done --
just as easy to do a general job as a special case!

selling is:
- clear writing
- reasonably formal talks
- informal talks
'back room scientists'; keeping quiet, would speak up after a decision has been made rather than
speaking up impromptu and advocating for specific things

give speeches, and gie good speeches;
why are siome papers remembered and most are not? technical person wants a highly limited
technical talk, while the audience wants more survey and background; the conversation is
a mediation between these two extremes, and finding the proper words makes a talk great

you /must/ work on important problems; pasteur: luck favors the prepared mind.
understand the meta problems the bigger problems, and mediate your work; take control if what you'd like to work on when you become more successful, and as more is demanded of you you have more power of choice as to what to work on


is the effort to be a great scientist worth it? doing first class work certainly is, but bosses are often in the way of such discovery -- and yet those who accomplish want it to do it again. those who have done great work still enjoy the slog, as the value is in the struggle moreso than the result

/drive and committment/ - doing great work with less ability but with deep committment to the first class work is vital to its success
personality defects: i.e. wanting total control of the system and not recognizing need for support
often good scientists will fight the system rather than working with the system and its advantages
ego assertion: assert your ego and personal appearance or learn to conform properly? don't let your personal desires get in the way of accomplishing what you care about
but we cannot always give in; often futzing the system is part of the fun of it
originality is being different! often this originality costs

self delusion is very common;; there are so many alibis
must know yourself, your weaknesses, strengths, and bad faults, often converting them to assets

talking to other people is important, but a session strictly for 'brainstorming' is often not whrthwhile; if it's necessary you need capable people. reduce the sound absorbers, get the critical mass in action but without the sound absorbers who will stimulate. get people who will respond, interact; look for /stimulation/ and /interaction/ when you talk to others. ask questions and leave /stimulated/ [i feel this has happened to me with lerner, or with a couple of other professors i've interacted with]

do not echo ideas, contribute to them, doube them, interact with them
if you read all the time what others have done you will think the way they thought
if you want to think new thoughts that are different, get the problem reasonably clear,
then refuse to look at any answers until you've thought it through carefully.

*you need to keep up to find out what the problems are; do not keep up to find out the solutions. the reading is necessary to discover what is possible but reading to get the solutions is not the way to do great research*

books show us how to find the way; while papers stimulate someone tomorrow
expect a good job, and expect good work, and have pride in what you do; it is valuable to have first class people around
of course there is always luck. there is always determination adn there is alwasy skill

the time is long past for me to stop reading and start doing
