#+TITLE: Wednesday, 10/07/2020
** 23:55 turn maybes into wins
[[https://x.sett.com/4c087979f48ba97a/082f8387f9feb83c]]

good things- maybes into wins!
- buying an island with friends
- relationships and marriages!
- quitting job!
- dropping out of school!
covid? it's wat you do with it!

do hot htink at a loss. no point in focusing on obvious wins. it's important to recognize when a win is just a *maybe* and actively work towards it. don't wish it, make it happen. be very stubborn about turning those maybes into wins. don't rely on the easy wins for carrying you along
** 23:58 on maintaining attention
[[https://email.mg2.substack.com/c/eJxVkUtv6jAQhX8N2RHZzoOw8IILSkXUhErlltJN5NgDOA87ShzS8OuvA6sr-Wjk47FmdD7ODFx1N9FW98YZeuhyKShG4dpDBDuC-gJHQeTIPr90AA2TNTXdAE47FLXkzEit5h_E8_HKuVG8CpgnggJzEUHEScAFWV0KCPwCIlhFzjwnZ4OQoDhQuEM3aQVOTW_GtP3C2yxIbA-7M7cfit4wXrlcN9ZqrbRa2hWUsZLqumTGgJpXWHix0RXYuoMpwZx8Td-krval_k135yB9bKb0c5T8bf0Q8br92e7DrPw7pY_zmG5HyU4xmnuzcmPF0eHIyfs2abmXyoNMRnHam7RMUXrk0voPe3_6hZeh9--kPp8yxE7rYa-Qm5VV7d_Im-rM4U-blCCry-HD1FG7PUbLqIvRL4rj3c-DIUdSggjCCBGCfRKELnbxRetIjoFo8MJHzZX8F4PT0ZJVwG93ZlhtG64zkeeLBZLb2gxKmikHxYoaxIuVedF9Rm-mFqiCsa_Bhte9TAswDIgXIuTYaULPGVOL4B9M77jz]]
post from ava

- life is a fight against entropy, cleaning things and developing regular habits
- it's hard to be good at maintaining things!
- attention is both effective and flawed
the best skill to develop isn't progress, it's *maintainence*; not just getting to your goal, but keeping up with it and working to sustain your quality of life, your skills, your status day after day. or you will lose them

western philosophy: doing; eastern: being. we must reconcile the two.
sometimes it is hard to write - how do people do it? - but you have to eke things out line by line regardless.

god i love her writing
** something
udemy
- fake the chicken first.
  need lots of courses for udemy? borrow videos from perfect sources and have signed up users !
  most of these users don't stay though...
- make the chicken - pay for users?
- ask investors to help out with udemy!
- hold events and add them to the camers !!
- grow the chicken:
  - find distribution channel
  - find instructor knowledgeable
  - make deal to give distribution, instructor and owner the revenue
find that true product market fit
do whatever you can to get that initial traction
the product market fit isnt always obvious!
stay lean until you have traction!
** trusting yourself
[[https://email.mg2.substack.com/c/eJxVkUuP2jAUhX8N2RHZTshj4QUamgo0SdUOlKGbyHEuicHYqe3AhF9fA6tKtiyf-zjSdzhz0Gkz0UFbF4wWTC1ailGSR4jgoKVxi7NFFghbHw3AhQlJnRkhGMZGCs6c0OoxQaIYp0FPmwVJiR9OmjzhWY7TDAHPOUkyYEmaHoOHT83GVoDiQOEKZtIKAkl75wY7i5YzUvjDriy0Y2Md4-eQ64uXBn-1mnt364Tq5pMejQV5nEWF02dQs2gF0wZz8nv6JPK8PumvcnVYlPflVH7cBP-e39siH_68rZNq1cXV6hCV4ibYvkCP3uq0_CpPP-Nq2y3e3zYD99UfYnNr92tXnkpUbrnw-t3_n3oTVej9cyMP-wqxfT6uFQplEQmIza7C8yy237D5td15clo6ntz3S81Hy3a9NR_HXSAoQQSh3POKcELyEIfuLzsnveC5msXo0pH_CASGntgZeH9ljknf0D3CeFZ8FrV_L6MSbqpBsUZC-4rJvYJ9UnfTAFTBzUpwDsxL9NnFWRYnKQm8W6v9UkU9_X-pMraa]]
descriptive exposition -> reason for the exposition -> reason stands by the rationale behind the topic.


how you feel determines what you believe, and what you believe determines everything. belief is deeply aesthetic.

my beliefs are ugly, i think.

morality is merely aesthetic: Parfit may believe in aesthetic; Kant believes that taste shares characteristics in moral judgement

many require constant validation of their beliefs
some are pushed heavily towards the most socially validated paths of achievement
writing: how to be alone. how to pay attention when nobody is paying attention to me. start to learn what you find beautiful. this is photography for me

if you don't delineate reality for yourself, other people will rush in to do it for uou.
isolation forces uou to take responsibility for my own actions and beliefs
never hide from yourself to please others
choice by choice one teaches themselves who they are. self wordh is continuous self respect - Joan Didion
** green and gold, next day
[[https://email.mg2.substack.com/c/eJxVkVGTmjAQxz-NvOkkIXDwkAfuHK_YQ9trr2pfmJCsGIiBgyDFT9-oTzezmZ38dzeb3Z_gFsqmm1jb9NYbeuhyJRlGYewjgj3JqMRREHmqz48dwJkrzWw3gNcOhVaCW9WYWwXxKX7yTizkNIopgfAoCp_GRx_TGIdhgSUENCLIu_XJ-SAVGAEMLtBNjQFPs5O1bT_zkxlZOeMXvuiHordc1AvRnJ3UulO6P5g5N3JeNlrO_JVtajAzfwnTGgvyZ9oTXadV8y9bHoLsmkzZr1GJ1_gqV3H79yUNs-sH3VQHkqlR8d0K3XI3VTJulwnKqjJ4e1m3ws_UVq1HuUttVmUo-y2U06_uftcLf4Pe9mt92G0Q38VDatDi22V8_ZF-7N-_E_rO5_pz-Nw8pxca7eqxpO3PINDD1tZ50jaeYgQRhGJCcBxgEi_wgpveXiv0hCidUXQuyZfhvY5VvAZxunDLtUsobxzuEYchd_48GGWnHAwvNMgHIftgel-4nVpgBsZeg7XQPUSHzQ-iMAyJ57rJxj1qmFv8f3IKsyE]]

In the beginning I imagine that there were nebulae and um, planets being formed and the one who dreamed us standing in the middle of all that negative space, thinking, I guess this is how it will be.

He dreamed us. Or She did—I don’t think there was much fussiness about pronouns in the beginning. And there were agate blue rivers and valleys and buffalo streaming through fields before we paved them over and built apartment complexes and gas stations. Those came later. We ruined almost everything that was given to us in the beginning, but that very act of destruction—which was either one continuous act over many centuries or the aggregated Frankenstein of many separate actions, depending on your perspective—was of course also an act of creation. We were the smartest creatures on Earth and we used our collective intelligence to invent strip malls and Eggslut. We were dreamers. At least part-time. The rest we spent fucking our lives up mercilessly and reading Madame Bovary.

Sorry, I’m just trying to reconstruct it all for myself as a child of modernity. Sometimes I think about what would happen if all of civilization was destroyed and we were living in a post-apocalyptic world that somehow managed to resemble a pre-human world, all t

ongod

daniel everett : time with piraha, amazon tribe with no concept of abstraction. they lost interest in jesus when they realized he had never met them. they are completely uninterested in anything that falls outside of personal experience, and will not trust other things

wehre we are heading: do not mind the body and needing things to feel okay, but being a good animal isn't enough for us

what kind of mutations are worth dreaming of? adam curtis: pandora's box


active life - execution; reflective life - all nostalgia
** i love visualization
sometimes a sound can paint a picture of a world
an environment
a fantasy
i want ot make that fantasy possible for others to see,
to get it out of my head and into yours

maybe this is a dream
