#+TITLE: Saturday, 09/19/2020
** 13:15 lack of divorce
i wonder how much parental divorce would have changed me
extremely privileged to realize that i have had a good upbringing without substantial trauma,
but i wonder if a divorce and the subsequent process of navigating my relationship
with my parents and others would have been beneficial for me in terms of personal
and interpersonal development.

navigating coplex familial relationships feels like a headache, but it may have
made me more sociable.

i suppose i am just looking for justification for my current state :: why am i not currently
having an easy time reaching out to others? how do i begin to navigate a new environment?

maybe these things will come with time
** 13:35 tattoos
i used to be afraid of permanent modification
now i welcome it :: it feels like i am recording myself at a moment in time
to be ashamed of the past is to welcome the future
it is good to acknowledge myself now && continue to move on!
** 22:00 awakening the prana and apana
[[https://freddieyam.com/gen2/p/the-day-my-kundalini-woke-up.html]]
the kundalini is the way to enligntenment

focus your attention on the place you expect to find them
- prana :: associated with defecation
- apana :: associated with breathing
senstations in rectum and chest, respectively
the sleeping Kundalini is said to coil around the coccyx, or vestigial tailbone

attempt to visualize light
stretch physically to induce feeling of hollowness
perceive energy moving downward throuhg lungs, contracting chest muscles
abdomen: contract muscles to induce accumulating energy
perceive feeling of lower spine moving towards the head
anus downward moving energy due to apana
two attentions: induction of particular percentpions and looking with imprecise expectations


*** provocations
- sphincter muscles quivered
  light in head becomes increasingly bright and dense
  voltage building between head and anus
  kundalini explosion from deliberate isometric contractions of anus, buttocks, perineum and thighs
  shaking legs violently, sometimes pressing thighs together. tiring

  link between sensations in head and anus
  cold sensation in abdomen below navel
*** result
after three days of meditation and several hours on the third day
mind becomes quieter with head splitting between anus and head
brilliant and deafening noise, work dark and huge jet of energy through the body
completely filled head and body, originating at collar bone
light and noise vanish instantly

*** outcome
clearly elevated spiritual state
others seem divine, aware of essential goodness and infinite importance
condition lasted three days; conviction that world is benevolent and good humored
you become a saint and smile at everyone! you can permanently remain in state and stay a saint

absolutely happy and fearless : )
*** follow up
[[https://realization.org/p/freddie-yam/after-my-kundalini-woke-up.html]]
we realize that everything is god.

** 22:08 my day today
i basically got lost in sodermalm
seeing christmas music in the park, people fly fishing, park in the city
it was like bliss
everyone so happy
feels like heaven
hard to say that people are depressed here, people seem to be very content and to worry less
i also got lost and that was very stresffful but i love the nature vibe
** 22:34 survival guide to phd
the namesake article can be found on andrej karpathy's blog
- maximizing variance
- extreme period of personal growth and self discovery
- high density of exceptionally bright people who will become your best friends
- expertise, only opportunity to become a recognized expert in the world at *something* !

there are lots of downsides! this is a very specific kind of experience that deserves
a disclaimer. will end up working very hard and have to be OK with the suffering. need
mental fortitude to handle the pressure, push through adn become successful

will have to put up with friends making actual money and living while you toil at PhD:
(i'm actually totally okay with this, honestly.)

struggle that months of work are put into paper with a few citations while friends
are working on exciting startups and pushing product
will continue to question your life decisions
must be certain that you can thrive in environment pursuing science.
unsure: lean negative by default but mbe open to transformation
phd has strong intrinsic value, not necc a means to an end !!!!!!!


*** picking the school
should be a top school
top schools will attract other top people

have potential advisors -- more than one! -- that you would like to work with.
student advisor relationship is incrediblt important. must prioritize each persons goal,
understand advisors incentive structures and department projects
you must help them gain more recognition through you! this is actually not just pro interaction

many axes to be aware of: fluffy vs professional, details of work vs hands off,
some on specific models and others on specific tasks,
some will meet you frequently and some wont,
some answer emails right away and others never,
some strongly support and others are cool with whatever

should first collect references; talking to students in casual environment etc
want truthful answers to super specific questions
must impress advisor and appeal to them for them to pick you!
consider the entire lab

an exercise in the outer loop. fun adn frustrating experience, operating at a meta outer loop
what problems are worth solving? what problems are ripe for solving?

we must develop a sense of 'taste' when it comes to problems; what problems are worth solving?
what are worth thinking about? is it time to solve those problems yet?
make sure you develop that taste as you come in
the problems should be well conceived, tractable *and* relevant. make sure to start refining these.

make sure you know your advisors interests and strengths interests and strengths intimately

*** sublinear scaling of hardness
:: a 10x more impactful problem *feels* 10x harder,
  but this is a fallacy! it is often at most 2x - 3x more difficult to achieve, and can be easier
  but it forces you outside of the box, confronting the real limitations,
  thinking from first principles, changing strategy and innovating
  improve by 10% you are likely to, improve by 100% you will have to do things differently
*** be ambitious but with an attack
there are lots of important problems that do not make great 'projects'
/"If you do not work on an important problem, it's unlikely you'll every do important work./
/Great scientists have thought through, in a careful way, a number of important problems/
/in their field, and they keep an eye on wondering how to attack them."/

Ex. The three outstanding problems in physics were never worked at at Bell, but they are not
actually important problems because there is no attack! The reasonable attack is the
most important part of pursuing a problem.

*** be the man
be the person who did x. make a mark.
you develop incredible skills !! according to Gladwell, a PhD makes you a bona fide expert
imagine being an expert -- will these tools advantage you or excite you? hell the *fuck* yeah
*** negatives
**** 'incremental work' :: makes something more complex, gets better benchmark
  + not very productive, but will not be highly cited or used
ex. his thesis: took a long time to navigate the metaproblem and actually find the problem space and problem
to be excited about working on.chat about interesting problems and see where interesting things are going.
find something fertile, something promising, something with a lot of interesting possibilities
find something practical at the moment - is it time for the technology? is it not there yet?
**** resistance
the advisor is not invallible
**** do not play game
a phd is more than just a sequence of papers
you are a member of a community and your motivation is to further the interests of this community
look beyond the academic game and think about what you can improve beyond all of these papers! e.g. blog
improve academic search tools! improve teaching! improve the work.
*** writing papers
make sure to review lots of papers to learn
have large exposure to lots of bad papers to learn what *not* to do -- more important
than just 'following a formula' to a good paper
rely on the 'gestalt' of the papers; how does it look? how is the density? how is the framework?
use the same language as others so that professors will pick them up and favorably judge
identify the *core contribution* of the work and focus entirely on what forwards that
develop a vocabulary to use. do this by writing frequently
*** attending conferences
go! go! go to the confreences! make sure to visit and it is so worth it to pay for them
it is so important to become part of the community and share ideas,
and many of the problems you are working on are so in line with the priorities of others in the field
that you might as well play an active part in discussing methods, ideas etc

'there are three stages to a phd; in first, you haven't read most of the papers. in second, you recognize all of the papers. in third, you've had a beer with the first authors of all of the papers!'

there are no shortcuts or cheats. you can't game the system or put up false appearances
ultimately you are trying to do good research and if you game any of the proxy metrics you won't
be successful in the long run
