#+TITLE: Sunday, 11/15/2020
** 15:43 backyard
[[https://email.mg1.substack.com/c/eJxVkUFvozAQhX9NfAvCNoTk4MOqSbp0F6JWJNvtBRk8BCdgI2xC4dfXSfey0oxGejN6I72v5BbOup9Yp41Fg4E-l4LhTbBeh_4KCeZHpIwKJE1e9QAtlw1D3VA0suRWanW_XmOK16hmERd-JVaE-AHBOMQYopD7OMJAuAjKCN1_5HwQElQJDG7QT1oBalhtbWcW9MeC7F0Zq3sJxjNDYSwvr16pWyd3rsea26XVyx64WFayh1FrsaB7q6-gFnQL0wsuyWl6J801vujPQ_YaHLbHMZWjLJ83s9hvuo-neJVkxzmddzSZExO3TS0e2t8xzeLwkCVhOo2Sv6ez85Dlz5P8nZ0_k3kXxHcfepIP_e73hKePP_uLeG5uhXzZeK-3xByyY1op3VzfqjTxV7_0fKDVbZsnest38UTat2MAdYwkIz7xMcbUzU0YedjjlI7VeFNtFy4Cvz3j_0JAPbvwK7iNNMp6WjXSxedo5G7ZDkraKQfFiwYEs_0AyH5jfeRupw6YgtE0YC303-KddUgjHFGK3CehHWDF_gH4AtFuuL4][substack link]]
A couple of years ago I went to a talk by a neurobiologist named Andrew Huberman that was, I think, broadly about mindfulness. But he said something as kind of a casual aside that’s stuck with me ever since: Humans, like predatory mammals, have eyes on the fronts of their heads in order to be able to focus on a single point (prey while hunting). That focus raises stress hormones like cortisol in the brain, and that’s why predators need to spend so much time recharging. It’s why if you go on a safari and drive past a pride of lions they’re probably all asleep, and it’s why my cat is currently taking her second nap of the day after spending an hour staring at the hall closet.

Huberman [said that] you can imagine how much those stress hormones get ratcheted up when we’re spending so much time focusing on tiny devices in our hands. We’re literally hunting for information. And we still have a lot of “wild” in our brains. I think that when we talk about “wilderness” and how it’s being lost in our modern era, we have to look inward as well as outward.
** 16:33 
