#+TITLE: Wednesday, 10/14/2020
** 13:33 corner office
 [[https://ma.tt/2020/07/corner-office-interview/][src]]
 In distributed organizations, everyone can have a 'corner office' - a space that they own.
 there is so much more you can do in terms of space management when you define the office;
 and you can choose to define your office as the space you feel that you will be most productive in!

 This blog might be relevant for future work, it's written by the creator of Wordpress.
** 13:41 slow march of attention
https://linus.zone/latest
control, attention and relationship
how to feel in control
be conscientious about where attention is. is your *complete* attention going in the right direction?
scattered attention can quickly contribute to a sense of chaos and lead to a lack of control over work!

Do not think just of /spending/ attention, but also of /redirecting/ the attention you waste into things that make your time more variable and enjoyable.

When you are working on something, redirect all of yourself into it! FOcus on focus.
[[]]
[[https://linus.coffee/note/knowledge/][what do we need to know to start making a difference?]]
- ds knowledge: vocab and ontological understandign
- prerequisite is vocabulary - you must speak the lnaguage to understand the ideas
- ontological knowledge is so easy to pick up when you're /doing the work/ vs relaxing
  format text to be scanned easily!
