#+TITLE: Tuesday, 08/18/2020
** 21:54 day two of internship
this was really good! i thoroughly enjoyed work and feel that i was fairly productive.
i would like to work on the platform more.
I'd also like to prioritize being more efficient with my time -- i feel that i have used a lot of time
(wasted) and that i could be being more productive and spending more time in the city while i am here!

I would also like to get to know more people in town -- i'll have to figure out the best way
to get out and meet others.

all of my coworkers are super nice and understanding. I am very happy to be working here.
Everyone is transparent and the goal we are working towards is very clear.
This is the work environment I want.

i am still very much stressed about housing but am hoping that my coworkers can help me figure things out to that end.

help me find more friends here !! i really want to reach out to more people in the area.
we'll see how this goes.

i do need to make sure i make it ot my migration agency appointment tomorrow.
let's hope i don't miss it for {silly reason}.
