#+TITLE: Sunday, 09/20/2020
** 17:22 its a healthcare today
i need to learn how to improve my health! here is how i can do that

*** biohacking lite
http://karpathy.github.io/2020/06/11/biohacking-lite/

nutrition!
he experimented a lot with some crazy shit and wild research over the course of a year, learning more about the body
**** weight focus
- weight is blunt instrument and barely associated iwth health
- weight loss is sensitive and complex
weight: bodies are 'full'
batteries are adipose tissue and triglycerides stored within,
stored by body to be burned for energy
- all discharge to synthesize ATP from ADP; some also goes to redox power
- common to all life on earth! everything performs this active transport operation

- four batteries
  - phosphocreatine system :: super short term battery. buffers phosphate groups
    to quickly cycle ADP to ATP; attached to createne. athletes take createne supplements
    barely anything here but good for short bursts
  - glycogen :: short term battery. stored in liver and skeletal muscle. can hold 120 grams in liver, 400g in skeletal muscle, with about 4g in the blood. we get 4kcal/g from oxidation of glucose, so glycogen battery stores 2k kcal, or the base metabolic rate of an adult for 24h. not very energy dense and binds a lot of water
  - adipose tissue :: fat; long term body. dense high capacity battery pack. significantly more energy dense, 9 kcal/g for energy.
  - lean body mass :: when fasted, biochemistry burns lean body mass like muscle for fuel as a last resort

all are charged and discharged at all times
cookie -> glucose -> bloodstream
if too much glucose:
anabolic pathways -> glycogen in liver
if in vast abundance: convert glycogen to fat
catabolics:
use creotine for first 3 seconds, glycogen for next 8-10 seconds, then ramp into 2 and 3 as heart rate, breathing rate and oxygen transport increases

moving energy around is expensive: creotene is cache, anaerobic is ram, and aerobic respiration is the disk, moving fatty acids through fatty tissue through the bloodstream but is super efficient storage wise

body weight is just a sum of the atoms; day to day fluctuations mostly due to water retention (in turn controlled by sodium, glycogen levels, horomones) + some stool
we breathe out most of our weight in carbon dioxide! was triglyceride molecule in fat

combustion = weight loss
cellular respiration: 'slow motion' combustion of ADP and ATP
ATP Synthase traps 40% of energy in ATP, more efficient than internal 'motor' which operates at 25%
lots of stuff happens in the chain: foot chopped into acetate and electrons are stripped, flow down to electron transport chain etc

**** Energy
humans have simple way of consuming energy - breakdown of food, narrow subset of organic molecules
proteins, fats, carbs and molecules like alcohol
cannot metabolize:
- celluluse/fiber, also a harbohydrate
- hydrocarbons: only by internal combustion

***** output
*not* mostly from movement! we are super efficient with movement and it is expensive to just exist
- homeostasis
- thermal regulation
- respiration
- heartbeat
- brain/nerves
- blood
- protein synthesis
- active transport
basically the 'passive energy' of being human is far more expensive
this is 'base metabolic rate' and we burn this for free every day
common estimate for BMR for men: 10 * weight(kg) + 6.25 * height(cm) - 5 * age(y) + 5
this is a free win! workout is a drop in the bucket for weight. cv health is different but this workout has nothing to do with losing weight

**** introducing deficit
greater deficits could stress out, make hangry, and sacrifice lean body mass !!!
good to lose maybe 1 lb per week
to do this, 1g of fat about 9 kcal, adipose is ~87% lipids, so 3500 kcal is 1 lb of fat

this means target deficit of 500 kcal per day; can be much easier to make this up with cardio than with pure calorie restriction

helps to adopt 16:8 intermittent fasting schedule :: skip breakfast, eat only from 12 to 8 pm
this controls appetite and reduces snacking

**** specific diet:w

low carb, mostly pescetarian
avoid nearly all sources of sugar
stopped drinking calories in any form
regular cardio a few times of week, regular existance training
improved a number of biomarkers supposedly

track:
- calories in food
- energy output
compute actual weight loss input/output!

discrepancy varies iwth the amount of carbohydrates in diet
eating increases glycogen levels, glycogen soaks up water

body composition: need to better understand specific body composition
**** simple diet recs
- eat from 12 to 8pm only
- do not drink any calories
- avoid sugar
- exclude carb heavy sugar
- lesser extent: natural sugars, berries are ok
- meat: chicken > beef/pork
  + ethical: intelligent large animals
  + envionmnetal: large footprint, lots of deforestation
  + read meat associated with some cause for concern
  + lots of diseases are zootopic and come from livestock
- only shop on outer walls of the store, stay clear of the cetner! michael pollan heuristic
**** Comments
- french doctor or something
  - main problem is sugar, not fat
  - eat as many veggies as you can
  - as many fish as you want (bake not cook!!)
  - eat meat as if you had to hunt it with a bow
  - ban every processed food, sauce, appetizer; if you wouldn't need a single ingredient don't eat it
  - learn how to cook plz
- very strong measures correlating with dexa scans:
  - waist just above belly button; no muscle and principal deposit of internal body fat
    take body weight and waist size every day
- weight track
  - must have a diet to weight less
  - must have distinct diet to lose weight
  - most do low impact cardio, like walking several miles a day
  - must do resistance training
  - these accomplish:
    - stable weight
    - take off weight
    - increase background caloric burn
    - encourage lean body mass loss over fat loss
    you must develop a routine and not vary from that routine for the rest of your life
- eating japanese is easy
  - bowl of rice
  - several small sides
  - small cup of miso soup
    can be boring but helps stick to consistent diet https://elemental.medium.com/ichiju-sansai-how-to-construct-meals-like-a-japanese-centennial-7cb878366994
