#+TITLE: Wednesday, 10/28/2020
** 21:46 life of designers
[[https://readymag.com/readymag/dailyroutines/?utm_source=awwwards.com&utm_medium=paid&utm_campaign=dailyroutines&mc_cid=ce7cd9a7c7&mc_eid=538eb81695][daily routines with designers article]]
i love love love the flow and the op-1 animations!

*** becki kozel
brooklyn! founded small, independent company.
amassed a large library to look up in and research for creative inspiration
multitasking, wearing a lot of hats very quickly, is so big and can drive you!

i love the rush right before the building
learn to sketch by hand! incorporate hand-sewn elements and documentation
focus: good music, get into groove, removce all distractions
take a break once an hour to take time out in the apartment

*** pavel
fight the blank page!
- start addign something - anything
- read the materials again and again to continue to clarify adn constrain your product
- work in darkness!
- designing icons and screenshots is incredibly difficult
travel periodically and systematically for creativity
*** miha motra
always read up on related things, make a brief, etc
finish little bits of work gradually rather than the whole thing at once
draw by hand, finalize the colors
*** anton repponen
estonia architecture -> design
discuss with the customer for a long long time then begin the research process
no burnouts! you can't burn out when you have more experienced and have faced the difficult problems before.
keep hacking at it
no eyar of a natural cycle
*** anna something
morning routines! find options that will boost your day
sports? workouts? don't do things that consume a lot of your willpower so early.
digital or analog?

free write! this helps you begin to understand and reason with yourself,
writing about your experiences and recording them will help you understand yourself -- storytelling and psychoanalysis. what is SWAT? five whys?
story of endles problems or an amazing journey

health goth health goth health goth
https://healthgoth.popkern.co/

developing an eye is so important
admire work /and/ determine a systematic vacuum
do not fall victim to thinking the world shares the same cultural values you do

*** ideas
- do not consume new content except wehn planned
- set a time interval for research -- only this much time to accomplish or finish somethign
- need some way to collect all references in one place and search through them
** 23:36 intake too much
it's time to cut things off and work internally.

time to work
hard
