#+TITLE: Wednesday, 09/23/2020
** 18:26 notes on social
*** tik tok
https://blakeir.com/Alex-Zhu-TikTok-4631f80fdcc4423a845e145e807d8e2b
i want to build a startup; a platform for networking and a platform for users
i watn to build a personal data management service first; this is our initial value
after this, it expands in a community

building an influencer communtiy is a lot like discovering new land
- build centralized economy, favoring few people
- they become role models for the country
- create the dream and demonstrate *why* they succeeded
- focus on utility first; without it you won't receive initial users
- give all users satisfaction in creating content; make a 'middle class'

the ads business is an excellent business
virtual gifting is excellent way of monetizing
the key power is the influence over culture; need monetization ecosystem
to reward creators and influencers

musical.ly uses music as a raw material, not the end product - not competing
powerful distribution network
*** stripe
venture capital! none are part of the same company but portfolio can share aspects
valuations are healthy, serial acquirers do so at a certain evaluation
Danaher lean acquisition strategy doesn't apply to tech
huge amount of expertise in the firm that you can unlock when they invest in you!
think about SVs best practices and getting them out to millions of internet businesses

stripe success -- early decision to start form the ideal api and work backwards
things will shift! a majority of commerce will become internet enabled
people spend lots of time thinking about first order effects of tech changes

returns to writing well are really high
asynchronous communication is so so so important! do not underemphasize
crism written communication

speak up to the reader - don't dumb things down!

  it's much easier to get fast work done than a small team than a large team

  'lean' methodology - when launching new things, start small and make them
  earn their way

  most markets are not like the US

  bottoms up and top down businesses; visa integrations vs top down
  strategy of the company vs the technological issue driving systemic change

  startup company needsi

  the way we build adn deploy software now is now where it will be
  we have regressed - harder to build a consumer startup! have to build platforms!
  standards are higher for what you have to show!

  capital has moved to intellectual capital and intangible capital
  the best is that software that has been developed in house by the business

  it's really easy to think about tangible capital, but terribly hard to value the intangible!
  hard to think about hte profitability of the business in its knowledge (how much is investment in future systems?)
  have to split out lines of business and categorize them

  how much are you investing in a long lived technological advantage? how much does it cost to operate the business?
  it is so hard to measure the outputs of software engineering

**** book recs
- the outsiders : case study of CEOS who are great capital allocators
  amazon probably most efficient allocators
  allocating scarce resources is the name of the game internally and externally
  the outcome for the company really depends on how good of a job they do!
  placing resources towards the rate of highest future return influences all businesses
- Softwar - like a letter to the editor
- Cable Cowboy - the rise of the mobile cable business; rhymes with tech shifts we see
  stripe is a part of all of this!
**** advice
be willing to go down the rabbit hole.
all of the institutions want to bring you on the normal track
allow people to dive further down the rabbit holes
it is so important to learn, learn, learn. to go deep
