#+TITLE: Tuesday, 10/13/2020
** 22:12 setting goals!
- what sacrifices do you need to tkae in order to achieve your goal?
  as everything has an opportunity cost, you have to give up things to pursue others.
  weigh the costs and benefits of your decisions
- rather than focusing on just goal setting, focus on *designing* a good system
- progress should always be recorded. makes you feel good
- only through measurement can you really track if you've been getting better
  this applies to everything; mental and physical
tool: https://motion.hoanhan.co/goals/hoanhan/
** tynan: time scale
we are dictated by our principles and the lenses through which we view the world
by recognizing - then changing - these lenses, we can effect positive change,
but when this positive change really matters can change a lot

it's clear that we all /want/ to make decisions that are good for us, but what matters is the
time scale; drug addicts optimize for the immediate rush, while those who save forever optimize for infinity - for things they want to have eventually in their lives, so they are worried about doing things in the near future

optimize for 5 - 10 years in the future instead! these things seem a bit silly but they will pay off.
make a list of things you'd like to accomplish and continue to track it.

when you optimize for further out, you'll have much more leverage and you'll be able to create much bigger change in that long term. You're trading some enjoyment in the next few years for a much better rest of your life, and you'll have had control over the rest of your life in a better fashion!

whenever you're making a decision, ask yourself if it'll be something you'll be glad you'd have done in 5 to 10 years. your physical and mental health now are obviously the most important, but other things should be considered as well

your time scale does and will become part of who you are -- make it a core part of the decision making
** 22:29 no free lunch
always keep in mind the no free lunch theorem:
all optimization strategies, as long as they're dedicated,
are considered equal averaged across all mathematical problems
