#+TITLE: Tuesday, 11/17/2020
** 00:19 living anywhere
familiarity is misunderstood; it's worth spending /time/ to improve the small things in your world, whether these are the social spaces of your local environment or the topology of your discord server or what have you. the pleasure of belonging is often undervalued relative to the pleasure of adventure -- and I don't think the pleasure of familiarity can be romanticized enough.

cultivating community is one of the most valuable things we can do as members of the spaces we occupy, and is something we should learn to appreciate -- without our active effort, none of the constants or assumptions we have about our lives are absolutely guaranteed.

living close to your birthplace, or in the same environment you were before, may not be so bad -- our digital lives, after all, can exist entirely independent of our physical relationships, and we often put ourselves in boxes
living in a single place allows one to /accumulate/ - materials, tools, and knowledge - while holding other aspects of life as constant and can be

(I see this as flawed: there is no stopping change and progress over the years, and we must adapt to it -- part of how we learn to adapt and develop is by exposing ourselves to new environments and social situations)

determine what you value first and, if necessary, shoot off to the city later. the city seems to have a bit of a grip on a person, and living in the country seems to liberate us from it.

we should really try to understand ourselves -- and cultivating familiarity is one art that's become lost in the information age. spend more time not using new tools, technologies, and innovations, but rather curating what we have -- and keeping as much as we can constant.

cafes: concrete strategy to meet others and improve familiarity, to feel like you belong in a certain place at a certain time. get to know your environment first, then start to develop a relationship with the world and the people inside it.
"The princess kisses a frog, and creates the prince."
** 03:19 hedonism
I find myself going through hedonistic cycles. Friday night I spend in a fervor of friends, good food, and eventual exhaustion, waking up at 2AM to find my phone near my bed and a rabid, endless rush of political tweets. I find myself jumping to use other services and tools within /minutes/ or my using electronics -- the motivation to avoid these must come from within.

Just jumped back from social media again. Making a conscious effort to turn these outlets into 'educational' platforms -- there are lots of valuable voices in academia, sure, but this just won't happen. Rather, I need to pare down, focus and simplify my life.

I was a bit touched by [[https://ava.substack.com/p/are-words-good-enough?token=eyJ1c2VyX2lkIjoxOTQ4ODUwNiwicG9zdF9pZCI6MTg5NDc0NjEsIl8iOiJRNzhKbSIsImlhdCI6MTYwNTU4MTA2NiwiZXhwIjoxNjA1NTg0NjY2LCJpc3MiOiJwdWItMjM0MTciLCJzdWIiOiJwb3N0LXJlYWN0aW9uIn0.AttlXYwLzFKeEdvpshg11pSw37viAK4yPtfGFnIviPc][Ava's new Substack article]] and two ideas in particular: one, that we never quite see eye to eye with one another, and yet another about our perception of beauty and content. This is a theme of many of her articles -- in recent memory, one written about the importance of maintainence to life rather than placing a focus on progress, and I often feel that this is what seems to be holding me back; yet I'm quick to hide my own regressions.

I'm captivated by The Power of Now, though I haven't quite read it; I'm so used to the constant waiting for the buzzing of notifications, of a refreshed twitter feed, to even consider the anecdote of sitting on a bus and watching life pass you by, and being happy for it. No matter how I feel, proper discipling will always come from within; and with it will come greater control over my interests, my life, and my long-term goals.

In this vein, learning to get in touch with the language of others is such a valuable skill to develop -- I believe it's in me somewhere, down in those shells of ages twenty nineteen eighteen seventeen sixteen like nesting dolls of years covering up prior personalities and identities, perhaps to protect me, perhaps to protect them. It is so easy to forget the power of this communication: the forgotten dialect of the heart does this justice.

I am human, nothing human is alien to me.
I am human, nothing human is alien to me.
I am human, nothing human is alien to me.
