#+TITLE: Monday, 12/07/2020
** 07:49 silly ideas
see aingle image at a time and tag it with multiple tags. nice ui shows you existing tags, more effort to add new one but still possible
images / video / text you've collected can be turned into a static site at a specific url and hosted easily

interview ppl!!! all the time. ask good questions. i loved being interviewed because it made me think and i want to do the same for others and do it /quickly/.
** 07:59 time cube
https://timecube.2enp.com/
** 8:00 more sweden
Rittersvik
Drottingholm palace
https://www.reddit.com/r/stockholm/comments/j0chz7/h%C3%B6stk%C3%A4nsla_i_h%C3%A4sselby/
https://www.reddit.com/r/stockholm/comments/j0vsfm/royal_palace_stockholm/ oml
https://www.reddit.com/r/stockholm/comments/jrhwbr/drottningholm_palace/ yo yo yo
[[https://www.reddit.com/r/stockholm/comments/j9d4uu/inside_the_brunkebergs_tunnel_a_231_meters_long/][brunkebergs tunnel]]
the woodland cemetary garden?
** 17:44 gwern
very cool quantified self work, backing up external tech, and other resources.
https://www.gwern.net/docs/design/2018-10-09-heck-structuraltypography.html
some backed up typography notes he has
love the independent researcher + live frugally idea
https://www.amazon.com/Case-against-Education-System-Waste/dp/0691174652 the case against education, book

[[https://srconstantin.wordpress.com/][governance; asking permission]]
[[https://webcitation.org/6DuYcqyQ3][the epistemic state]]
