#+TITLE: Tuesday, 01/05/2021
** 00:06 writing
is best when you leave most things unsaid -- as much as you can -- but produce a product that communicates your words regardless. The informed reader should be able to pick up all of the nuance and reference within the work, but it should be perfectly comprehensible and enjoyable without.
** 13:29 living and writing
"I would like to understand things better, but I don't want to understand them perfectly." - Douglas Hofstadter
https://blog.beeminder.com/ -- give beeminderr your credit card, and they'll charge it every time you fail to meet your goal. in defining a quantifiable metric for beeminder to track, you define a metric that you yourself can monitor and keep track of. It's a brilliant way to turn your intrinsic motivation extrinsic -- and serious.

the founder of sia's an interesting guy - maybe more daily journaling would be valuable. i'd be able to keep a lot more in mind. or am i already remembering the most important things?
i have to continue to remember that ideas - and understanding - are in and of themselves incredibly cheap. it's having the determination and consistency to execute day after day that makes for valuable work. 
reading godel, escher, bach might be valuable.
execute on more ideas -- you won't be able to iterate on them if you do not work with others!
hofstadler might be worth reading...

rust seems like the key to accessing a lot of the innovation i'm interested in, up and down the stack. haskell and ml are still incredibly intriguing, but their communities feel masturbatory by comparison
first, improve your c skills. its been the root of the programming language world for 30 years or more.

lua game development through pico8 seems fun
** 20:00 it's a community garden, not a blog
walled gardens - with closed information and writing that are not accessible - are probably bad; they're used to obscure individual or corporate notes. the 'blog' sucks information into a particular format and places harsh limitations on the organization of content. don't do that! viewing writing as a content marketing strategy or a way to develop a personal brand is valid, but in the end it deters from writing articles we want to write or posting things we want to post to fit a particular image -- this inhibits personal expression and keeps you from recording ideas -- just build a second brain

https://llllllll.co/t/on-singularity-creation-repair-and-commodity/39710
thoughts on the unique breaking article; timeless ways of building.

commoditizing removes the creator from the equation; things become dispersonal. i didn't at all connect with food until i was making it, and making it completely. it is often better to do things yourself, or to use those of friends -- commiditizing the wrong things will lead to the detachment from our belongings that is so toxic about the standard 'capitalist' way of living, dispensible and commoditized items that carry no emotional weight.

revisit and explore the linked parts of this article: Alexander's timeless way of building, and alienation, marvelous pursuits and the new nomadic sciences.

the marvelous pursuit is born of the desire to create playful complexity where these is simplistic convenience; it can't be commodified and is a rejection of such commodities because it cannot be purchased.

marvelous pursuits are attempts to make the environment one's own by ascribing values to the space. the marvelous pursuer is not an engineer, because the marvels are not in and of themsevles providing value; they are creative tokens that we cannot necessarily commodify

https://campuspress.yale.edu/modernismlab/the-work-of-art-in-the-age-of-mechanical-reproduction/

https://en.wikipedia.org/wiki/The_Oregon_Experiment 
wendell berrt seems a worthwhile read as well

https://tomcritchlow.com/2019/02/17/building-digital-garden/
digital streams, campfires and gardens; these concepts are not unique, but it's important
to divide different levels fo information 'flow' into different parts of one's information

blogs without publish buttons; constantly updated and constantly growing
a lot of people seem to use are.na
https://notes.busterbenson.com/
https://sive.rs/dj -- daily journal from derek sivers.
- use plain text
- open the diary as a nightly routine; clear everything out to reset. this is also something you can look back on, the daily facts of life'
  https://www.brendanschlagel.com/2017/11/05/canonize-creating-personal-canon-template/ a neat way to navigate sites, personal canons, gardens, wikis or what have you. look to this to more information, please![[file:../pages/wiki.org][Wiki]] 

  http://worrydream.com/#!/quotes invaluable quotes[[file:../pages/wiki.org][Wiki]] 

  
I have a theory, which has not let me down so far, that there is an inverse relationship between imagination and money. Because the more money and technology that is available to [create] a work, the less imagination there will be in it.

  Alan Moore: interview on mtv.com
http://particleblog.blogspot.com/2006/07/stories-structure-abstraction-and.html
stories, video games and interactivity; stories cannot really be interactive; for then you would fault the story. robustness and elegance are the most important factors of games, and they directly oppose the complication that leaves us enamored with good stories

http://daywreckers.com/
a list of links without context; cataloguing links saved that he finds interesting[[file:../pages/wiki.org][Wiki]]


What is above all needed is to let the meaning choose the word, and not the other way around. In prose, the worst thing one can do with words is surrender to them. When you think of a concrete object, you think wordlessly, and then, if you want to describe the thing you have been visualising you probably hunt about until you find the exact words that seem to fit it. When you think of something abstract you are more inclined to use words from the start, and unless you make a conscious effort to prevent it, the existing dialect will come rushing in and do the job for you, at the expense of blurring or even changing your meaning. Probably it is better to put off using words as long as possible and get one's meaning as clear as one can through pictures and sensations. Afterward one can choose -- not simply accept -- the phrases that will best cover the meaning, and then switch round and decide what impressions one's words are likely to make on another person.

George Orwell: Politics and the English Language

In my life as an architect, I find that the single thing which inhibits young professionals, new students most severely, is their acceptance of standards that are too low. If I ask a student whether her design is as good as Chartres, she often smiles tolerantly at me as if to say, "Of course not, that isn't what I am trying to do.... I could never do that."

Then, I express my disagreement, and tell her: "That standard must be our standard. If you are going to be a builder, no other standard is worthwhile. That is what I expect of myself in my own buildings, and it is what I expect of my students." Gradually, I show the students that they have a right to ask this of themselves, and must ask this of themselves. Once that level of standard is in their minds, they will be able to figure out, for themselves, how to do better, how to make something that is as profound as that.

Christopher Alexander: foreword to Richard Gabriel's "Patterns Of Software"

noam chomsky: manufacturing consent.

[The] point is not that innovation attracts groups but that innovation is found in groups: that it tends to arise out of social interaction -- conversation, validation, the intimacy of proximity, and the look in your listener's eye that tells you you're onto something. ...

When [Erasmus Darwin, James Watt, Joseph Priestley, etc.] were not meeting, they were writing to each other with words of encouragement or advice or excitement. This was truly -- in a phrase that is invariably and unthinkingly used in the pejorative -- a mutual-admiration society. ...

What were they doing? Darwin, in a lovely phrase, called it "philosophical laughing," which was his way of saying that those who depart from cultural or intellectual consensus need people to walk beside them and laugh with them to give them confidence. ...

We divide [groups] into cults and clubs, and dismiss the former for their insularity and the latter for their banality. The cult is the place where, cut off from your peers, you become crazy. The club is the place where, surrounded by your peers, you become boring. Yet if you can combine the best of those two -- the right kind of insularity with the right kind of homogeneity -- you create an environment both safe enough and stimulating enough to make great thoughts possible.

Malcolm Gladwell: Group Think

the royal family gives people something to pay attention to and gossip about while the politicians can get the real work done behind the scenes


come back to these quotes; they will help you in the future.

** ava's writing today
I learned nothing except the way a sentence should sound in your head when you’re reading it over and again, trying to make it last longer. 
https://ava.substack.com/p/a-few-book-recommendations?token=eyJ1c2VyX2lkIjoxMDY5MzAyMSwicG9zdF9pZCI6MzAwODE5MTYsIl8iOiJhNFBiYiIsImlhdCI6MTYwOTgzMjU1NiwiZXhwIjoxNjA5ODM2MTU2LCJpc3MiOiJwdWItMjM0MTciLCJzdWIiOiJwb3N0LXJlYWN0aW9uIn0.gg7syfHNyBU0acrY7o8QeisjVoUnvhZC3xYdehkjXPAhttps://ava.substack.com/p/a-few-book-recommendations?token=eyJ1c2VyX2lkIjoxMDY5MzAyMSwicG9zdF9pZCI6MzAwODE5MTYsIl8iOiJhNFBiYiIsImlhdCI6MTYwOTgzMjU1NiwiZXhwIjoxNjA5ODM2MTU2LCJpc3MiOiJwdWItMjM0MTciLCJzdWIiOiJwb3N0LXJlYWN0aW9uIn0.gg7syfHNyBU0acrY7o8QeisjVoUnvhZC3xYdehkjXPA

buying lots of clothes; take your mind off and help you focus. do you ever worry that you're not interesting?

Pick one: 1) Having enough money and time and focus to buy all the hardcover books you want and read them 2) Lying in bed beside someone you love.

Some good editing advice I read: imagine that your smartest ex, the one that you resent the most, is the person who’s criticizing your writing.

My favorite books this year:[[file:../pages/books.org][Books]] 
 
Fiction
Problems by Jade Sharma
Mariette in Ecstasy by Ron Hansen
Women by Chloe Caldwell
How to Save Your Life by Erica Jong
Luster by Raven Leilani
Sputnik Sweetheart by Haruki Murakami
Mating by Norman Rush
The Friend by Sigrid Nunez

Poetry
Stag’s Leap by Sharon Olds
Summer Snow by Robert Hass

Memoir
Stray by Stephanie Danler
Abandon Me by Melissa Febos
Uncanny Valley by Anna Weiner
Wild Game by Adrienna Brodeur
The Undying by Anne Boyer

Nonfiction
Psychopolitics by Byung Chul-Han
The Power Notebooks by Katie Roiphe
Gravity and Grace by Simone Weil
Post-Capitalist Desire by Mark Fisher
Heroines by Kate Zambreno


how do you read so much so fast?
*** on redoing things
https://ava.substack.com/p/on-redoing-things?token=eyJ1c2VyX2lkIjoxMDY5MzAyMSwicG9zdF9pZCI6MjIwMjIxNjcsIl8iOiJhNFBiYiIsImlhdCI6MTYwOTgzNDI4NCwiZXhwIjoxNjA5ODM3ODg0LCJpc3MiOiJwdWItMjM0MTciLCJzdWIiOiJwb3N0LXJlYWN0aW9uIn0.abRBstb5exotzWD8ggf_zM0pRfLFqMSPt6Xk_xRoqsU

the secret to fine things is in remaking them.
the third draft becomes easier and it makes one feel alive, somehow

john keeble: the first page of anything should contain the concerns of the entire work.
writing is memory but memory is also exorcism; like practice, it's okay to continue to mess up and let it out until it is done.
