#+TITLE: Wednesday, 01/27/2021
** 21:56 Internet Oddities
*** Usernames
Someone I had several courses with in high school recently joined instagram and continues to be recommended to me; their chosen username is https://www.instagram.com/akshaymusic101gmail.com6/.

I love it. The brazen declaration of 'music 101', the unashamed declaration of their email address - in the username no less! - and the addition of '6' to the end even though the username is available without the suffix are all fascinating to me.

This runs counter to all of the assumptions I had about what usernames should be - short, sweet, and poetic at best, informative if it makes sense - but this is none of those. It's long, brazen, littered with characters, and clearly advertises someone's character and their hobby. There's no question of how to contact them; their email is available!

The '6' is incredible, too; it's a complete subversion of the popular convention to postfix the username with numbers. Typically people will, upon trying their preferred username (usually some reiteration of their real name) will postfix it with a string of numbers that hold some meaning to them. Some add 99 or 1999 to suggest their birth year, while others choose numbers that are important to them such as their house number or a lucky number.

Still others picked up on this and began using these numbers without such a name conflict, picking up on the stylistic choice as a trend of some sort. This is one of those circumstances, but the name conflict truly doesn't exist - and the addition of the number breaks parity with the email-as-username scheme!
*** million dollar homepage
https://en.m.wikipedia.org/wiki/The_Million_Dollar_Homepage
*** kmikeym: invest in someone's personal decisions
https://kmikeym.com/
related: HumanIPO  https://humanipo.app/
