#+TITLE: Saturday, 02/13/2021
** 21:50
*** shame and guilt
[[https://ava.substack.com/p/on-shame?token=eyJ1c2VyX2lkIjoxOTQ4ODUwNiwicG9zdF9pZCI6MzIzNDA2OTksIl8iOiI3Mk5YMiIsImlhdCI6MTYxMzI1MjU5MSwiZXhwIjoxNjEzMjU2MTkxLCJpc3MiOiJwdWItMjM0MTciLCJzdWIiOiJwb3N0LXJlYWN0aW9uIn0.jLgalWhjz8PVI8G5WxPDCoikMrWMuYl9DucNy_J0MIk][src]]
"Shame is distinct from guilt because it isn’t about responsibility: it’s about feeling like the very way you are is insufficient and bad and embarrassing. If you’ve read any Brene Brown you probably already know that guilt can be adaptive and helpful, but shame is dangerous."

It's scary to keep putting yourself out there - to say the one thing that will be deemed /wrong/ - and fall into the depths of the internet's vilification of your choice of words.
*** Effort
[[https://ava.substack.com/p/effort?token=eyJ1c2VyX2lkIjoxOTQ4ODUwNiwicG9zdF9pZCI6MzI0MTIzMTEsIl8iOiI3Mk5YMiIsImlhdCI6MTYxMzI1MjU3OCwiZXhwIjoxNjEzMjU2MTc4LCJpc3MiOiJwdWItMjM0MTciLCJzdWIiOiJwb3N0LXJlYWN0aW9uIn0.U57nkPUXbGR5AoiANK5iAw4m76dtdpqGKjy2nmFxKT4][src]]
social media success off of the back of all of the money and effort towards preparing a public image
if someone is much better than you at something, they are probably trying much harder. we're underestimating how much effort they put in into what they're interested in!

why the process? the ugliness of trying and wanting and hoping and working are fascinating. sustained tenacity - and /deep work/ - are so so so valuable.

a lot of people want to /be/ but do not want to /do/ - and there is an obvious solution to this. i am incredibly ashamed of rejection and of imperfection, so i stray from trying to /do/ things, but in doing so i constantly grapple with not doing things. it's clear that my doing things would be much better than not doing so. if the writer isn't having fun then the reader doesn't either.  if you love the process, then your work will be better enjoyed - because it is done out of love.

two types of people: people who are ashamed of something and choose not to do it, and people who choose to do it anyway and just hide it. it is so much harder to be the latter - but being ugly is 'the price that unlocks everything beautiful in the world'.

bury your insecurity by making things and making them so well that you look good.
*** angel investments and startups as a new grad
[[https://medium.com/@gefen/how-i-raised-angel-investments-for-a-pre-launch-startup-using-just-twitter-as-a-new-grad-8db467131af7][src]]
- join an accelerator! learn more about this
- look into venture funding and venture partners. these could be super useful. contrary capital seems very cool, as does the dorm room fund.
- keep studying and reaching out to others. building credibility through product helps with this
- apply to tons of hackathons and conferences to get travel reimbursed!
- start or join a small, supportive community
- advantageous twitter work:
  - network, network, network. personally
  - stick to your own voice and identity
  - cold message everyone who inspires you!
  - build cool things : )
*** thinking, better
[[https://www.lesswrong.com/posts/cumc876woKaZLmQs5/lessons-i-ve-learned-from-autodidacting][lessons learned from self teaching]]
- use spaced repetition system and review ever yday without fail
- learn math rigorously! work hard! start learning math - hard! drill on what to remember.
  lots of good anki tips in this article.
- read several textbooks concurrently. this allows the brain to cement the topics you're learning
  at the same time so that everything builds and cements concurrently. blurry to sharp approach rather than progressive one
- as you read more you learn what's most important. don't strive to go front to back
- read easier textbooks! don't struggle for fun!
- be comfortable learning approximate models rather than focusing on learning with /depth/ right away
  
*** taboo
https://www.lesswrong.com/posts/M8cEyKmpcbYzC2Lv5/exercise-taboo-should
- virtue theory: people who eat virtuous foods will be rewarded, and sinners will be punished
- this could actually be true if you look at the paper lol what
