#+setupfile:./hugo_setup.org
#+hugo_slug: os
#+TITLE: Operating Systems

Operating systems run your computer!

There are lots of innovative OS projects but only a few are really used.

* Projects
Aside from Linux, Windows, MacOS and derivatives...
https://github.com/tomaka/redshirt
https://gitlab.redox-os.org/redox-os/redox is a Rust operating system with a microkernel-based design.
https://github.com/urbit/urbit is an operating system and framework that claims to be entirely functional
https://github.com/toddsharpe/MetalOS all by one guy!
https://github.com/mntmn/interim the interim os, written to accompany mntmn's custom hardware
https://github.com/mchlmmc/CirnOS os to use arduino on raspi (lmao)
https://github.com/demikernel/demikernel interesting approach to architecture
https://github.com/cleverca22/not-os operating system generator based on nixos
https://github.com/vygr/ChrysaLisp lisp machine!
TempleOS (racist)

https://blog.quarkslab.com/playing-around-with-the-fuchsia-operating-system.html
fuscia operating system sounds cool and fun, but ig we will see what happens
if it becomes more popular. this blog could also be useful as this person
seems knowledgeable

https://www.paritybit.ca/blog/my-beginnings-with-gentoo
https://mirror.dernuntius.de/projects/wii-linux/ -- linux on the wii ???
https://www.qubes-os.org/intro/
https://www.whonix.org/
lineageos vs /e/
https://wiki.lineageos.org/devices/starlte/install
https://news.ycombinator.com/item?id=23100713

* Pi
[[https://wiki.xxiivv.com/site/raspberry.html][wow!]]
[[https://notmuchmail.org/frontends/][notmuch clients]]
[[http://willcrichton.net/notes/][type level programming]]
[[https://wiki.xxiivv.com/site/discourse.html][on discourse.]]
[[https://en.m.wikipedia.org/wiki/Ricci_calculus][rules and indices for tensor and tensor fields!]]
[[https://homelabos.com/][self hosting at home.]]
[[https://alot.readthedocs.io/en/latest/][alot tutorial]]
[[https://www.youtube.com/watch?v=kgVz4-SEhbE&app=desktop][clustering with the raspi]]

https://raspberrypi.stackexchange.com/questions/86/how-can-i-run-the-pi-on-solar-power
pi on solar power
https://100r.co/site/raspberry_pi.html
https://www.lifehacker.com.au/2012/12/make-a-raspberry-pi-solar-powered-ftp-server/
https://www.instructables.com/id/Solar-Powered-Raspberry-Pi/

[[https://bartoszmilewski.com/2020/05/27/guitar-decomposed-5-mutating-the-third/][guitar in haskell]]
[[https://git.sr.ht/~ft/9pro][tools for sourcehut!]]
[[https://link.springer.com/book/10.1007/978-1-4302-5990-9?utm_source=twitter&utm_medium=social&utm_content=organic&utm_campaign=BBKK_1_DL01_GL_twitterorganic&sf234521345=1][book by rahul khanna]]
[[https://obsidian.md/][obsidian md knowledge base]]

https://electro.pizza/2020/05/selfhosting-cloudshell2/ NAS self host with
documentation

https://aperiodical.com/2020/06/review-immersive-linear-algebra/ review for
linalg
https://blog.quarkslab.com/playing-around-with-the-fuchsia-operating-system.html
fuscia operating system sounds cool and fun, but ig we will see what happens
if it becomes more popular. this blog could also be useful as this person
seems knowledgeable
* Mobile
https://www.youtube.com/watch?v=WSNGK9gmdpg&app=desktop intro to privacy on
android

https://www.qubes-os.org/intro/ security os with microkernels that runs
everything in vms
https://www.whonix.org/ anonymous linux desktop or somethign
https://wiki.lineageos.org/devices/starlte/install lineageos for the galaxy s9
https://www.reddit.com/r/degoogle/comments/gu2kk9/lineageos_vs_e_vs_alternatives/

https://github.com/redkyn software for teaching programming
