#+setupfile:./hugo_setup.org
#+hugo_slug: web_design
#+title: Web Design
- tags :: [[file:design.org][Design]],[[file:fonts.org][ Fonts]]
* Philosophy
:PROPERTIES:
:ID:       84fdf4e2-8050-40e8-bd93-502d6e260dfa
:END:
Websites should be minimal.
There is no reason to download five megabytes of Javascript to communicate
my hiring credentials. I shouldn't have to wade through frameworks and dark
patterns to read a blog post!

I am taking a reductionist approach to web design by:

- Limiting the number of lines of Javascript.
  Javascript consumes unnecessary resources and can distract from information
  presented; as such, Javascript should serve only to enhance current content.

- Limiting the number of colors on the site, shifting focus to central components.

- Reducing the overall complexity of the project.
  You can only truly understand a machine if you can remove every piece
  you don't need. If every piece is necessary for communicating the information,
  it's all the end user should need to see.

Aesthetics aside, focusing on minimizing web development allows the millions of
people worldwide with slow connections to access resources and information.
Using a simple subset of CSS and Javascript, too, enables older browsers and
hardware to sufficiently load websites.

The web doesn't have to be so hostile or expensive to run.
Focus on boiling it down to its essentials.

* Inspiration
:PROPERTIES:
:ID:       3f7f93ab-9bc7-4322-9f3e-15d8efa5b949
:END:
- [[http://mikhailkhoury.com/][Mikhail Khoury's website]], one I stumbled upon only because he shares
  a last name with Northeastern's Computer Science college, has
  an astoundingly minimal yet well-designed site. It's easy to navigate
  and has no distractions from the site's objective.

- [[https://100r.co][100 Rabbits]] are a creative duo comprised of Rekka Bellum and
  [[https://xxiivv.com/][Devine Lu Linvega]]; they've inspired me to move towards using
  minimal, accessible tooling, and have a fantastic design language
  present throughout all of their work. [[file:../people/100_rabbits.org][100 Rabbits]]

* Resources
:PROPERTIES:
:ID:       919f9e4b-ec6f-404a-9f5c-ee51aa3605d3
:END:
- [[http://clrs.cc/][clrs.cc]] :: communicative colors for browser prototyping.
