#+setupfile:./hugo_setup.org
#+hugo_slug: vim
#+title: Vim

Vim is a text editor with an easily configurable extension langauge.
It's most frequently used as a [[file:../concepts/terminal_ui.org][Terminal UI]] program,
but also has a graphical application distribution (Gvim).

Unfortunately, due to the inflexibility of its programming environment,
it's not as flexible a tool as[[file:emacs.org][ Emacs]].

However, it has a first-class editor-based extension language
that's written to prioritize text processing and configuration.
Its extensive, literate keybindings that have made their way
into every popular text editor as well as many other applications.

It's one of best text-editing tools in the Unix ecosystem,
and Vim users often have a library of cli and tui programs that they use
in conjunction with Vim to facilitate a desktop ecosystem without a GUI.

Vim is often preinstalled on Unix systems. If it's unavailable,
such systems will likely still have vi (or busybox vi), so taking the time
to learn vim keybindings is worthwhile for their flexibility throuhgout
programming environments.
