#+setupfile:./hugo_setup.org
#+hugo_slug: books
#+TITLE: Books

Books I've read and would like to read.

hr giger
zdzislaw beksinski
* shows
BBC: In Our Time. on famous math works
wayne, emerson student film
** merveilles
rozencrantz guildenstern
solaris
wristcutter: a love story
the rules of attaction
faust
my dinner with andre
sedmikrasky
valerie a tyden divu
na srebrnym globie
the taste of tea
cat soup
black moon
(see xxiivv wiki for more)
* ETC
beyond good and evil: friedrich nietzsche
3 body problem
sapiens: yuval noah harari
Skarholmen
karl jung?

the machineries of joy: Ray Bradbury
[[https://en.m.wikipedia.org/wiki/Elephantmen][Elephantmen]]
[[https://m.barnesandnoble.com/w/the-body-keeps-the-score-bessel-van-der-kolk-md/1117229987][the body keeps the score: child trauma and adult health]]
black hat python: python for pen testers
https://www.amazon.com/Breaking-Habit-Being-Yourself-Create/dp/1401938094
https://www.amazon.com/10-Happier-Self-Help-Actually-Works/dp/0062265423
https://en.wikipedia.org/wiki/The_Coddling_of_the_American_Mind
https://en.wikipedia.org/wiki/Homotopy_type_theory
https://www.amazon.com/Algorithms-Aided-Design-Parametric-strategies-Grasshopper/dp/8895315308
https://www.amazon.com/Culture-Map-Breaking-Invisible-Boundaries/dp/1610392507
https://en.m.wikipedia.org/wiki/Manufacturing_Consent
https://www.amazon.com/Elements-Finite-Theoretical-Computer-Science/dp/3540212027
https://www.amazon.com/Fooled-Randomness-Hidden-Markets-Incerto/dp/0812975219
https://www.amazon.com/Self-Made-Man-Womans-Year-Disguised/dp/0143038702
https://mitpress.mit.edu/books/semantics-engineering-plt-redex
https://www.goodreads.com/book/show/20702054-ricky-rouse-has-a-gun
https://www.goodreads.com/book/show/13058637-subliminal
https://mitpress.mit.edu/books/hacking-life
https://www.amazon.com/dp/1788735013?tag=duckduckgo-fpas-20&linkCode=osi&th=1&psc=1
https://www.amazon.com/One-Mans-Terrorist-Political-History/dp/1786636883
https://www.amazon.com/Its-Not-How-Good-Want/dp/0714843377
https://www.goodreads.com/book/show/41057294-normal-people
https://www.goodreads.com/book/show/20518872-the-three-body-problem
https://en.m.wikipedia.org/wiki/Schild%27s_Ladder
https://en.m.wikipedia.org/wiki/Stories_of_Your_Life_and_Others
https://en.m.wikipedia.org/wiki/Flatland
https://www.goodreads.com/book/show/29845449-the-weird-and-the-eerie
https://www.amazon.com/Invisible-Planets-Contemporary-Chinese-Translation/dp/0765384191
https://www.amazon.com/Compiling-Continuations-Andrew-W-Appel/dp/052103311X
https://en.m.wikipedia.org/wiki/The_Tao_of_Pooh
https://www.amazon.com/Three-Dimensional-Imaging-Techniques-Takanori-Okoshi/dp/0982225148
https://www.amazon.com/dp/1556154844?tag=duckduckgo-fpas-20&linkCode=osi&th=1&psc=1
https://en.m.wikipedia.org/wiki/One_Hundred_Years_of_Solitude
https://www.amazon.com/Pattern-Recognition-Learning-Information-Statistics/dp/0387310738
https://news.ycombinator.com/item?id=23151144
https://www.reddit.com/r/compsci/comments/g37h4c/what_are_your_favorite_computer_science_books/
https://www.cis.upenn.edu/%7Ebcpierce/tapl/
http://pages.cs.wisc.edu/%7Eremzi/OSTEP/ classic os book
https://www.amazon.com/Clean-Architecture-Craftsmans-Software-Structure/dp/0134494164
https://www.info.ucl.ac.be/%7Epvr/book.html
https://www.oreilly.com/library/view/applying-uml-and/0131489062/
https://www.goodreads.com/book/show/2333956.The_Annotated_Turing?ac=1&from_search=true&qid=6DmPQiMHk9&rank=1
https://www.goodreads.com/book/show/166195.Modern_Operating_Systems?ac=1&from_search=true&qid=95BaFJ8hmZ&rank=1
https://www.amazon.com/Pragmatic-Programmer-Journeyman-Master/dp/020161622X
https://eloquentjavascript.net/ writing javascript good

[[https://www.amazon.com/dp/1099819776?tag=duckduckgo-fpas-20&linkCode=osi&th=1&psc=1][book on how doom was developed, looks cool too!]]

https://en.wikipedia.org/wiki/Adventures_in_the_Screen_Trade
https://en.wikipedia.org/wiki/No_Logo
[[https://www.amazon.com/Working-Public-Making-Maintenance-Software/dp/0578675862][working in public: maintaining open source software]]
realm of racket ????
https://en.wikipedia.org/wiki/The_Three-Body_Problem_(novel)

* books
https://en.m.wikipedia.org/wiki/Words_of_Radiance
https://www.amazon.com/Dark-Matter-Novel-Blake-Crouch/dp/1101904240
https://en.m.wikipedia.org/wiki/Range:_Why_Generalists_Triumph_in_a_Specialized_World
https://www.powells.com/book/little-typer-9780262536431
https://blog.rogs.me/2020/05/de-google-my-blog-how-to-blog-in-2020-without-google/
de google the blog

code as a creative medium :: MIT book
https://en.m.wikipedia.org/wiki/Literate_programming -- practice literate
programming in daily life.
https://en.m.wikipedia.org/wiki/Juno_(film) movie not book i guess
[[https://m.imdb.com/title/tt0477139/][Wristcutters]]: a love story. movie

https://moviebarcode.tumblr.com/ cool looks

https://github.com/alimir1/ali/blob/master/index.md books this dude has enjoyed
* movies
i am heath ledger
https://m.imdb.com/title/tt0096256/
https://m.imdb.com/title/tt1737747/
okja
fargo
yokai watch
the 15:17 to paris
the farewell
the last black man in san francisco
ten years
full metal jacket
cowboy bebop
samurai champloo

to read:
- noise
https://www.goodreads.com/book/show/41057294-normal-people
https://www.amazon.com/gp/product/0143122231/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=0143122231&linkCode=as2&tag=ucmbread-20&linkId=XIHEULXQQPU7EGO7
http://atulgawande.com/book/being-mortal/ being mortal:: atul gawande, surgery, medicine
https://www.goodreads.com/book/show/769712.Palestine palestine: joe sacco
https://www.goodreads.com/book/show/16982.Marvels kurt busiek: marvels
https://www.goodreads.com/book/show/118944.American_Born_Chinese gene luen yang: american born chinese
https://www.goodreads.com/book/show/34072.Jimmy_Corrigan Jimmy Corrigan: the smartest kid on earth. chris ware
ghost world
https://www.goodreads.com/book/show/38333.Black_Hole charles burns: black hole
https://www.goodreads.com/book/show/6088007-neuromancer william gibson: neuromancer

https://www.goodreads.com/book/show/297627.The_League_of_Extraordinary_Gentlemen_Vol_1  the league of extraordinary gentlemen. marvel anti-heroes, but with historical figures we already believe to be the good guys. similar to alan moore's watchman evaulation of the anti hero, but sets you up with preconceived notions of his subjects
https://www.goodreads.com/book/show/96358.Batman batman the killing joke
https://www.goodreads.com/book/show/22416.Transmetropolitan_Vol_1 transmetropolitan, a journalist dragged back into the thick of it
https://en.m.wikipedia.org/wiki/Gon_(manga) manga for kids about a dinosaur navigating the world : ' )
https://myanimelist.net/manga/664/Akira akira, duh
https://en.m.wikipedia.org/wiki/Mushishi
https://myanimelist.net/manga/336/GTO gto
https://en.m.wikipedia.org/wiki/File:Berserk_vol01.jpg berserk i guess
https://www.goodreads.com/book/show/59960.Batman
https://www.goodreads.com/book/show/156534.Y Y, the last man
https://nogunslife.fandom.com/wiki/No_Guns_Life_(manga) No Guns Life
https://en.m.wikipedia.org/wiki/Dorohedoro
Biomega
Vagabond
deiter rams: the complete works. claus kemp
deiter rams' 10 principles of good design, apparently on vimeo
the work of art in the age of its technological reproducibility and other writings on media: walter benjamin
futura: the artist's monograph

- [[https://en.m.wikipedia.org/wiki/Be_Here_Now_(book)][Be Here Now]] :: Foundational LSD book
- [[https://www.goodreads.com/book/show/118288.On_Beauty_and_Being_Just][On Beauty and Being Just]] :: a work on our world's loss of focus on true beauty
- [[https://www.goodreads.com/book/show/6708.The_Power_of_Now][The Power of Now]] :: Some call Tolle a hack, others an appropriator of spiritual truths, but this seems to have genuinely valuable words and advice.
- [[https://www.tinyhabits.com/][tiny habits]] :: developing lots of small habits, emotions, etc and sticking to character. [[https://fs.blog/knowledge-project/bj-fogg/][podcast about creating lasting change]]
- [[https://en.m.wikipedia.org/wiki/The_Shock_Doctrine][The Shock Doctrine]] :: On leveraging sudden events for political gain
Tekkonkinkreet
20th century boys
Tokyo Tribes
Gantz
Battle Angel Alita
Koduko no Gourmet
blind man's bluff: untold story of american submarine espionage
neuromancer, gibson -- some of the goodreqads reviews are absolutely incredibly written, actually
superlife: on superfoods and fitness. Darin Olien
check out things by isaac asimov! incl. 'the widowers club'
contact high: a visual history of hip hop
doug dubois: my last day at seventeen
haruki murakami: men without women
mastery: george leonard
Crary: 24/7 book
Keller Easterling: Extra statecraft: the power of infrastructure pace
Marx: Capital
Kant: Critique of pure reason                                                                            
Effective Altruism
Doing Good Better: earning to give.
Personal space: Dylan Gins (@_dylangins on ig)
book: xchg rax,rax - assembly riddles
Range: david epstein. book about generalism                                                          
fuzzingbook.org 
waste tide: chen qiufan
thinking fast and slow: daniel kahneman
Exhalation: ted chiang
Flights: olga tokarczuk
outline: rachel cusk  
ice: anna kaven      
@migrant_journal issues
[[https://www.calnewport.com/books/deep-work/][deep work]]: rules for focused success
[[https://en.m.wikipedia.org/wiki/Homunculus_(manga)][homunculus]]                         
[[https://en.m.wikipedia.org/wiki/The_Flowers_of_Evil_(manga)][the flowers of evil]]               
[[https://www.goodreads.com/book/show/136744.Domu][domu: a child's dream]]            
[[https://en.m.wikipedia.org/wiki/Uzumaki][uzumaki]]                         
[[https://en.m.wikipedia.org/wiki/Ichi_the_Killer_(manga)][ichi the killer]]                
[[https://www.penguinrandomhouse.com/books/72469/only-the-paranoid-survive-by-andrew-grove/][andy grove::only the paranoid survive]] 
* favorites                          
** Blame!
an incredible navigation of dystopia in a world as a city
** Scott Pilgrim
Such a joyful adventure! Follows a kid out of college and two old to grow up as he battles his new girlfriend's evil exes and navigates regrets, living without limits and his future. Thematic exploration changes with the art style.
* others i have read
ghost in the shell -- too hard to follow, too much dialogue, not a big fan of the art style

* etc
podcast
https://www.thisamericanlife.org/523/death-and-taxes
