#+setupfile:./hugo_setup.org
#+hugo_slug: algorithms
#+title: Compilers

Compilers translate one language to another.
They're most commonly used to translate higher level languages like C to lower level languages like Assembly.

* To Review



https://o1o.ch/about/ interesting compilers work in R
- [[https://news.ycombinator.com/item?id=23175280][explore compiler ir]]
- [[https://www.reddit.com/r/Compilers/comments/bg1g2w/interesting_topics_for_study_at_university/][cool topics to study]]
  - alternative ir structures
  - gradual typing
  - different type systems! (tapl)
https://skillsmatter.com/skillscasts/14803-what-s-in-a-functional-compiler what's in a functional compiler? talk
https://dl.acm.org/doi/abs/10.1145/512927.512941 first work on verifying and structuring compilers
https://hassamuddin.com/blog/reg-alloc/ overview of register allocation
https://getpocket.com/redirect?url=https%3A%2F%2Fwww.reddit.com%2Fr%2FProgrammingLanguages%2Fcomments%2Fhvs79e%2Ftracing_jit_vs_method_jit_what_to_choose%2F tracing jit vs method jit compilation -- learn the difference!

https://groups.google.com/g/comp.arch/c/UXEi7G6WHuU/m/Z2z7fC7Xhr8J?pli=1 popcount: the NSA instruction
https://vaibhavsagar.com/blog/2019/09/08/popcount/ more on popcount
https://oswalt.dev/2020/11/anatomy-of-a-binary-executable/ cool article about whats inside a binary executable
[[https://m.youtube.com/watch?v=yP29TKmK3_o][secure compilation from amal]]

[[https://chrisseaton.com/truffleruby/basic-truffle-graphs/][truffle compiler graphs for real programming languages]]
https://www.youtube.com/watch?v=BRNxM8szTPA&list=PLJq3XDLIJkib2h2fObomdFRZrQeJg4UIW some time on v8 and wasm, from compilers guy
[[https://dl.acm.org/doi/abs/10.1145/2980983.2908106][idle time garbage collection]]
[[https://docs.google.com/document/d/10CbqmRs-i8Jy0IE3ToEP25_FD8gj2kEHvfd3N0icN3g/preview][in-place field representation]] motivation and examples
https://v8.dev/blog/react-cliff vy performance cliff in react

* HOPL
Great resource for learning about the history of programming languages research, by definition.
https://dl.acm.org/doi/10.1145/1238844.1238853
