#+setupfile:./hugo_setup.org
#+hugo_slug: entreprenuership
#+title: entreprenuership
* Jean Yang

https://blog.sigplan.org/2020/10/27/whats-the-role-of-developer-experience-in-programming-languages-research/
excellent article on assessing dev experience and getting concrete info from it

http://firstround.com/review/how-superhuman-built-an-engine-to-find-product-market-fit/#rt_u=1604934611_r4nx1o framework to make product market fit more actionable
[[https://en.wikipedia.org/wiki/Growth%E2%80%93share_matrix][Growth-share matrix]] :: A method of using a chart to help corporations organize and analyze business units and product lines.

* Caramack
tweet: from peter drucker:
"Leaders focus on doing the right thing, managers focus on doing things right"
* Drew
[[https://drewdevault.com/2020/11/20/A-few-ways-to-make-money-in-FOSS.html][advice for working in FOSS full time]]
* Minimum viable usership
https://www.reddit.com/r/dredmorbius/comments/69wk8y/the_tyranny_of_the_minimum_viable_user/
the tool should never be more complicated than the needs of the user; it should serve the single purpose it needs. consequently, complex tasks should never be more complex than the actual task at hand, nor more simple! 
* Improving work
[[https://rework.withgoogle.com/about/][inspired by Google's work]]
Skira:
- Psychological evaluations to ensure that employees feel that they are heard and supported
- Thorough manager and personal feedback
- Truly collaborative environment vs. one in which time is valued relative to one's importance in the company

https://romainaubert.com/product-marketing-resources
