#+TITLE: Federated Wiki

* Status Quo
** Wikipedia
Pros:
- Single source of truth: it's a trustworthy source. People know to get their data from here.
- Tons of information. Crowdsourcing has done the
Cons:
- Because it's a single source of truth, there are constant fights over what belongs where that are often fruitless.
- There are also strong arguments that are made for information being 'out of scope' for wikipedia and belonging to a page or site that is more domain specific.
- The organization is bloated and inneficient. They really don't need your donations.
- The servers are centralized and controlled by a single private entity with the potenial to hold data (partially - sans clever parsers) captive.
** Wikia
Pros:
- Tons of information with moderators who are experts on their domains.
- Dedicated contributors, existing communities, easy to edit.
Cons:
- Divided into lots of different wikis with no interoperability between them.
- Tons of overlap between wikis (i.e. multiple star wars and minecraft ones, among other franchises and tropes)
- Typically used for casual and hobby interests rather than professional writing and work - why?
** Personal wiki implementation
Pros:
- Super flexible.
Cons:
- Not a consistent or reliable source of information, as it's typically controlled by one person.
- Can be disorganized and things can easily become unmaintained.
** Version control managed files
Pros:
- Built-in consensus algorithm.
Cons:
- Concurrent modification hurts.

* Goals
- Decentralized: share information from many sources without being controlled by any of them
- Open: should incorporate as many sources of knowledge as possible, and individual wikis should have tons of agency.
- Easy to use: it should be incredibly easy to contribute to and communicate with some sort of central wiki.
** Information Sources
In order of priority:
1. Wikia sites (there are tons!)
2. Wikipedia
3. wiki.c2.org
4. Assorted third party wikis.
5. [perhaps] personal wikis
6. etc...
Fusing all of the Wikia sites into a single, cohesive wiki seems incredibly useful.
** Feature Ideas
- shared & enhanced pages :: fuse pages that cover similar or related topics together into one view.
- consensus :: condense and share overlapping information, reducing the amount of duplication.
- interoperable :: shift from one wiki to another easily.


* Wiki IR related decentralized wiki idea (what we were talking about in chat, but not really what is above)
 - uses wiki IR standard to link together many peoples personal wikis
 - there is an engine at the center (or several?) that crawl the wikiverse and attempt to bring together pages that are similar
   - when pages are similar (by AI?, NLP measure), suggest several types of merging
     - suggestion ways
       - as part of wiki IR cli tool display suggestions
       - make tiny website dashbaord backed by small webapp that phones to recomender engine
     - types of page merging (between peoples federated wiki)
       - link at the bottom of page to other pages with similar content (like webring)
       - transclude entire other page to bottom of your page (and vice versa, both pages in the link transclude eachother)
       - suggest that pages are merged using git-esque strategy (pull request, text diff/merge tools like mergely)
         - q: where does consenus page live? on neither page? (next to ai engines) on one page? (one of the merge requesters 'wins', one conceceds), or both (they share :))
     - goals of merging
       - reduce information duplication
       - instead of conflicts of information being resolved in backchannel of wikipedia, consensus arguments are disputed publicly through pull requests and accepted/rejected page links
       - epic and cool

* Conversation linking
  - make conversations first class primitive of wiki, so that concepts are linked to discussion in which they are conceived
  - can be as simple as citations linking to specific conversations
  - uses matrix? hard part is technical challenge of implementation

* Backlink fixing
  - move/rename pages and update backlinks
* Automatically backup videos/external sites
  - https://github.com/bibanon/tubeup
  - like gwern, to prevent linkrot
* Provide tools to make good public/private separation
  - so that people can have shareable personal wiki concepts/reference pages, while also having extremely messy private brainstorming (brainstorming=unformed,errorfull,shameless,indulgently bad, creative, risky)/exobrain wiki pages.
* Syntax that is not static/markup
  - I want a markup syntax like (move [otherpage]: " this concept deserves to be in other page, but right now i am in [firstpage] and don't want to move all the way to otherpage in emacs so im gonna write this thought in a move block: this thought")
    - and that will append that thought to the bottom of other page once i save or run tool or something (linter?)

* Smart todo aggregation system
  - dokuwiki has decent one,
  - zimwiki also has some good features (like hiding todo until certain date)
* New types of syntax
  - some syntax for assigning how sure you are of an idea, or how much you like it
     - font size???!
     - number of exclamation points vs question marks !!!
* First class support for sorting lists
  - idk how this would work but interactive sorting is underrated!!!
* Visualizers 
  - like roam/logseq/etc.
  - but if they want to use those interactively, just use them and use wiki IR to convert wiki to them
  - maybe support something simple like
* WIKI LSP
  - breadcrumbs (https://i.stack.imgur.com/wu4kP.png)
  - definition/lookup. like you can name concepts and hover for definitions?
  - autocompletion of other page names
