#+TITLE: Generative Art
https://wiki.xxiivv.com/site/methascope.html
https://wiki.xxiivv.com/site/vast.html
https://wiki.xxiivv.com/site/lard_shader.html lard shader automation
https://wiki.xxiivv.com/site/brane.html digital fabrics
[[https://github.com/hundredrabbits/Ronin][experimental graphics terminal]]
https://wiki.xxiivv.com/site/moogle.html wireframe editor
[[https://ertdfgcvb.xyz/][studio for graphic design and art]]


https://constraint.systems/ [[file:text-editors.org][Text Editors]]
[[https://etch.constraint.systems/][Etch]]
[[https://mobile.twitter.com/alexandrosM/status/1314383329894912000][Alexandros Marinos on Twitter: &quot;Machines are making beautiful things without even trying to. We ask them to make something that optimizes for our requirements, they give us something back that looks surprisingly like nature. What is going on? A Thread https://t.co/809cWhc4ft&quot; / Twitter]]
[[https://futuristan.io][index | futuristan.io :: contemporary and digital art]]
[[https://hex.constraint.systems/][Hex]]
[[https://constraint.systems/mobile/][Constraint Systems]]
[[https://github.com/cloudhead/rx][pixel editor]]
https://en.m.wikipedia.org/wiki/Gray_code


http://subject.space/  lots of cool  projects motivated by space, maps, and tracking data around the world
https://blog.raeez.com/genesis/
https://iko.soy/dotrix drawing with vectors by touching!

https://drawabox.com/ learn to draw by starting a box!
 [[https://github.com/itsrainingmani/lsys][itsrainingmani/lsys: L-Systems: Interactive Fractal Generator]]
 [[https://github.com/urbit/sigil-js][urbit/sigil-js: ~4.2 billion default profile pics]]
https://nelari.us/ generate 3d buildings using node graphs,
also has generative art [[file:raytracing.org][Raytracing]] and is a[[file:blogs.org][Blogs]]

https://news.ycombinator.com/item?id=24111248

https://news.ycombinator.com/item?id=24091297 3d out of paper
https://eyeburfi-blog.tumblr.com/
