#+TITLE: Getting Things Done
[[file:org_mode.org][Org Mode]]

https://jeffhuang.com/productivity_text_file/
[[https://news.ycombinator.com/item?id=22124489][Procrastination is about managing emotions, not time]]

[[https://news.ycombinator.com/item?id=23211184][your learning strategy]]
[[https://jjude.com/sdl/][self-directed learning: a framework to learn effectively]]
https://liquidti.me/
https://www.reddit.com/r/getdisciplined/comments/hunx3s/advice_how_to_split_your_time_tips_from_a/
[[https://julian.digital/2020/09/04/a-meta-layer-for-notes/][A Meta-Layer for Notes « julian.digital]]
[[http://karolis.koncevicius.lt/posts/ascetic_bullet_journal/][the ascetic bullet journal]]
https://benwiser.com/blog/Saving-todos-to-my-calendar.html

* What you'll wish you'd known
- It's hard to decide what job you want
- You don't learn in high school waht to do with your life
- Work forward from promising situations rather than working backwards from a goal:
  this ensures that you're using your time efficiently!
- 'Stay upwind' -> 'work on hard problems'. Treat school like a day job, work at your passions at night. You're wasting far too much time agonizing and procrastinating anyways.
[[https://www.hillelwayne.com/hate-your-tools/][hate your tools]]
* Start working despite not feeling like it
https://www.deprocrastination.co/blog/3-tricks-to-start-working-despite-not-feeling-like-it
- 'Screw it, let's do it'
- Start sloppy
- Start small
[[https://www.lifehack.org/articles/productivity/how-stop-procrastinating-and-stick-good-habits-using-the-2-minute-rule.html][two minute rule]]: start working on something for two minutes and put it down iff it's not worth the time
[[https://news.ycombinator.com/item?id=23057411][how do you self study?]]
[[https://news.ycombinator.com/item?id=23088219][having 'grit']]
[[https://www.reddit.com/r/productivity/comments/hv5343/how_to_better_remember_what_you_read/][how to remember what you read]]: implement some of these strategies !!
https://jamiehoward.co/
* zotero
http://zotfile.com/ plugin for zotero to manage attachments
 [[https://en.wikipedia.org/wiki/Five_whys][Five whys - Wikipedia]]
 [[http://tynan.com/prioritize][A Step by Step Guide to Life Prioritization - Tynan]]
https://explog.in/notes/writingsetup.html opinionated structure for writing setup

* how to do hard things
https://www.drmaciver.com/2019/05/how-to-do-hard-things/
- find something similar to the hard thing but easy
- modify the easy thing to have exacly one thing that is hard
- do modified thing until it is no longer hard

   https://news.ycombinator.com/item?id=22325975 learning complex, dense information.
https://fortelabs.co/blog/para/ method for organizing digital information
https://fs.blog/2013/12/circle-of-competence/ understanding your circle of competence
http://www.howardism.org/Technical/Emacs/getting-boxes-done.html [[file:org_mode.org][Org Mode]] getting boxes done
https://www.reddit.com/r/orgmode/comments/hfmgdw/greenspuns_eleventh_rule_any_sufficiently/
https://orgmode.org/list/87zha5qrds.fsf@nicolasgoaziou.fr/ org mode mailing list

http://matt.might.net/articles/productivity-tips-hints-hacks-tricks-for-grad-students-academics/

http://www.paulgraham.com/head.html if you can hold the whole program in your head, you're finishing things effectively.
http://www.paulgraham.com/newthings.html making new things

https://news.ycombinator.com/item?id=23550758 developing internal motivation

https://writingcooperative.com/zettelkasten-how-one-german-scholar-was-so-freakishly-productive-997e4e0ca125 being freakishly productive with the zettelkasten method
https://blog.jethro.dev/posts/self_tracking_in_plain_text/
 [[https://www.nytimes.com/2019/02/03/smarter-living/failure-resume.html][Do You Keep a Failure Résumé? Here’s Why You Should Start. - The New York Times]]

 https://news.ycombinator.com/item?id=24265491
