#+TITLE: Memoriam

I want to replicate the feeling of memory.

* Rationale

Memories are temporary.
Memories fade.

Today, we're empowered with several tools to prevent this. We have devices that constantly track our locations and monitor our activity. I want to use these tools to allow us to travel through our past.

I want to replicate the feeling of walking down a familiar road and seeing a place we have a particularly fond memory of, but in the digital world. Moreover, I want to be able to share this experience with others who may not have lived the same life experiences I have had, and to be able to link across experiences between people.

Further, I'd like to add a nostalgic aspect that we do not often feel in the real world -- one spent on the internet.

(This isn't a very good name... it should be catchier.) 

* Information

- Location
- Location stamped photos/videos
- Notes on photos
- Textual links for every point
Not everything has to be linked to a location, but most browsing is location-based.

* Rough Idea
** Temporal View

Cutscenes happen like a video game with fast travel. Pressing 'play' on a day starts with a map and a first location. It will zoom in when digital activ

** Spacial View

Visit location -> see everything visible in that location. A lot of this is already handled by Google Maps. You should be able to enter the other views from here so that viewing a location can trigger a memory.

** Textual View

This is a traditional dictionary view.
It puts text notes first and allows for the browsing of linked information, much like other dictionaries.
I'd like a view that operates similar to my wiki.

