#+TITLE: Movies
* Recs
https://www.youtube.com/watch?v=3pT7gadYPso
https://www.youtube.com/watch?app=desktop&feature=youtu.be&v=bzDjGvdvJXI
https://www.youtube.com/watch?app=desktop&v=3Q6Fzbgs_Lg
Arman: La Haine
Miracle on 34th street
Die Hard
American History X
[[https://www.criterion.com/][the criterion collection: classic movies]]
https://archive.org/details/CyberlifeShowOnOnliveTraveler1997
* Seen
** Akira
Worth all of the hype. A seminal cyberpunk fantasy with animation that still feels like it's from the future. There's no need for exposition because the story tells itself.
** Goodfellas
Great narrative -- clearly inspired movies like the wolf of wall street ans catch me if you can, among others.
** Monty Python and the Holy Grail
** Taxi Driver
** Pineapple Express
Stupid 'comedy' movie, no depth involved

* Record of a living being
https://cinemasojourns.com/2020/03/29/akira-kurosawas-record-of-a-living-being/
source
watch the film :: one of the first to directly address the fear of nuclear
holocaust and the implications of the atom bomb.  an introspective, cerebral
work regarding japan after the bomb and moving forward, away from fallout.
inspired by conversations with otuers regarding what may -- or may not be --
in store for us tomorrow, if tomorrow is in store at all.
