#+setupfile:./hugo_setup.org
#+hugo_slug: music
#+TITLE: Music

Programming and music.

* Synthesizers
** Online
https://synth.playtronica.com/
https://midi.city/
** OP-1
[[https://github.com/op1hacks/docs][OP-1 Hacks]]
[[https://github.com/op1hacks/op1repacker][OP-1 Repacker]]
** Otto :: Open source OP-1 Adjacent Project
[[https://github.com/OTTO-project/OTTO][src]]

** Pocket Operators
[[https://github.com/santiagomarcano/PO-33][learn to use the PO-33]]

* Tools
- MPD
  https://github.com/drewt/scmus
[[https://m.youtube.com/watch?v=3jxcKPoi5Kc][use game boy as midi synthesizer]]
http://nanoloop.com/mono/index.html nanoloop synth
* Notes
ncmpcpp is an mpt client, the frontend for mpd

** Installation
can configure thing !

install: ncmpcpp, mopidy, mopidy-mpd, mopidy-spotify

configuration:
the mopidy service by default reads its configuration from
/etc/mopidy/mopidy.conf, not from ~/.config;

trying a symlink
symlink didn't work out
just going to start it in userspace

*** mopidy-spotify

goto https://mopidy.com/ext/spotify/#authentication and authenticate
its unclear how i can even search with this interface!!

** idea: dishwasher with auto soap dispenser. duh
[[https://github.com/ngynLk/dotfiles/tree/master/.ncmpcpp][Displaying art with ncmcpp]]

[[https://wiki.znc.in/ZNC][configure irc bouncer so that irc clients can stay in session]]

* setting up mutt for gmail

[[https://news.ycombinator.com/item?id=14567074][on using mutt]]
make sure to generate an additional password for two factor auth
other than that everything is fine
mutt is not a fun user experience ....

* other configuration (TODO)

set up server
host music on this server

goal configuration::
- music streaming from custom server to local system
- single client for all messaging platforms (matrix,irc,slack,discord.....) (matrix??)
- rss feed from a single server (tt-rss, newsboat)
- better autosync solution than dropbox
- controlling things in house, different places etc
- reproducible system configuration
[[https://www.reddit.com/r/selfhosted/][selfhosted community]]

- a place to view social media easily and centralized:
- twitter/mastodon/instagram (??)

[[https://hobo.house/2017/07/17/using-offlineimap-with-the-gmail-imap-api/][offlineimap]]
[[https://bedrocklinux.org/][bedrock linux: mix and match components from different linux distributions]]

https://metasyn.github.io/learn-orca/#percussion

https://timput.com/posts/mailserver.html self hosting email with nixos and
vultr !
https://thedorkweb.substack.com/p/tales-from-the-dork-web-10 making a cool
thing

https://www-cs-faculty.stanford.edu/~knuth/taocp.html classic. may be a good
read, sounds like a waste of time right now . probably a cool gift or
something to purchase though !

https://geekflare.com/multiple-domains-on-one-server-with-apache-nginx/
pertinent for the server configuration

https://beta.openai.com/ openai analysis through an api!

https://github.com/musikinformatik/Steno music for live coding .
https://supercollider.github.io/ the classic live coding librar
https://github.com/toplap/awesome-livecoding/blob/master/README.md great
livecoding resources
* resources
[[https://www.spitfireaudio.com/labs/][free software instruments]]

[[https://supercollider.github.io/][music engine]]
[[https://blog.benwiener.com/programming/2019/04/29/reinventing-the-wheel.html][reinventing the wheel with pytorch]]
[[https://metasyn.github.io/learn-orca/#percussion][percussion machine]]
[[https://audiomass.co/][neat audio file editor]]

https://www.youtube.com/watch?v=x0BpPa72qCE&app=desktop
http://www.pd-tutorial.com/english/index.html
https://vcvrack.com/
https://forum.bela.io/d/1277-c-real-time-audio-programming-with-bela-a-free-online-course
https://www.syntorial.com/
https://ccrma.stanford.edu/~jos/

https://www.purrdata.net/
https://teddykoker.com/2020/05/deep-learning-for-guitar-effect-emulation/
https://arxiv.org/html/1202.4212
https://git.sr.ht/~rabbits/orca
https://sonic-pi.net/
https://www.simple.com/blog/behind-the-budget-how-to-build-your-own-synthesizer-with-simples-kelly-d
https://syntherjack.net/how-to-start-synth-diy/

https://www.gwern.net/GPT-2-music#generating-midi-with-10k30k-context-windows
-- generating music automatically!!
https://bjooks.com/ -- music book website
https://www.soundonsound.com/reviews/push-turn-move -- highly recommended; a
book written about how we interact with electronic instruments. for synth
enthusiasts and music industrial designers!
http://everynoise.com/engenremap-vaporsoul.html
http://everynoise.com/engenremap-indiepoptimism.html
http://everynoise.com/engenremap-indiepoptimism.html
http://everynoise.com/retromatic.html
http://everynoise.com/engenremap-vaportrap.html
http://everynoise.com/engenremap-escaperoom.html
** making music
https://learningsynths.ableton.com/
https://learningmusic.ableton.com/
https://www.ableton.com/en/blog/ideas-offers-making-music-home/
https://musiclab.chromeexperiments.com/
** making the making of music
https://tonejs.github.io/
https://www.youtube.com/watch?v=JZ5yPdoPooU
https://www.youtube.com/watch?v=x-1_TEETVOA
https://www.reddit.com/r/synthesizers/comments/fxhogj/im_a_bassist_and_producer_and_i_love_synths_i/

* music
https://www.youtube.com/watch?v=SqayDnQ2wmw
[[https://www.youtube.com/watch?v=ONloOhDLrFU&app=desktop][inspiration: turning ideas into tracks]]
[[https://keithclark.github.io/ZzFXM/tracker/?url=https://raw.githubusercontent.com/keithclark/ZzFXM/master/examples/songs/sanxion.js][ZzFXM Tracker synthesizer]]
https://codepen.io/kucerajacob/pen/GRqBQNV drum sequencer with sample pad
[[https://m.youtube.com/watch?feature=youtu.be&v=OP8bsXbJlpw][devine using orca well]]
https://www.instagram.com/p/CD17bImnUp7/ incredible devices making incredible music

https://m.youtube.com/watch?v=tLFOt7BbYJc ambient music and randomness
https://m.youtube.com/watch?v=OHS3lN6snrE euclidean rhythm
* Listening Recs
frisky biscuits - mason
agulta - gabriel garzon montano
world of echo - arthur russell
from deewee- soulwax
baile and drip - vhoor
https://wiki.xxiivv.com/site/listening.html
https://www.reddit.com/r/aphextwin/comments/k4c42v/songs_like_avril_14th/
https://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780190226992.001.0001/oxfordhb-9780190226992 cool textbook for algorithmic music
* Generative music
** SuperCollider
https://www.emacswiki.org/emacs/SuperCollider
[[http://ccrma.stanford.edu/planetccrma/software/supercollider-en/][How to make SuperCollider go &quot;beep&quot;]]
[[https://m.youtube.com/watch?v=YUIPcXduR8E][Jessica Garson - Making Music with Python, SuperCollider and FoxDot - PyCon]]
[[https://github.com/lvm/build-supercollider][build-supercollider]]
[[https://github.com/theseanco/howto_co34pt_liveCode]["A repository of readmes, techniques, notes and other materials about how i live code in SuperCollider. A (sorta) companion repository to co34pt_livecode "]]
[[https://www.reddit.com/r/vim/comments/hwdehp/vim_osc_livecoding/][Vim   OSC = Livecoding - vim]]
** TidalCycles
https://gist.github.com/kindohm/9388957
[[http://pages.tidalcycles.org/getting_started.html#linux][Tidal - Getting Started]]
[[https://news.ycombinator.com/item?id=13947537][TidalCycles – A language for the Live Coding pattern | Hacker News]]
[[https://tidalcycles.org/index.php/Linux_installation][Linux installation - TidalCycles userbase]]
[[https://tidalcycles.org/index.php/Welcome][TidalCycles userbase]]
[[https://news.ycombinator.com/item?id=13947537][TidalCycles – live music coding : Hacker News]]
** Overtone
[[https://github.com/overtone/overtone/][overtone/overtone: Collaborative Programmable Music]]

[[https://github.com/overtone/overtone][Collaborative Programmable Music ]]
** Orca
[[https://llllllll.co/t/orca/22492][Orca - Library - lines]]
[[https://metasyn.github.io/learn-orca/#percussion][LEARN ORCΛ~]]
[[https://github.com/hundredrabbits/Pilot][hundredrabbits/Pilot: Orca&#039;s best friend.]]
[[https://futureofcoding.org/episodes/045][45 • Devine Lu Linvega • Orca | Future of Coding]]
* Physical generative devices
[[https://wiki.xxiivv.com/site/telekinesis.html][telekinetic music from devine]]

[[https://m.youtube.com/watch?v=TK1mBqKvIyU][Programming as Performance | Sam Aaron | TEDxNewcastle]]
[[https://algorave.com][Algorave]]
[[https://m.youtube.com/watch?v=VW_SFmS17ao][Yann Tomita and the Doopees - How Does It Feel - YouTube]]
[[https://www.unminus.com/][free premium music for your projects]]
https://wiki.xxiivv.com/site/eschatolor.html
https://github.com/googlecreativelab/chrome-music-lab [[file:web_design.org][Web Design]]
https://github.com/nukeop/nuclear
[[https://audiomass.co/][audio mass]]

[[https://deezer.io/releasing-spleeter-deezer-r-d-source-separation-engine-2b88985e797e][spleeter: msuic research engine]]

[[https://github.com/prajwal1121/Portable-Synth][op-1 style portable synthesizer!]]
[[https://github.com/deepjyoti30/ytmdl][get songs from yt in mp3 format]]

[[https://github.com/toplap/awesome-livecoding][awesome livecoding]]
https://github.com/beetbox/beets music library manager
https://github.com/s-ol/themer themer

[[http://labs.phaser.io/][phaser games]]
[[https://github.com/f-f/CASSALPOPOLO][f-f/CASSALPOPOLO: More open source 4/4 beats for the peoples]]
[[https://arcade.makecode.com/][games in the browser!]]

[[https://m.youtube.com/watch?v=30FiQ8m4aoo&index=23&list=PLyrlk8Xaylp5mvxARtX5ncjy9p4X_Ajwd][Session 19 June 0800 Synthesis 3 - YouTube]]
[[https://m.youtube.com/watch?v=09w54uhb1TE&list=PLyrlk8Xaylp5mvxARtX5ncjy9p4X_Ajwd&index=17][Session 18 June 1040 Machine Learning II - YouTube]]
[[https://m.youtube.com/watch?v=EjuetJ00Z0M&t=3m17s][Session 17 June 0620 Networking and Hardware - YouTube]]
