#+setupfile:./hugo_setup.org
#+hugo_slug: personal-website
#+TITLE: Personal Website

Everyone should have a bit of a personal website with a little blurb about who they are and what they do.
https://jacob.chvatal.com
* Inspiration
https://github.com/pacocoursey/paco
https://github.com/azlen/azlen.me
[[https://ameyama.com/hey][novel design!]] a website that interfaces with a physical device, a pi, and flashes a smiley face whenever someone visits the page. lends some personal, physical characteristics to an otherwise void webspace. they also have very good book recommendations
https://github.com/zzh8829/zihao
https://github.com/ottomated/portfolio

https://github.com/kickscondor/fraidycat follow everything from a single page
[[https://github.com/xdesro/vogue][xdesro/vogue]]
https://aaron.ng/
http://ryanhileman.com/
http://ryandoeng.es/
https://lucumr.pocoo.org/
https://controls.ee/links/
https://magoz.studio/
http://www.jameschip.io/
https://weasyprint.org/
https://omar.yt/

https://shifrakhan.com/ this is close to what i want my site to look like!
https://www.amalbansode.com/pages/projects/data/index.html
http://whydontyoulove.me/
https://whitequark.org/ && https://lab.whitequark.org/
https://lyngvaer.no/
https://ambrevar.xyz/articles.html
https://emersion.fr/
https://craze.co.uk/
https://benkettle.xyz/ i really like this site as well!
http://jmct.cc/ galois person
http://people.cs.uchicago.edu/~rchugh/
http://people.cs.uchicago.edu/~brianhempel/ can we augment programming with direct manipulation interactions?

https://a9.io/
https://penrose.ink/ beautiful diagrams with math notation in plain text
https://www.katvlasova.com/ art
http://www.brendangregg.com/

[[100r.co][100 rabbits site]] is also a great reference for personal site look
http://seenaburns.com/
http://akkartik.name/about
https://www.welcometothejungle.com/en/collections/behind-the-code
https://frnsys.com/
https://www.jainfamilyinstitute.org/
https://mutantc.gitlab.io/

https://www.zx2c4.com/ this is so sick

[[https://royniang.com/][koikoi — index]]
[[http://kmicinski.com/][Kristopher Micinski]]
[[https://cblgh.org/now/][now | cblgh.org]]
[[https://clairelegoues.com/][Claire Le Goues]]

[[https://m.youtube.com/watch?feature=youtu.be&v=MmkNSsGAZhw][The Simple Essence of Automatic Differentiation - YouTube]]

[[https://m.youtube.com/watch?feature=youtu.be&v=Kgw9fblSOx4][Residential Programming without Mutable State - Thomas Getgood - YouTube]]

[[https://thume.ca/resume/][i like layout of resume and pers proj]]

https://people.csail.mit.edu/karger/
https://www.stephanboyer.com/

https://sivers.org/ cool entreprenuer
https://secondbreakfast.co/patio11-s-law
https://tinysubversions.com/
https://jae.moe/
https://www.paritybit.ca/

http://mikhailkhoury.com/
https://www.reddit.com/r/compsci/comments/69h3vb/rank_polymorphism_for_array_languages/
https://weiweihuanghuang.github.io/
http://janvitek.org/whoowns.html
