#+TITLE: Product Research
https://www.thelightinthedarkplace.com/2019/08/the-origin-of-life-fruit-of-life-metatrons-cube.html?m=1
Products I like.

* Packs

[[https://www.carryology.com/reviews-2/head-to-head/peak-design-everyday-backpack-zip-vs-everyday-backpack-v2/][Peak Design Camera Packs]]
Mission workshop rambler
https://www.peakdesign.com/products/travel-backpack/
[[https://www.orbitgear.net/collections/messenger/products/r221-vb-wx-adv-vb-commuter][orbitgear acr clone]]
[[https://www.peakdesign.com/collections/pouches-cubes/products/camera-cube?variant=11530961649708][pd camera cube]]
[[https://www.peakdesign.com/products/tech-pouch][pd tech pouch]]
[[https://www.indiegogo.com/projects/arris-adventure-pack-modular-accessories#/][arris pack - love the innovation here]]
https://matterful.co/i/pakt-travel-backpack/ modular good
https://matterful.co/i/aer-capsule-pack/ travel pack elegant aer
https://eu.wandrd.com/products/duo?sscid=91k4_5stpc would be good if not for branding

* Socks

[[https://www.amazon.com/dp/B0771V3SSP/?tag=wtpl-20][gtex socks]]

* Shirts

[[https://www.patagonia.com/product/mens-capilene-cool-daily-shirt/45215.html?cgid=mens-shirts-tech-tops-daily][patagonia tech top]] considered best non-merino wool performance shirt
[[https://woolandprince.com/products/button-down-ivory-twill][wool and prince button down]] wish this had cover over buttons, that would be a bit sleeker
[[https://www.veilance.com/us/en/shop/mens/frame-ls-polo][veilance frame ls polo]] first polo i have liked

* Collections

https://m.youtube.com/watch?v=rMoig3kQr3Y

* towel

travel towel recs
https://packhacker.com/travel-gear/matador/nanodry-towel/

* jacket

[[https://www.veilance.com/ca/en/shop/mens/indisce-blazer][indisce blazer]]
[[https://www.veilance.com/ca/en/shop/mens/partition-coat][partition ar coat]]
[[https://rosen-store.com/collections/rosen-x/products/rosen-x-minerva-2-overshirt-in-2l-nylon?variant=30231428857915][rosen minerva overshirt]] both min. and futuristic!

* recorder
[[https://www.ourlegacy.se/mens/shirting][Shirting - Long and shortsleeve shirts - Our Legacy]]

https://m.youtube.com/watch?v=SgMteaMbZi8 -- best lav mic recorder?
[[https://m.youtube.com/watch?v=-L1EtAdgwww][how to mount h1n on camera]]

* wbottle

https://packhacker.com/travel-gear/vapur/eclipse-water-bottle/ get one like this

* general
remake clothes like my y3 things in sustainable fabrics!
imitate vetements zip hoodie, one size bigger, waterproof or merino or something
wish i had vetements xl

https://outlier.nyc/collections/pants/products/futureworks
https://www.reddit.com/r/onebag/comments/blghok/ronebag_buying_guide_pants_and_shorts/ buying guide for onebagging
https://www.reddit.com/r/onebag/comments/935t1p/best_tshirt_for_running_yoga_and_gym/ best all in one tee

https://www.michaellivingston.com/my-travel-kit-weighing-underwear-for-science/ underwear: uniqlo prob best

https://wayfindercarry.com/collections/accessories/products/borderless-passport-notebook-holder borderless passport holde
https://kk.org/thetechnium/travel-without/ traveling without a bag
* transport
https://us.brompton.com/
https://blixbike.com/products/vika-electric-folding-bike
https://www.reddit.com/r/DIEMs/comments/6xzwnn/first_attempt_at_diy_ciems/ diy ciems
https://www.hilavitkutin.com/2007/01/22/burton-audex-motorola-cargo-jacket-lumilautatakki-kaiuttimilla/ the audex jacket
https://ablecarry.com/products/daily-backpack?variant=19570923602033 backpack
https://outlier.illposed.com/ outlier archive
https://m.youtube.com/watch?v=rMoig3kQr3Y descente allterrain show
https://www.reddit.com/r/onebag/comments/hzqxk2/lightweight_compact_travel_blanket/
https://web.archive.org/web/19980115120006/http://www.asarian.org/~vickis/continuum.html yes

* anxiety in product development
https://andreschweighofer.com/agile/anxiety-in-product-development/
anxiety can emerge easily from stress, resulting in anger, frustration and
other unhealthy forms of exerting such stress. this impacts other people,
organizations and processes as well.
we have fear driven development : a concrete idea encouraging us to avoid
certain practices depending upon the specific approach
play to win, don't play not to lose; developing a unique selling proposition
means that you are no longer fighting with others, but rather striving to
come out ahead
awareness of such anxiety is the first step to take. with this awareness
comes conscious decision making, and with such decisions come wiser product
crafting and, in the end, better, more creative work

Why should you be concerned?
[[https://www.nytimes.com/2019/12/05/opinion/digital-technology-brain.html][Our brains are no match for our technology.]]
[[https://vimeo.com/36579366][Inventing on principle]]
https://www.youtube.com/watch?app=desktop&v=b2AjRklfWQo
