#+TITLE: Quantified Self

analyzing myself
life logging is super important
what things am i interested in processing?
[[https://beepb00p.xyz/my-data.html#emfit][source]]

https://activitywatch.net/  good resource for tracking
[[https://blog.jethro.dev/posts/self_tracking_in_plain_text/][Jethro's self tracking in plain text]]

doing things digitally automatically logs data for the timeline
feels wrong that data can be forgotten and lost forever
want to have the choice whether to forget or remember,
and want to be able to access forgotten memories

ultimately, i want this to be an effort to accomplish two things:
- reduce the services i use
- connect all of the services i use
and i want to be able to interface with all of them

eventually, i would like to be able to open this ecosystem to others,
and in doing so allow people to share events, memories and experiences


* text messages
i want to see everything i have sent and to whom i have sent it to
* purchases
i want to be able to track all of my purchases
* health
** consumption
 track precisely what i am eating and the assoc. information
** exercise
what exercise am i doing? what does it change about my health?
** general
sleep, mental competency/sluggishness?
some way to reflect on longer term progress
** env
temp during sleep
weather conditions information
** blood
tracking blood levels is best way to deduce health composition
** sleep
sleep time, health etc
* github
- code progress
- what projects do i work on? when? how much do i do?

* gps
where have i been? why? how?
** places
where did i probably spend my time?
what places am i interested in?
what did i visit?
* mail
what mail do i get? what htings go through mail?
* google
google gives lots of good analysis, like browsing and youtube watch history
* music
what do i listen to? why? how?
* photos
- document what i see
- assoc with location
- assoc with sound
- assoc with time and other things
front to back: time and location taken to ig and blog post
* shell
what goes on
* ideas
- weight
- sports

- sick today
- mood
- good/bad
- what i learned
- heart rate
- steps
- eating habits
the more i track the more i know about myself
the more time i save
the more efficient i become

* biofeedback vibes
https://www.nature.com/articles/s41598-020-72501-w
does perceived health matter more than actual health?
this is just one study but nature is huge.
* tracking
[[https://medium.com/aaronn/tracking-my-blood-glucose-over-a-month-with-a-sensor-stapled-to-my-arm-8f025c438719][constant feedback blood glucose]]
[[https://medium.com/aaronn/some-thoughts-on-n-back-and-a-free-sketch-file-din-for-ios-6d82af94359c][notes on n-back]]
[[https://medium.com/aaronn/cognitive-enhancement-nootropic-stack-october-2017-7232c6b657e4][pill stack]]
[[https://gitlab.com/joshavanier/cal][gool generated time log]]
