#+TITLE: Shows

Shows I've seen!

Yes, this includes anime.

breaking bad
the wire
trigun
cowboy bebop
re:zero

* Queen's Gambit
Beautifully done 1950's woman empowerment - but not about woman - genius character develops into a star and navigates relationships with a pragmatic view of the world but desparate one of the past.
* FLCL
aka Fooly Cooly
2000s anime; I love the soundtrack but the plot is nonsensical or entirely absent.
* Neon Genesis Evangelion
Absolutely beatiful series. Killer opening theme that doesn't fit the show at all. The pacing and visuals are artful; entirely different from any comparable series.
that ending really sucked though
* FMA Brotherhood
True to the manga but skips all of the fluff - somehow improves on the best moments. the retrospective did them some huge favors, and they were able to perfect already one of the best manga out there
* Death Note
As expected, this is an incredible series. The third arc (could be considered the second arc) notably trails off in quality relative to the second arc or the first segment of the series as characters begin to lose dimension -- though some of the characters have to develop flaws to some degree as the series continues or there wouldn't be any resolution.
* Erased
Poetic, simple series about someone who's hit a dead end making the right decisions and changing his life. All of the characters are incredibly fleshed out, and the depiction of trauma is almost poetic -- all of them, in one way or another, garner sympathy from the watcher and you become invested in just 12 episodes. Not a moment is wasted, either; the series starts and resolves quickly and all of the plot points are cleanly tied together.
* Steins;Gate
This started incredibly slow and I didn't have the patience to continue watching. The characters didn't feel comprehensive and didn't have much depth to them; the same corny anime jokes were made so many times within the first few episodes, and actual plot elements were few and far between.
