#+setupfile:./hugo_setup.org
#+hugo_slug: vim
#+title: Vim

Vim is a text editor with an easily configurable extension language. It's most frequently used as a [[file:./terminal_ui.org][TUI]] program but also has an (aft-used) graphical application distribution (Gvim).

I've come to prefer the power of [[file:emacs.org][Emacs]] but I do miss Vim's performance.

However, it has a first-class editor-based extension language that's written to prioritize text processing and configuration. Its extensive, literate keybindings that have made their way into every popular text editor as well as many other applications.

It's one of best text-editing tools in the Unix ecosystem, and Vim users often have a library of cli and tui programs that they use in conjunction with Vim to facilitate a desktop ecosystem without a GUI.

Vim is often preinstalled on Unix systems. If it's unavailable, such systems will likely still have vi (or busybox vi), so taking the time to learn vim keybindings is worthwhile for their flexibility throughout programming environments.

* Tools
https://www.youtube.com/watch?app=desktop&v=-I1b8BINyEw my vim workflow
https://www.reddit.com/r/vim/comments/h84oiy/list_of_all_vimtips/ lots of vim tips
https://writing.grantcuster.com/posts/2020-07-12-swapping-color-schemes-across-all-terminals-and-vim-with-pywal-and-base16/ swapping all color schemes
https://vimways.org/2018/death-by-a-thousand-files/ vim as the end all be all

https://www.edwinwenink.xyz/posts/48-vim_fast_creating_and_linking_notes/ linking notes in vim

https://www.reddit.com/r/vim/comments/hvr09s/how_can_i_integrate_a_vim_text_editor_in_react/[[file:web.org][ Web]]
http://marco-lopes.com/articles/Vim-and-Haskell-in-2019/
https://github.com/puremourning/vimspector debugging
https://archive.emily.st/2018/11/13/vim-in-the-future/#vim-in-the-future vim in the future
https://github.com/glepnir/dashboard-nvim vim dashboard

https://vim.fandom.com/wiki/Editing_remote_files_via_scp_in_vim edit remote files in vim
https://github.com/cassidoo/vim-up fun vim shortcuts
https://www.youtube.com/watch?app=desktop&v=BhwtnCaFTFk wild vim config

https://www.reddit.com/r/vim/comments/5ryxin/any_plugins_like_projectile_emacs_for_vim/ like projectile, but for vim
[[https://stevelosh.com/blog/2011/09/writing-vim-plugins/][how to write vim plugins]]
https://github.com/JNRowe/vim-configs
https://github.com/hlissner/.vim vim config
https://github.com/nimboids/vim-config vim config
https://www.reddit.com/r/vim/comments/hzesgf/ecstaticlife_will_never_be_the_same_again/ cool macros!

https://www.reddit.com/r/vim/comments/hzcmcd/personalize_you_dotfiles_with_signit/ create custom header or footer for dotfiles
https://github.com/alevchuk/vim-clutch hardware pedal for vim
https://www.reddit.com/r/vim/comments/i08w2t/quicker_saving_and_saving_habits/ good saving habits in vim

https://www.reddit.com/r/vim/comments/i35lev/i_made_an_improved_nerdtree_called_chadtree/ improved nerdtree file manager

https://www.reddit.com/r/vim/comments/hvxtpf/using_variables_in_your_nvimrc/ using variables in your vimrc

https://www.reddit.com/r/vim/comments/hy3yma/what_is_the_best_leader_key/ best leader key?
https://www.reddit.com/r/vim/comments/i0lffn/thought_id_share_some_recent_vimspector/ vimspector
https://github.com/tpope/vim-projectionist vim projections for granular project configuration

https://github.com/glacambre/firenvim neovim in the browser
https://github.com/puremourning/vimspector debugging system for vim
https://www.reddit.com/r/vim/comments/i0lffn/thought_id_share_some_recent_vimspector/
* Resources
https://www.reddit.com/r/vim/comments/i1tfux/i_have_fallen_to_vim/ learning more about vim mappings
https://www.reddit.com/r/vim/comments/h8pgor/til_conceal_in_vim/ -- concealing plaintext symbols with glyphs

* Plugins
https://www.reddit.com/r/vim/comments/i1p3s9/fernvim_a_modern_asynchronous_file_manager_for_vim/ async file manager, with lists of alternatives
https://www.reddit.com/r/vim/comments/i0tciv/you_liked_so_much_the_first_version_that_i/ a vim plugin for highlighting infomration in different colors while parsing a document
https://www.reddit.com/r/vim/comments/hvr09s/how_can_i_integrate_a_vim_text_editor_in_react/ adding vim text editor to react project
https://www.reddit.com/r/vim/comments/hxn5ue/how_do_i_use_macros_when_i_have_variable_amount/ meta macros for variable amounts of data
https://www.reddit.com/r/vim/comments/hwdehp/vim_osc_livecoding/ livecoding in vim
https://www.reddit.com/r/vim/comments/hy3yma/what_is_the_best_leader_key/ finding the best leader key
https://app.getpocket.com/read/3056881828 arbitrary variables in vimrcs
https://github.com/mhinz/vim-signify show a diff with vim sign column
https://github.com/francoiscabrol/ranger.vim rangerinteraction inside of vim
https://github.com/huyvohcmc/atlas.vim colorful vim theme?
https://vim.fandom.com/wiki/Editing_remote_files_via_scp_in_vim
https://www.reddit.com/r/vim/comments/h84oiy/list_of_all_vimtips/
https://getpocket.com/redirect?url=https%3A%2F%2Fwww.reddit.com%2Fr%2Fvim%2Fcomments%2Fi35lev%2Fi_made_an_improved_nerdtree_called_chadtree%2F
* ideas
idea! vim plugin to reduce plugin usage. removes random lines from vimrc on
load, and continues to remove them every time vim starts up until you
manually override
[[https://www.reddit.com/r/vim/comments/hm6b9d/help_vim_wpm_counter/][wpm counter for vim]]
[[https://www.reddit.com/r/vim/comments/hz97jh/nerdtree_vs_defx_vs_nnn_which_one_do_you_prefer/][vim file browser recommendations]]
[[https://www.reddit.com/r/vim/comments/i1p3s9/fernvim_a_modern_asynchronous_file_manager_for_vim/][ferm, an asynchronous file manager]]
