#+setupfile:./hugo_setup.org
#+hugo_slug: web
#+title: Web
Things about the web.

[[https://www.youtube.com/watch?v=5CYeZ2kEiOI&app=desktop][from rails to elm and haskell: functional web programming]]

* web dev
https://github.com/gawlk/svind boilerplate supporting svelte, vite, vercel and tailwind
https://github.com/GoogleChromeLabs/ProjectVisBug tool to edit any website in any state directly
https://felixgerschau.com/react-rerender-components https://tonsky.me/
https://www.ybrikman.com/writing/2013/11/24/play-scala-and-iteratees-vs-nodejs/
https://leerob.io/blog/how-stripe-designs-beautiful-websites
https://blog.chromium.org/2020/05/introducing-web-vitals-essential-metrics.html?m=1
https://wwwwwwwww.jodi.org/
https://raphlinus.github.io/graphics/2020/04/21/blurred-rounded-rects.html
https://www.youtube.com/watch?v=f2mMOiCSj5c&feature=youtu.be&app=desktop
https://benchmarks.slaylines.io/
https://webkid.io/blog/react-flow-node-based-graph-library/
https://jamesmonger.com/2019/09/10/super-robust-api-with-isomorphic-typescript.html
https://vistaserv.net/blog/90s-fonts-modern-browsers
https://lukeplant.me.uk/blog/posts/why-im-leaving-elm/ why not elm
https://www.reddit.com/r/haskell/comments/fy848b/why_im_leaving_elm/
https://einaregilsson.com/serverless-15-percent-slower-and-eight-times-more-expensive/
https://www.listennotes.com/blog/the-boring-technology-behind-a-one-person-23/
https://bitsofco.de/what-i-wish-i-knew-about-react/
https://denvaar.github.io/articles/csrf_tokens_with_phoenix.html
https://www.reddit.com/r/purescript/comments/fud1za/purescriptflame_cool_well_documented_alternative/
https://www.purescript.org/


** graphql
[[https://morpheusgraphql.com/]]
[[https://graphql.org/learn/best-practices/]]
[[https://gist.github.com/spicydonuts/0c09596c1f27d517e9fe][purescript and elm]]
[[https://github.com/hendrikniemann/purescript-graphql][typesafe graphql in purescript!]]
[[https://konkle.us/purescript-for-front-end-developers/][purescript on the frontend]]


* design
https://nipponcolors.com/#aikobicha -- color picker that has some neat
configurations by default!
http://fatihhardal.com/ -- cool design inspo
https://www.motherdesign.com/work/aiga/
** web design
https://www.cssmatic.com/noise-texture cool idea, exporting the link that will
query the right thing without saving it
https://www.webdesignerdepot.com/2014/12/3-tricks-for-adding-texture-to-your-text-with-css-and-svg/
https://www.webdesignerdepot.com/2015/02/3-cool-css3-image-hover-effects/
https://www.smashingmagazine.com/2020/04/skeleton-screens-react/

[[https://svelte.dev/][autocreate websites. what.]]

[[https://shouldiblockads.com/#ha][what is wrong with ads?]]
[[https://revealjs.com/#/][create stunning presentations on the web]]

[[https://txt.fyi/about/][quick publishing on the web.]]
[[https://ertdfgcvb.xyz/][inspirational site]]
[[https://constraint.systems/][creative image constraints]]

* web hostility
[[https://neustadt.fr/essays/against-a-user-hostile-web/][article]]
"Facebook is at odds with the open web that I love and defend..."
Netscape Navigator (small internet) -> big internet!
The modern web is being destroyed -- personalized content, growth hacking,
social media activation, CMS and user experience. These websites are not
built to appreciate the visitor -- they are constructed to make the user a
customer. Cookies bad! Small blogging good!

https://www.nirandfar.com/hooked/ book on the perils of the modern web, tangentially
https://drewdevault.com/2020/03/18/Reckless-limitless-scope.html
http://john.ankarstrom.se/replacing-javascript/ reducing the scope of the web
[[https://www.quirksmode.org/blog/archives/2015/07/stop_pushing_th.html]]

* background
[[https://www.html5rocks.com/en/tutorials/internals/howbrowserswork/][Great work on how browsers work]].
* fun sites
- [[https://milk.com]] :: This individual is staking their claim over their corner of the internet and doing so strongly. Mimu is a cool collection of programatically generated music demos as well.
- [[radio.garden]] :: A map of the world with lots of radio stations. Listen in from anywhere!
- [[https://www.ocearch.org/tracker/?list][osearch.org]] :: Track seals, whales, turtles and (mostly) sharks all over the world! There are pictures! They all have names!
- [[campoallecomete.it/]] :: A wine website *and* an intimate 3D experience.
- [[asoftmurmur.com]] :: Generate white noise of your choice to remove distractions.
- [[https://atelier.net/virtual-economy/]] :: An incredible article about the virtual economy. I wish more articles offered such experiences.
* Great ideas
- [[branch.gg]] :: A two-dimensional office environment for employees to interact in just like a physical space.
- [[http://endless.horse/][hoooooooooooooooooooooooooooooooooo]]
https://meowis.ms/handshake.html handshake: forming a namespace system for the decentralized web. we don't own our own domains!
https://github.com/auchenberg/volkswagen the best way to pass tests
https://yarmo.eu/blog/no-io-yes-xyz
https://github.com/luigimannoni/webxr-earthday webxr of earth day
[[https://runyourown.social/#how-to-run-a-small-social-network-site-for-your-friends][advice on running a small social network]]
https://now.lectronice.com/ cute personal site
http://vmchale.com/miscellany very cool person

https://thomasorus.com/home.html cute site using some fun time tracking and management ideas
https://www.welcometothejungle.com/en/articles/btc-interview-paul-mockapetris interview with creator of dns

[[https://href.cool]]
[[https://john-doe.neocities.org/#home][example with one line html file for multi page site]]


https://www.are.na/everest-pipkin/on-vocal-cloning on vocal cloning: beautiful piece. sources for this: https://shell-song.neocities.org/
https://neocities.org/: support for creating cool websites with free hosting!
* SEO
[[https://www.currentaffairs.org/2020/12/how-seo-is-gentrifying-the-internet][how seo is ruining the web]]
[[https://static.googleusercontent.com/media/guidelines.raterhub.com/en//searchqualityevaluatorguidelines.pdf][Google's vaguely worded SEO advice hadnbook]]
reverse engineer seo by sampling search results? is this done?
