#+setupfile:./hugo_setup.org
#+hugo_slug: web_design
#+title: Web Design
- tags :: [[file:design.org][Design]],[[file:fonts.org][ Fonts]]

* Philosophy
:PROPERTIES:
:ID:       84fdf4e2-8050-40e8-bd93-502d6e260dfa
:END:



Websites should be minimal.
There is no reason to download five megabytes of Javascript to communicate
my hiring credentials. I shouldn't have to wade through frameworks and dark
patterns to read a blog post!

I am taking a reductionist approach to web design by:

- Limiting the number of lines of Javascript.
  Javascript consumes unnecessary resources and can distract from information
  presented; as such, Javascript should serve only to enhance current content.

- Limiting the number of colors on the site, shifting focus to central components.

- Reducing the overall complexity of the project.
  You can only truly understand a machine if you can remove every piece
  you don't need. If every piece is necessary for communicating the information,
  it's all the end user should need to see.

Aesthetics aside, focusing on minimizing web development allows the millions of
people worldwide with slow connections to access resources and information.
Using a simple subset of CSS and Javascript, too, enables older browsers and
hardware to sufficiently load websites.

The web doesn't have to be so hostile or expensive to run.
Focus on boiling it down to its essentials.

https://matthiasott.com/notes/the-thing-with-leading-in-css

* Inspiration
:PROPERTIES:
:ID:       3f7f93ab-9bc7-4322-9f3e-15d8efa5b949
:END:

- [[http://mikhailkhoury.com/][Mikhail Khoury's website]], one I stumbled upon only because he shares
  a last name with Northeastern's Computer Science college, has
  an astoundingly minimal yet well-designed site. It's easy to navigate
  and has no distractions from the site's objective.

- [[https://100r.co][100 Rabbits]] are a creative duo comprised of Rekka Bellum and
  [[https://xxiivv.com/][Devine Lu Linvega]]; they've inspired me to move towards using
  minimal, accessible tooling, and have a fantastic design language
  present throughout all of their work. [[file:../people/100_rabbits.org][100 Rabbits]]
- [[https://www.pentagram.com/work/secondmind][Pentagram]], a design consultancy with a lot of great work. They have lots of mockups and designs to reference.

* Resources
:PROPERTIES:
:ID:       919f9e4b-ec6f-404a-9f5c-ee51aa3605d3
:END:

- [[http://clrs.cc/][clrs.cc]] :: communicative colors for browser prototyping.

Y
https://cargo.site/
[[https://www.huffpost.com/entry/complexion-reduction-a-new-trend-in-mobile-design_b_577d828fe4b05b4c02fb8b07?test_ad=taboola_iframe_mw_life][complex reduction]]
[[https://medium.com/startup-grind/i-got-rejected-by-apple-music-so-i-redesigned-it-b7e2e4dc64bf][apple music redesign case study]]

https://codepen.io/ge1doot/pen/MWeBPQE very cute pen
https://matthiasott.com/notes/wicked-design quick thoughts on 'wicked design'
https://grumpy.website/ a catalogue of terrible user interface design decisions
https://avanier.now.sh/work.html love this
https://www.happyhues.co/ helps pick and curate colors
https://deianeira.co : great web design. wow
vertically aligned logos, cool font, 'alter ego', quick journal
https://neil.computer/notes/the-design-of-diskprices-com/ amazing minimal site with a few notes on making it the best it can be
http://ericmotil.com/
[[http://clrs.cc/][default web colors for sites optimized for the browser]]
https://web.archive.org/web/20191125141522/http://www.070shake.net/ an incredible site!

[[https://themesberg.com/product/ui-kit/windows-95-ui-kit][Windows 95 UI Kit - Themesberg]]
[[https://github.com/brainrape/windows-95-ui-kit][brainrape/windows-95-ui-kit: ? Windows 95 UI Kit made with Bootstrap 4 comp]]
https://github.com/mit-pdos/noria
