#+setupfile:./hugo_setup.org
#+hugo_slug: wiki
#+title: Wiki

Wikis are tree-based tools for representing
hierarchies of information.

This personal wiki is the one I maintain.
Others refer to personal wikis as /Digital Gardens/,
/Brain Dumps/, or /Personal Libraries/.

The source of this wiki can be found at [[https://github.com/jakechv/wiki]].

* Motivation
** Organization

I needed a way to better organize my ideas.
Administering structure to my data was a good way
to do this, and org-mode provides a good facility for this.
Further, the constraints administered by the website motivate
me to better organize my notes as they're visible to the public;
without this structure the notes won't even render properly.

** Accessibility

I'd like my notes to be easily visible to anyone.
It allows me to easily share my thoughts and perspectives with
friends or colleagues.

** Publicity

This portal also enables recruiters or future collaborators to
learn more about me, my skills and my interests. Perhaps I can
build a following, inspire someone, or find an interesting job
opportunity if someone stumbles upon this wiki.

* Design

- tags :: [[file:web_design.org][Web Design]],[[file:design.org][Design]]
The design of this wiki takes after the principles of simple and minimal as discussed.
I introduce additional logic for the multi-pane browsing as I feel that it's more conducive
to consuming information than the typical browser structure and it adds a unique feel to the site.
[[https://github.com/jakchv/cortex][Here]] is the template I use to publish this wiki.
I may consider other templates or alternative views in the future,
and will continue iterating on this design,
but I plan to keep this template around.

* References

I've taken inspiration from several others who maintain wikis.
- [[https://github.com/tommy-mor][Tommy Morriss]] first introduced me to the idea with his personal (private) wiki.
- [[https://jethro.dev][Jethro]] has easily accessible articles and templates that I've made use of to put this together.
- [[file:../people/100_rabbits.org][100 Rabbits]] publish all of their notes and information in a custom wiki framework.
  https://github.com/logseq/logseq is a cool framework that syncs with github
  https://github.com/kormyen/memex

* Further Inspiration

[[https://github.com/frankmcsherry/blog][Frank McSherry's blog]] is maintained entirely by .md files in a journal with a simple markdown index. Git *is* the UI.
https://github.com/jackmcdade/secret-public-journal
https://github.com/HermanMartinus/bearblog
https://github.com/bphenriques/knowledge-base elisp wiki
https://github.com/nikitavoloboev/knowledge
https://github.com/karlicoss/beepb00p
https://github.com/bennetthardwick/website
https://github.com/nikitavoloboev/knowledge -- i *love* the idea of visualizing the ralations of the notes as well as his rationale
https://github.com/aceyoung9/garden
https://github.com/binyamin/eleventy-garden

* Frameworks

[[https://github.com/buckket/twtxt][txtxt is a CLI microblogging service for 'hackers']]
https://codeberg.org/Valenoern/bopwiki microwiki
https://blot.im/ blog platform with no interface

* Notes

https://www.youtube.com/watch?v=nXgqnYVAzKk&app=desktop note citation system for vim and pandoc
https://blog.griffin.sh/2020/06/05/how-we-write/ improving language for blogging
https://jlelse.blog/posts/wiki-approach/ cool wiki approach :: find the best method for me ! I think writing a blog post is the best way to help me organize my thoughts, i should get that infrastructure up. nextcloud notes is also a good option, but i do have to set up a nextcloud server to handle that
https://dpitt.me/blog/2020/03/zettelkasten/
[[https://obsidian.md/][obsidian md knowledge base]]
[[https://www.thebrain.com/][The Brain]] is a digital memory solution written and maintained by the brother of Acronym's founder, Errolson,for many years. It's not well known in the technology space, but it's popular with creatives and researchers who often don't intersect with the field.

* organization

https://todaytakeseverything.wordpress.com/2016/09/29/the-bullet-journal-bulletproof/
doing things once a day and putting them in a bullet journal or something
https://www.reddit.com/r/philosophy/comments/1vn6uk/thoughts_on_the_meditations_by_marcus_aurelius/
https://www.veilance.com/gb/en/shop/mens/isogon-mx-jacket
https://www.srid.ca/689c4a39.html bulletproof web app for notes; uses reflex frp and obelisk framewrok
https://reflex-frp.org/ haskell web framework; uses tech called obsidian. feels very opinionated? not sure whether it is good or not
http://shpadoinkle.org/docs/getting-started/index.html some ui library someone is very passionate about, it is unclear whether it is good or worthwhile
https://nesslabs.com/digital-garden-tiddlywiki
https://seekr.github.io/zettel/#colophon

[[https://u14908331.ct.sendgrid.net/ls/click?upn=QT7cosm4pQAFMt8R3ewV2eA4J0Qknm69d17OQyiUW-2FSLjMQE6TDZ1zPsKaaYIbKWOJm7_gbAz1fQK-2FBqv-2FJI4vVhBff-2FImsvil-2BJhjmYU2Kz2iBmuR7p63e5vF-2FwLKesYoSOALzbaSiyqQabAX-2BNsYGdQEJXXikRX5GURqWCwLB8XN8MqXLEipir56MkdIC-2FVjSSGMun6dgO-2Bb6NzPGEfLV8qaGSGZkdyR7FlMZMWfAJOpyBl12Zp-2BzVoGLbUfXyb5-2F5ct3mbLVAS57kDasYOe4MMuxWI13Yr5SCX-2BhfPgtOJheXIEr5DD98p1kkXKt5tzI7z4XRc-2BCiuxJuf5Oay6TPTFHte5wE4BoCrwYphdMM2sPdH783h7HfLUMJwp-2FlyUyxz6Ll7O1zyZmlA-2BVf3gWZP8j5zfzGfGgmX6xCT-2B9K4wOufd7kJPqm2p31xo0AK616Ind0qyNHO-2Bw1lE44O5dmDd5eFLFdzodkh8vRjB37R6I7ak0XOL-2BXtUeSJU3wSNc-2FDoK6xy7pEvVFAw2fyXkAiwJnkTI1u0jZx18lpcnXwSuNFIU1y36rSz61EdsRhIv3sSIb6w2MiZP7nd6mCbp3Sge54m26BFdTJ5BnvJVnz1PY6CtYGYwIj6wnIpLxwBuZARBiAKyoTknx-2FyfQblojcldHLKa3hpZA-2FwRdmGRFCAkcivRtjvcmOGZU0-2BQ5LGbzKMyyGB7oGnwoFepuImzju1zVftHHoNvFUkkqd9AtIY7xpbjkiZ9P8rlfpIularpQ0uj7YMWLexRZOBdVepoUud7yVW-2FM4htc5cSKSTzw6498jzAOUzVBNtWPt-2BbmYbdPn1CHw6nI-2Bo-2FwRf-2BgH6gVFXnTLxW93egsqUkZzU7UmsciHGDIvpCabX898gjaMThw4-2BofQ6-2FNdzWcWTeT8SnklFSLWVT-2BCLruF1R0avDLKwAraJhTRIep9o8AkZDupePMLkbHwGjSznVCktZU8AFqSYAsLT1r9fS6HySJEvtYtjDlTHBPkSfu-2BshdXtNG0iDoPw5iHR4FODjqxNWEY33Byb6i8a1-2FJRX-2Bz9eJnvqB-2Fo5BOJ13y6JROSlYI18lq4oXX][gossip's web]]: a directory of home-grown personal websites, experiments and writing
https://www.wikiwand.com/en/Transclusion#overview both the subject of transclusion: the inclusion of one document in another - and the wiki itself are super good here
http://outliners.scripting.com/ 40 years of outliners
https://github.com/TymonZ/garden

[[https://notes.andymatuschak.org/Work_with_the_garage_door_up][working with the garage door up]] :: why we should learn with wikis in the open. 
