#+TITLE: Cooking

I find cooking to be incredibly intimidating, but it's often the case that many dishes are not difficult. Cooking is procedural precision with an eye and a nose for good taste.

As with other aspects of my life, I think it's important for what I eat and make to be minimal. If I buy minimally processed ingredients myself, the end result will be simple and healthy for me; the more processed an ingredient is, the greater its propensity to have health symptoms and consequences.

* Resources
https://www.becomingminimalist.com/yum-yum/
http://minimalistwoman.com/
https://minimalistbaker.com/recipe-index/ these aren't *actually* minimalist, but they all look like good recipes

* Ideas
[[https://s2.washingtonpost.com/1d27abc/5edfc39ffe1ff654c2f5ec7f/5e93d247ae7e8a0ab11998e8/14/39/c9204a21cfdf9036fb2167dfd3cc58a2][good bowls]]
- [[https://tasty.co/recipe/protein-packed-buddha-bowl][example bowl]]
  mom tips:
  - start with base; quinoa, brown rice, pasta
  - add toppings: roasted veggies, raw chopped veggies, cheese, beans
  - crunch: seeds, chips, chickpeas, croutons
  - sauce, dressing, salsa, sour cream, yogurt
  - chopped chicken or browned meat alternative on top of that
https://tasty.co/recipe/buffalo-cauliflower-tacos
- could top tacos with anything, or use flatbread and veggie gyro
[[https://www.allrecipes.com/gallery/meatless-pasta-recipes/?slide=f433b3a1-d96b-4b1e-8aab-051f9e07734d#f433b3a1-d96b-4b1e-8aab-051f9e07734d][good reference for meatless pasta recipe suggestions]]
