#+TITLE: Ethical Web

- Backlinks :: [[file:concepts/web.org][Web]]
Thoughts on the current state of the web and taking action to make it more ethical.

The modern web often forces all developers to adhere to more and more specifications (have you seen how long and convoluted the RFC manual is?), and lives in a world where only the companies that create the standards can practically adhere to them.

This is bad abstraction! This process is no different from forcing everyone who *uses* a technology to add specific components to their work rather than taking on this responsibility as the browser.

Of course, information like a robots.txt, a webpage title and these sorts of things should be standardized and mandated by the user -- but there are lots of sensible defaults, like keyboard-navigable websites, that could be applied and later overridden by the user if they don't like these defaults.

Not including these accessible features in a native application that runs these web services leads to substantial bloat and insecure (JavaScript) code execution to emulate accessiblity features that could easily be accepted by the browser, like onMouseKey functionality! What about using tab-enter to navigate links without having to tag said links with specific attributes?
