#+setupfile:./hugo_setup.org
#+hugo_slug: reasons-not-to-use
#+TITLE: Reasons Not To Use

Reasons not to use popular products and services, just like on RMS's website

* Adobe
uses the "software as a service" pattern which gives it complete control over who is allowed to use their software, and it can be revoked at any time, such as when a [government requires it](https://www.theverge.com/2019/10/7/20904030/adobe-venezuela-photoshop-behance-us-sanctions). With this licensing model, you never own what you're paying for, you're just renting it.

* AT&T
marketed "unlimited" data plans that were nonetheless throttled after reaching a certain threshold, for which they were rightfully [punished and ordered to refund $60 million](https://arstechnica.com/tech-policy/2019/11/att-users-whose-unlimited-data-was-throttled-get-60-million-in-refunds/). Right after that, they [forced customers to switch to more expensive data plans without asking them](https://arstechnica.com/information-technology/2019/11/att-adds-10-to-smartphone-bills-for-customers-with-older-plans/), presumably to make up for this loss. Broadband connections in USA are in general expensive and poor quality, as a result of local monopolies and lack of choices for consumers.

* Blizzard
[[https://playhearthstone.com/en-us/blog/23179289/][banned a player from a major tournament]] for offending the sensibilities of the Communist Party of China by [[https://www.pcgamer.com/blitzchung-removed-from-hearthstone-grandmasters-for-liberate-hong-kong-comments/][supporting the Hong Kong protests publicly]]. Blizzard is partially owned by Tencent, which in turn is owned by the Chinese government. History shows that it is exceedingly easy to offend the Chinese government with Winnie the Pooh memes and other nonsense - we should not let oppressive governments dictate what we are allowed to express, especially abroad.

* Google
's '"Project Nightingale" [[https://www.bbc.com/news/technology-50388464][included buying sensitive health-related records]] about Americans who were not even notified about their data being up for sale or having been sold. Google promises that this data will not be combined with existing consumer data (presumably for targeting ads), but it surely will, and it will not be the first time Google has bought sensitive private data from another company.

* Microsoft
- uses confusing UI patterns to [[https://www.zdnet.com/article/windows-10-users-fume-microsoft-wheres-our-local-account-option-gone/][coerce Windows users to create online accounts during installation]]
- [[https://www.theguardian.com/technology/2020/jan/10/skype-audio-graded-by-workers-in-china-with-no-security-measures][recorded private Skype conversations and Cortana commands and shared them with contractors without making any effort toward anonymizing them]], or asking the users for permission to record them. Security around these recordings was nonexistent. If you care about privacy, never use any programs that send your voice through third party servers, in particular Microsoft's.

- uses deliberately confusing UI patterns to [[https://www.howtogeek.com/442609/confirmed-windows-10-setup-now-prevents-local-account-creation/][force Windows users to create online accounts, instead of local ones during system installation]]. Making local accounts is only possible if you disconnect the computer from the Internet, but [[https://www.bleepingcomputer.com/news/microsoft/microsoft-wants-to-do-away-with-windows-10-local-accounts/][there are reasons to believe they will eventually force users to always use online Microsoft accounts]] for greater insight into their activities.

* Samsung
was caught [[rigging smartphone benchmarks, and reporting higher performance.][https://www.androidpolice.com/2019/10/02/samsung-galaxy-s4-class-action-lawsuit/]] The court ordered them to pay $10 per person, which is insultingly low.

* Tesla
can [[https://www.theverge.com/2020/2/6/21127243/tesla-model-s-autopilot-disabled-remotely-used-car-update][remotely disable many features of their cars after they're sold]]. This is reason enough to never buy them, as they can lose all value at the drop of a hat for any reason.
