#+setupfile:./hugo_setup.org
#+hugo_slug: vim
#+title: Vim

Vim is a text editor with an easily configurable extension language. It's most frequently used as a [[file:./terminal_ui.org][TUI]] program but also has an (aft-used) graphical application distribution (Gvim).

I've come to prefer the power of [[file:emacs.org][Emacs]] but I do miss Vim's performance.

However, it has a first-class editor-based extension language that's written to prioritize text processing and configuration. Its extensive, literate keybindings that have made their way into every popular text editor as well as many other applications.

It's one of best text-editing tools in the Unix ecosystem, and Vim users often have a library of cli and tui programs that they use in conjunction with Vim to facilitate a desktop ecosystem without a GUI.

Vim is often preinstalled on Unix systems. If it's unavailable, such systems will likely still have vi (or busybox vi), so taking the time to learn vim keybindings is worthwhile for their flexibility throughout programming environments.

* Tools
https://github.com/glacambre/firenvim neovim in the browser
https://github.com/puremourning/vimspector debugging system for vim
https://www.reddit.com/r/vim/comments/i0lffn/thought_id_share_some_recent_vimspector/
* Resources
https://www.reddit.com/r/vim/comments/i1tfux/i_have_fallen_to_vim/ learning more about vim mappings
https://www.reddit.com/r/vim/comments/h8pgor/til_conceal_in_vim/ -- concealing plaintext symbols with glyphs

* Plugins
https://www.reddit.com/r/vim/comments/i1p3s9/fernvim_a_modern_asynchronous_file_manager_for_vim/ async file manager, with lists of alternatives
https://www.reddit.com/r/vim/comments/i0tciv/you_liked_so_much_the_first_version_that_i/ a vim plugin for highlighting infomration in different colors while parsing a document
https://www.reddit.com/r/vim/comments/hvr09s/how_can_i_integrate_a_vim_text_editor_in_react/ adding vim text editor to react project
https://www.reddit.com/r/vim/comments/hxn5ue/how_do_i_use_macros_when_i_have_variable_amount/ meta macros for variable amounts of data
https://www.reddit.com/r/vim/comments/hwdehp/vim_osc_livecoding/ livecoding in vim
https://www.reddit.com/r/vim/comments/hy3yma/what_is_the_best_leader_key/ finding the best leader key
https://app.getpocket.com/read/3056881828 arbitrary variables in vimrcs
https://github.com/mhinz/vim-signify show a diff with vim sign column
https://github.com/francoiscabrol/ranger.vim rangerinteraction inside of vim
https://github.com/huyvohcmc/atlas.vim colorful vim theme?
